cuthbertLab/music21

music21/pitch.py
Functionality seemed to be missing... music21
=> Add accidental.listNames

music21/instrument.py
hey Myke there were no docs here.  ehhhh!
=> add docs to instrument

music21/pitch.py
A dummy pull request (for why see #112)
=> dummy pull request, added newlines

music21/corpus/josquin/4vPerIlludAveProlatum.abc, music21/corpus/josquin/adieuMesAmours.abc, music21/corpus/josquin/fortunaDunGranTempo.abc, music21/corpus/josquin/laDeplorationDeLaMorteDeJohannesOckeghem.abc, music21/corpus/josquin/laPlusDesPlus.abc, music21/corpus/josquin/milleRegrets.abc, music21/corpus/josquin/oVenusBant.abc, music21/corpus/josquin/petiteCamusette.abc
See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
=> Correct FSF address

music21/mei/base.py, music21/mei/test_base.py
As usual, I would be happy to make any style or functional requirements as requested. Thanks in advance!
=> For issue #125

music21/musicxml/m21ToXml.py, music21/musicxml/xmlToM21.py
[output before.txt](https://github.com/cuthbertLab/music21/files/428727/output.before.txt)
[output after.txt](https://github.com/cuthbertLab/music21/files/428728/output.after.txt)
=> Update m21ToXml.py and xmlToM21.py for MuseScore 2

.idea/vcs.xml
According the to master's branch .gitignore file we are ignoring all the .idea folder in the project. To comply with that I deleted the currently added .idea folder
Please note that the .gitignore file could be updated to include some of the .idea folder contents as shown here:
https://www.gitignore.io/api/pycharm
=> delete the idea folder from the repo

music21/demos/build_melody.py
Simple example of working directly with MidiFile/MidiTrack. Not sure if there should be more explanation accompanying this, or if there are links to these demos that need to be updated?
I have a few more useful demo scripts I'd like to contribute once I understand the process.
=> demo that shows how to build a MidiFile directly

music21/alpha/analysis/__init__.py, music21/alpha/analysis/aligner.py, music21/alpha/analysis/fixer.py, music21/alpha/analysis/hasher.py, music21/alpha/analysis/testFiles.py
branch with all the hash align fix files in it pulled from the most recent master that has the newest music21 updates... still trying to get back into the hang of things... going to wait until all the tests pass to see if i'm breaking any conventions
=> ported files to new branch

music21/stream/__init__.py
This was done primarily by removing some cases were extremely inefficient quadratic algorithms were used where a simpler linear (or at least linear for all reasonable midi files which don't have all notes in the same location) algorithm would work.
There are still several cases were quadratic algorithms are still used and they definitely should be optimized.
In my tests this made midi file loading approximately 5.5x faster.
=> Significantly improve performance of midi file loading.

music21/analysis/neoRiemannian.py
… complementing the existing options to generate that change.
=> Checks whether two chords are related by a single L, P, or R transform

music21/harmony.py, music21/stream/__init__.py
=> Change classSortOrder for Harmony to come before notes

music21/base.py
there were many inner functions that shadowed names from outer functions.  Hopefully this should fix it.
=> an attempt at a fix of context sites

music21/roman.py
scaleDegreeWithAlteration never worked as a setter -- making it read only.
=> Fix docs for roman

music21/sorting.py
Make modest performance improvements in the shortRepr, modify, add,
and sub methods in sorting.py.
=> Refactor four methods in sorting.py.

music21/figuredBass/checker.py, music21/figuredBass/examples.py, music21/figuredBass/notation.py, music21/figuredBass/possibility.py, music21/figuredBass/realizer.py, music21/figuredBass/realizerScale.py, music21/figuredBass/resolution.py, music21/figuredBass/rules.py, music21/figuredBass/segment.py
rename ambiguous "prog" to "progression"
=> Lint and add TypeHints to FiguredBass

music21/musicxml/m21ToXml.py, music21/musicxml/xmlToM21.py, music21/omr/correctors.py
=> do not run hyphenToCamelCase if m21 names are given

music21/musicxml/xmlToM21.py
Allows parsing Gluck score from @OpenScore
=> Allow wedges to pass with warning

music21/alpha/analysis/fixer.py, music21/alpha/analysis/ornamentRecognizer.py
Turn Fixer detects where a turn should be in music generated using OMR when compared against music generated from MIDI using the new Turn Recognizer. And inserts turn on appropriate omr note.
=> Turn Fixer

music21/roman.py
=> Fix scaleDegreeWithAlteration for Aug6 chords

music21/key.py, music21/scale/__init__.py, music21/scale/intervalNetwork.py
=> key.Key.deriveByDegree overloads on Scale

music21/chord/__init__.py, music21/interval.py, music21/layout.py
Also fix some small bugs in setting noteStart and noteEnd
Adds in a test for a particular problem in Chord with removing the bass or root from a chord.
Add a description in LayoutBase of what that does.
Fixes #524  -- Thank you @punyidea
=> Make reverse in transposePitch work consistently

.pylintrc, music21/converter/__init__.py, music21/converter/subConverters.py, music21/environment.py, music21/humdrum/__init__.py, music21/humdrum/spineParser.py, music21/musicxml/m21ToXml.py, music21/musicxml/xmlSoundParser.py, music21/musicxml/xmlToM21.py, music21/scale/__init__.py, music21/stream/__init__.py, music21/test/testLint.py
Fix some bugs in musicxml.png output -- especially the >999 pages warning
Fix new pylint 1.50 issues 
Also update some Humdrum code
=> Fix musicxml png output

.flake8, music21/braille/text.py, music21/common/misc.py, music21/converter/__init__.py, music21/features/base.py, music21/humdrum/__init__.py, music21/metadata/__init__.py, music21/metadata/primitives.py, music21/musedata/__init__.py, music21/musicxml/m21ToXml.py, music21/note.py, music21/omr/correctors.py, music21/search/serial.py, music21/stream/__init__.py, music21/test/multiprocessTest.py, music21/tree/core.py, music21/tree/trees.py, music21/variant.py
Clean up and diversify examples there.
=> add lyricist and librettist to metadata

music21/environment.py
=> Handle lack of local corpus path

music21/features/base.py, music21/features/jSymbolic.py, music21/features/native.py
=> Fixes #570: Improve feature extractor handling of streams without expected objects

music21/base.py, music21/converter/__init__.py, music21/converter/subConverters.py
=> Write compressed xml directly from .write('mxl')

.idea/dictionaries/music21.xml, music21/braille/basic.py, music21/duration.py, music21/expressions.py, music21/humdrum/spineParser.py, music21/note.py
=> Correct appogiatura to appoggiatura

music21/common/misc.py, music21/environment.py
=> Preview has changed on new macOS

music21/midi/translate.py
Fixed #606 Fixed #610 (duplicates)
=> Catch UnicodeDecodeError

music21/converter/__init__.py
Fixes #530, or better, refers to it, but I don't think we identified any other TODOs there except this one, so marking it for closing.
**Now**: add `-noQtz` or `-qld8`, etc., to a pickle path to capture any non-default quantization keywords.
=> Made pickles contemplate quantization keywords

music21/midi/translate.py
Now, repeats are expanded when writing MIDI.
=> Fixed #464: Expand repeats when writing MIDI

documentation/docbuild/iterators.py, documentation/docbuild/writers.py, documentation/source/usersGuide/usersGuide_03_pitches.ipynb, documentation/source/usersGuide/usersGuide_06_stream2.ipynb, documentation/source/usersGuide/usersGuide_26_iterators.ipynb, documentation/source/usersGuide/usersGuide_28_lyricSearcher.ipynb, music21/__init__.py, music21/graph/axis.py, music21/note.py, music21/pitch.py, music21/test/commonTest.py, music21/test/testRunner.py
Also remove some Py2 references / code workarounds
=> Update docs for pitch

music21/midi/__init__.py
=> Execute other.NoteOff in matchedNoteOff

documentation/source/usersGuide/usersGuide_03_pitches.ipynb, music21/base.py, music21/duration.py
=> Mention expression of quarterLength as Fraction in more places

documentation/source/usersGuide/usersGuide_23_romanNumerals.ipynb, music21/analysis/discrete.py
Fixes #463 
Thanks @ZM-J for the report and original patch!
=> Calculate key confidence for every pitch class in case of tie

music21/_version.py, music21/analysis/discrete.py, music21/base.py, music21/graph/plot.py, music21/midi/__init__.py, music21/pitch.py, music21/stream/__init__.py, music21/tree/verticality.py
Gives a way of preserving original pitches whenever possible within chordify
=> Chordify -- copyPitches -- update version

music21/harmony.py, music21/musicxml/xmlToM21.py
_updatePitches() is also added to the end of addChordStepModification. I can redo the pull request without that if that's something that shouldn't happen.
This fixes #665
=> Fix #665 by altering pitches in place

.github/workflows/maincheck.yml, .travis.yml, music21/stream/__init__.py, music21/test/coverageM21.py
=> Attempt to run coverage on Github Actions / 3.7

music21/musicxml/testPrimitive.py, music21/musicxml/xmlToM21.py, music21/stream/__init__.py
Fixes #728, and without much effort it turned out to be a huge nothing, since the example was out of date.
=> Check required tie attribute "type" and correct example

music21/converter/subConverters.py, music21/environment.py, music21/graph/plot.py, music21/graph/primitives.py, music21/lily/translate.py, music21/scale/__init__.py, music21/vexflow/toMusic21j.py
=> Remove deprecated Environment.launch()

music21/converter/subConverters.py
From recently merged change.
Just FYI @jacobtylerwalls to look out for next time we do a subprocess
=> If options is blank, not the same as an extra space subprocess 

music21/converter/__init__.py, music21/lily/translate.py
=> Proper rU mode for musedata

music21/instrument.py
Fixing an oversight in a recent feature.
=> Bug in deduplicate() returned early

music21/environment.py
Inspired by #679, handle #660 
Use tempfile.mkdtemp() to set and create default root temp directory.
This way is robust, cross-platform, and behave like the original routine.
~But it creates and deletes the temp directory for each python instance.~
=> Create a fallback for environment.getDefaultRootTempDir()

music21/roman.py
Note: I am the author of the code on which this is based, previously hosted at [MarkGotham/When-in-Rome](https://github.com/MarkGotham/When-in-Rome/blob/master/Code/anthology.py) and I agree to have this code re-released under music21's licenses, and the BSD license in particular.
=> roman.RomanNumeral.isMixture()

music21/mei/base.py
=> Check for elem.get('artic') is not None in articElement

music21/mei/base.py
(I anticipate that this) Fixes #765
=> Fix MEI _keySigFromAttrs None handling for accidental

.github/workflows/maincheck.yml, README.md, music21/test/testSingleCoreAll.py
Coveralls reporting 422 Client Error: Unprocessable Entity -- need to check why.
=> Tiny grammar fix to test coveralls

music21/musicxml/partStaffExporter.py
Fixed #774 
This patch handles the case where multiple `layout.StaffGroup` objects happen to enclose the exact same set of `PartStaff` objects.
=> Gracefully handle bracket and brace enclosing same PartStaffs

music21/scale/__init__.py
=> Fixes #784: instantiation of OctaveRepeatingScale and CyclicalScale

music21/meter.py, music21/stream/makeNotation.py, music21/test/testStream.py
First note in a measure does NOT always start partial beams.  Only if measureOffset is 0.0
=> Fix beaming in pickup measures

documentation/source/usersGuide/usersGuide_19_duration2.ipynb, music21/musicxml/xmlToM21.py, music21/spanner.py
=> Spanner exceptions

music21/chord/__init__.py, music21/musicxml/m21ToXml.py, music21/musicxml/testNC.xml, music21/musicxml/xmlToM21.py
=> Don't wipe chordKindStr value on already created NoChord object

documentation/source/usersGuide/usersGuide_17_derivations.ipynb
=> minor typo in usersGuide_17_derivations.ipynb

music21/note.py
allows for iterating over NotRest objects and collecting pitches.
=> Add pitches property to NotRest as well

music21/converter/subConverters.py
=> Don't raise CalledProcessError in .launch()

music21/lily/translate.py, music21/search/lyrics.py, music21/text.py
Composite lyrics with assembleText
re.escape on plaintext searches.
=> Fix some bugs that crept into lyrics

music21/base.py, music21/chord/__init__.py, music21/duration.py, music21/editorial.py, music21/harmony.py, music21/humdrum/__init__.py, music21/interval.py, music21/note.py, music21/roman.py, music21/stream/__init__.py, music21/stream/core.py, music21/stream/iterator.py
=> Remove functions marked as deprecated to remove in v7

music21/midi/translate.py, music21/stream/__init__.py
- recurse defaults False
- add tests for recurse and inPlace
=> V7 quantize signature

music21/braille/segment.py, music21/musicxml/xmlToM21.py, music21/stream/__init__.py, music21/test/testStream.py
https://github.com/cuthbertLab/music21/blob/4f67e0ddb4e5d9fce459d7aa0802b278de1c9d06/music21/stream/__init__.py#L3840-L3841
done!
https://github.com/cuthbertLab/music21/blob/4f67e0ddb4e5d9fce459d7aa0802b278de1c9d06/music21/stream/__init__.py#L3876
easy, because that was done in #734:
https://github.com/cuthbertLab/music21/blob/4f67e0ddb4e5d9fce459d7aa0802b278de1c9d06/music21/stream/__init__.py#L6303-L6304
=> measures() returns only relevant spanners

music21/base.py, music21/braille/runAllBrailleTests.py, music21/freezeThaw.py, music21/stream/__init__.py, music21/stream/core.py, music21/test/testStream.py
Also unify the derivation methods
=> Stream coverage

music21/converter/__init__.py
=> Raise FileNotFoundError when mistyped paths end in correct extension

music21/stream/makeNotation.py
=> Fix crash on empty chords in getStemDirectionForPitches

music21/chord/__init__.py, music21/harmony.py
=> Clear figure when transposing ChordSymbol

.github/scripts/install_ubuntu_deps.sh
This should fix the CI problems. 🙏🏻
=> Bump Lilypond to 2.22.0 in GitHub Actions script

music21/_version.py, music21/base.py, music21/converter/__init__.py, music21/freezeThaw.py, music21/midi/translate.py
Fixes #824 
Now, measures are made when MIDI files are imported.
=> MIDI import makes measures

music21/style.py
```
>>> from music21 import style
>>> s = style.Style()
>>> if 'Style' in s.classes:
...    print('make toast')
... 
AttributeError: 'Style' object has no attribute 'classes'
```
=> Let Style objects inherit from ProtoM21Object

music21/common/numberTools.py, music21/converter/__init__.py, music21/features/jSymbolic.py, music21/stream/base.py
=> Deprecate almostEquals() in favor of math.isclose()

music21/duration.py
Cherry-picked from #763 so that we can attack this in manageable pieces.
=> Add attribute expressionIsInferred to Durations

music21/_version.py, music21/bar.py, music21/base.py
=> Barline doesn't need to inherit from StyleMixin

music21/pitch.py
=> Set spellingIsInferred in Pitch.transpose(inPlace=True)

music21/clef.py
=> returns downward directions for stems in tabs

music21/chord/__init__.py, music21/expressions.py, music21/pitch.py, music21/roman.py, music21/stream/makeNotation.py
Fixes #529
Diagnoses that there are larger problems with postFigureFromChordAndKey  not taking into account major and minor differences.  It needs a major refactor  BUT this is a step in the right direction and for helping give many better test cases
Also fixes a small bug in Mordents and intervals in Expressions and adds some typing in makeNotation -- it's not related but I accidentally had it sitting around the same directory.
=> Sensible Defaults for Augmented 6th

music21/duration.py, music21/stream/tests.py
Fixes #959 
The one existing test that needed changing looked appropriate.
=> Inform client when setting tuplets

music21/converter/__init__.py
The module level function had this keyword, but it was dead, because it didn't exist on `Converter.parseURL()`.
Noticed when looking at the CI failure on #948 .
=> Add `forceSource` to `Converter.parseURL()`

music21/analysis/floatingKey.py
Measure numbers were assumed to be 0-indexed (`for i in range(self.numMeasures):`), but accessed with `.measure()`, which gets the _actual_ measure numbers, so this only worked exactly right for pieces with pickup measures, like the Bach chorale in the doctest. That is, for pieces without pickup measures, the last measure was never reached.
=> Let floating KeyAnalyzer reach final measure in streams without pickups

music21/musicxml/xmlToM21.py
Fixes #971
Also use `opFrac()` more.
=> Enforce a floor of 0.0 for measure offset when parsing `<backup>`

.github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md, README.md, documentation/source/developerReference/documenting.rst
and a Feature Proposal template.
The idea is that this should show up in convenient places around GitHub to give people the confidence to get started / follow through.
=> Contributing Guidelines

music21/meter/tools.py
=> Raised TimeSignatureException when instantiating with a string representing floats

music21/lily/translate.py, music21/mei/base.py, music21/mei/test_base.py, music21/note.py, music21/stream/base.py, music21/variant.py
After doing this, however, maybe spacer rests ARE different from just hidden rests?  Now after wanting to remove them for years, I'm conflicted.  @jacobtylerwalls -- want to weigh in?
=> Remove SpacerRests, normal rests with hideObjectOnPrint

music21/abcFormat/__init__.py, music21/capella/fromCapellaXML.py, music21/converter/__init__.py, music21/converter/subConverters.py, music21/freezeThaw.py, music21/lily/translate.py, music21/metadata/caching.py, music21/midi/__init__.py, music21/musedata/__init__.py, music21/musicxml/m21ToXml.py, music21/musicxml/xmlToM21.py, music21/romanText/rtObjects.py, music21/scale/scala/__init__.py, music21/stream/base.py, music21/test/multiprocessTest.py, music21/tree/trees.py
Suppressed the warnings for `consider-using-with` when there was a set of `open()`, `read()`, and ` write()` methods that would need a bigger refactor. Resolved the others.
multiprocessTest generated a huge diff, but it's just indentation and breaking lines on an f-string that would have gone over the line length limit.
Refactored `SubConverter.writeDataStream()` -- this is where I want eyes when you have time. (No rush!) There were too many branches before, IMO. Separated the decoding logic from the writing logic to reduce repetition.
=> Resolve Pylint consider using with and consider using max/min violations

music21/midi/translate.py
Refs #988 (but doesn't close it, since we will track the MusicXML issues there)
cc @retorquere, thanks again for finding it!
=> Catch MIDIPercussionException and just emit a warning

documentation/source/usersGuide/usersGuide_15_key.ipynb, music21/analysis/discrete.py, music21/graph/plot.py
Fixes #998 
As discussed on the ticket, we can consider making a copy and doing a .flat for the user in v7, but then we should decide if we will ALWAYS make a copy, etc., if not--then sometimes .srcStream will be the source stream and sometimes it won't.
=> Fix key plot legend colors

music21/stream/makeNotation.py
=> Avoid deepcopies in `makeMeasures()`

music21/midi/translate.py
=> Fix crash exporting MIDI from stream with instrument but lacking notes

music21/converter/subConverters.py, music21/environment.py
Fixes #260
Google Colab with a fresh install of musescore and music21 from this branch showing everything working without setting any variables 🎉 
https://colab.research.google.com/drive/11hqRvss6Ai7Tu-H5g5dj6MHtbQ2CfmKO#scrollTo=ev4Emn7ahcy0
=> Defaults for headless MuseScore in Google Colab

music21/scale/__init__.py
=> Fix abstract scale network building with implicit octaves

music21/chord/__init__.py
=> Support single-note chord strings in Chord constructor

music21/stream/makeNotation.py
Fixes #1065, then will add a port for m21j next.
=> Handle "unspecified" direction in middle of a beam group

music21/musicxml/m21ToXml.py
Fixes #1022 (unless there is another use case you'd like to present)
(force-pushed to correct commit msg)
=> `fromGeneralNote()` stream packer creates multiple measures

documentation/source/usersGuide/usersGuide_27_graceNotes.ipynb, music21/analysis/reduction.py, music21/graph/primitives.py, music21/instrument.py, music21/midi/translate.py, music21/musicxml/xmlToM21.py, music21/pitch.py, music21/repeat.py, music21/search/serial.py, music21/stream/base.py, music21/stream/makeNotation.py, music21/stream/tests.py, music21/variant.py
A miscellany branch mostly related to recent PRs.
Highlights involve speeding up makeRests() and MIDI parsing--details in commit messages.
=> [misc] Optimizations related to recent PRs

music21/corpus/manager.py
=> Prevent test failures on systems with local corpus entries

.github/workflows/pythonpylint.yml
Until https://github.com/PyCQA/pylint/issues/4891 is resolved.
=> Pin pylint==2.9.6

music21/stream/base.py
Cleanup after #857: two blank lines after classes
=> Restore blank line

music21/midi/translate.py
Regression in dc97d02083f4b69bd6f1ef8cdd4e325aac8fc40f
=> Prevent crash in MIDI parsing from grace note chord

music21/meter/base.py
See doctest: beams were being inappropriately made on final notes in final incomplete measures.
=> Make beaming aware of paddingRight

music21/musicxml/m21ToXml.py
Fixes #1106 
The variety of changes reverted suggests to me it was an oversight, but let me know if there was an intent I need to be aware of. Cheers.
=> Restore recent changes to musicxml export

documentation/source/usersGuide/usersGuide_28_lyricSearcher.ipynb, music21/analysis/reduceChords.py, music21/freezeThaw.py, music21/musicxml/m21ToXml.py, music21/musicxml/xmlToM21.py, music21/noteworthy/translate.py
Typos, fixes, and cleanups (see commit messages)
=> September miscellany

music21/chord/__init__.py, music21/converter/__init__.py, music21/instrument.py, music21/metadata/__init__.py, music21/musicxml/m21ToXml.py, music21/musicxml/xmlToM21.py, music21/pitch.py, music21/stream/__init__.py, music21/vexflow/toMusic21j.py
Only show one copy of music21 software in MusicXML output.
Add more typing information in musicxml processing.
=> Typing fixes and improvements to <software>

music21/corpus/demos/two-parts.xml, music21/musicxml/xmlToM21.py
=> MusicXML import: Stop duplicating MetronomeMarks in multi-staff parts

.github/workflows/pythonpylint.yml, .pylintrc, documentation/docbuild/documenters.py, documentation/docbuild/writers.py, documentation/source/usersGuide/usersGuide_10_examples1.ipynb, documentation/source/usersGuide/usersGuide_61_trees.ipynb, documentation/testDocumentation.py, music21/abcFormat/__init__.py, music21/converter/subConverters.py, music21/instrument.py, music21/musicxml/xmlToM21.py, music21/test/testLint.py, music21/variant.py
A branch with some cleanups.
Highlights:
- Thanks @daniellumertz for reporting on google groups that `.color` is not correct, should be `.style.color`
- Fixes #1179
- resolve a `StreamIteratorInefficientWarning` in `instrument.deduplicate()`
=> November cleanups

music21/pitch.py
Fixes #1191
Issue since introduction in #128 (v.5.0.3.a1). Thanks to Brian Lee for the report.
=> Fix dissonance score for compound intervals

music21/harmony.py
Fix the failing tests for add, alter, omit, and subtract in chord figures.
=> Fix parsing of add, alter, omit, and subtract in chord symbol figures

music21/base.py, music21/common/classTools.py, music21/sites.py
also fix bug in common.isIterable
=> allow classes in getSpannerSites

music21/pitch.py
=> Fix accidental status overriding for initial diatonic naturals

music21/pitch.py
=> Fix accidental display after note intervenes between identical chromatic pitches

music21/corpus/__init__.py, music21/corpus/corpora.py, music21/harmony.py
=> Fix chord symbol duration realization edge case

music21/spanner.py
Fixes #1204
@gregchapman-dev could you take a look?
=> Fix numbering of crescendos and diminuendos in musicXML export

music21/harmony.py, music21/musicxml/m21ToXml.py
See https://github.com/cuthbertLab/music21/pull/1166#issuecomment-1010504878.
=> Realize NoChords as rests if writeAsChord = True

music21/musicxml/m21ToXml.py
=> Fix export of chord symbols with realized durations

music21/musicxml/m21ToXml.py
Solve an issue with musicxml export failing.
**Scenario**
Since eb1c953, musicxml import creates unlinked durations when there are discrepancies with the given types (e.g. due to tuplets and rounding errors). This can leave small gaps. If gaps are filled with hidden rests such as during voice creation, musicxml export chokes on "Inexpressible" durations.
**Solution**
Instead, for hidden inexpressible rests, just create `<forward>` tags.
=> Represent inexpressible gaps as `<forward>` tags

music21/musicxml/xmlToM21.py
When this MusicXML import warning happens, it probably repeats hundreds of times (since it's just warning about less-than-ideal behavior by the software that produced the musicxml doc).
```
Cannot put in an element with a missing voice tag when no previous voice tag was given.  Assuming voice 1... 
```
To avoid duplicating this hundreds of times, just convert to a python warning instance (MusicXMLWarning) which by default emits once but can be filtered, shown always, raise exceptions, etc.
We were going to do this anyway as part of #254.
=> Make all import warnings MusicXMLWarning

music21/midi/translate.py
Fixes #1224
Thanks @saintmatthieu for the report.
=> Fix MIDI export of meter changes

music21/base.py
=> Fix next(activeSiteOnly=True) finding things in other streams

music21/musicxml/xmlToM21.py
=> Import non-default instrument transpositions (musicxml)

music21/roman.py
Fixes #1218 (Mark had additional proposals there that might benefit from a new issue)
@malcolmsailor @MarkGotham does this resolve your issue?
=> Distinguish which figures imply a bass note

music21/roman.py
As proposed by @mscuthbert after @napulen (#1210)
=> Implements N53 (root position Neapolitan) #1210 

music21/configure.py, music21/figuredBass/possibility.py
updates for staying on latest pylint (2.14)
=> Pylint fixes to unblock CI

music21/duration.py, music21/meter/base.py, music21/musicxml/lilypondTestSuite/__init__.py, music21/stream/base.py
I heard the word "release," so figured I'd PR this old branch for adding warnings for already advertised deprecations.
=> Add warnings for already noticed deprecations

music21/mei/base.py, music21/mei/test_base.py
Fixes issue reported on m21 list
=> Force MEI parser to create unique elements

music21/musicxml/xmlToM21.py
=> [musicxml import] Prevent loss of inner tuplet's type

music21/bar.py, music21/musicxml/xmlToM21.py
=> [musicxml import] Catch BarException from presence of "times" attribute on start repeats

.pylintrc, music21/dynamics.py, music21/environment.py, music21/expressions.py, music21/meter/tests.py, music21/note.py, music21/prebase.py, music21/stream/base.py, music21/stream/iterator.py, music21/style.py, music21/tempo.py, music21/test/testLint.py
Implement the work around with dummy code shown in:
https://github.com/PyCQA/astroid/issues/1015
Unrelated (should pull out): Improve documentation for Expressions, Dynamics
add style docs.
=> Work around not-an-iterable bug; Expr. docs; rem .iter.

.github/workflows/pythonpylint.yml, music21/meter/base.py, music21/meter/core.py, music21/meter/tools.py
Uses a Sentinel MeterSequence so that all Sequences are always defined
=> Meter Typing

music21/search/lyrics.py
New version of mypy is a little more stringent.
=> Fix a mypy complaint.

music21/duration.py, music21/stream/base.py, music21/stream/tests.py
=> Patch duration linked bugs

music21/musicxml/m21ToXml.py, music21/stream/base.py, music21/stream/makeNotation.py, music21/stream/tests.py
Fixes #1345 
One more bug (duplicate measure being put into stream) emerging but seems to be only partly related.  Might try to fix within this PR or open a new one.
See also new comment on #866
=> makeTies within makeNotation; getTimeSignatures recurse

dist/dist.py
I'm a big fan of checklists. So I just added a suggestion to boost confidence when doing tags in the future. (Ref #1284)
=> More specific instructions for tagging commits

documentation/docbuild/writers.py, documentation/source/_themes/m21/static/m21.css, music21/__init__.py, music21/base.py, music21/common/enums.py, music21/common/pathTools.py, music21/common/types.py, music21/corpus/chorales.py, music21/duration.py, music21/meter/__init__.py, music21/meter/base.py, music21/midi/translate.py, music21/musicxml/m21ToXml.py, music21/musicxml/xmlToM21.py, music21/sorting.py, music21/stream/base.py, music21/stream/iterator.py, music21/stream/makeNotation.py, music21/test/testRunner.py, music21/tree/core.py, music21/tree/trees.py
=> Docs improvements.  Fix Pylint RecursiveIt typing

music21/base.py, music21/stream/base.py, music21/stream/iterator.py
putting the Generic in the Sequence.
Will also try OffsetIterator now, but RecursiveIterator errors what was making dev on PyCharm super annoying.
=> RecursiveIterator typing fixed

music21/duration.py
A little nothing change to make sure all tests are currently passing
=> Make small docs improvement to informClient

music21/roman.py
=> Validate figures provided to `RomanNumeral()`

music21/base.py, music21/expressions.py, music21/test/test_base.py
Accidentally committed to the main branch.  Checking if any damage was done and if I need to revert or keep going.  (Was working on expressions and thought I was on a branch)
=> Accidental commit to master -- damage?

.github/workflows/maincheck.yml, music21/expressions.py, music21/test/coverageM21.py
=> Test protected branch workflow

music21/_version.py
a nothing PR, which in the past I would've pushed straight to main.
=> Update version docs

music21/roman.py
=> Fix problem with add#7

music21/converter/__init__.py
=> Add timeout minimum to requests.get

music21/musicxml/partStaffExporter.py
Fixes #1400
Previously, the part staff exporter overzealously deduplicated `<barline>` tags (including child `<repeat>` tags).
Now, it checks that the `location` attribute is identical before deduplicating.
Prevents losing forward barlines as reported in #1400.
@gregchapman-dev does this resolve your issue?
=> Fix loss of forward repeat marks when exporting PartStaffs

documentation/docbuild/documenters.py, music21/abcFormat/__init__.py, music21/analysis/elements.py, music21/braille/basic.py, music21/corpus/chorales.py, music21/corpus/corpora.py, music21/duration.py, music21/dynamics.py, music21/features/base.py, music21/figuredBass/checker.py, music21/figuredBass/notation.py, music21/figuredBass/possibility.py, music21/figuredBass/realizer.py, music21/figuredBass/resolution.py, music21/figuredBass/segment.py, music21/harmony.py, music21/instrument.py, music21/mei/base.py, music21/metadata/bundles.py, music21/metadata/caching.py, music21/meter/core.py, music21/roman.py, music21/search/segment.py, music21/sieve.py, music21/stream/base.py, music21/tempo.py, music21/test/multiprocessTest.py, music21/text.py
Probably not slowing anything down, but real inconsistency in docs.
=> Tons of unnecessary imports in doctests

music21/corpus/manager.py, music21/metadata/bundles.py
gotta fix the coverage huge drop!
=> tiny fix -- distracted

music21/analysis/correlate.py, music21/base.py, music21/chord/__init__.py, music21/clef.py, music21/converter/__init__.py, music21/duration.py, music21/dynamics.py, music21/editorial.py, music21/graph/__init__.py, music21/graph/plot.py, music21/graph/primitives.py, music21/instrument.py, music21/key.py, music21/meter/base.py, music21/meter/tests.py, music21/midi/percussion.py, music21/note.py, music21/pitch.py, music21/roman.py, music21/search/base.py, music21/serial.py, music21/spanner.py, music21/stream/base.py, music21/tempo.py, music21/test/commonTest.py, music21/test/coverageM21.py, music21/test/testSingleCoreAll.py, music21/test/test_base.py, music21/test/test_pitch.py, music21/voiceLeading.py
Coverage dropped 10% when moving to not using imp -- need to understand why.  Various tests.  Will take some time.
=> Coverage drop!

.github/workflows/maincheck.yml, .github/workflows/pythonpylint.yml, dist/dist.py
Also upgrade setup-python to v4
=> Fix mypy with github

documentation/docbuild/iterators.py, music21/analysis/enharmonics.py, music21/analysis/patel.py, music21/analysis/segmentByRests.py, music21/articulations.py, music21/defaults.py, music21/dynamics.py, music21/editorial.py, music21/exceptions21.py, music21/expressions.py, music21/features/base.py, music21/figuredBass/notation.py, music21/figuredBass/rules.py, music21/metadata/caching.py, music21/musedata/translate.py, music21/roman.py, music21/romanText/rtObjects.py, music21/romanText/translate.py, music21/romanText/tsvConverter.py, music21/stream/iterator.py, music21/test/treeYield.py, music21/text.py, music21/tie.py, music21/voiceLeading.py
Remove 17 Exceptions that were never used.  And one that used the name of a theorist used in one place.
=> Reduce 172 Exceptions to 154

music21/_version.py, music21/base.py, music21/interval.py, music21/key.py, music21/percussion.py, music21/roman.py, music21/scale/__init__.py, music21/stream/base.py, music21/test/test_base.py, music21/test/treeYield.py, music21/voiceLeading.py
All Music21Objects must not crash on `m = MyM21Object()` and `{m: 1}` must be valid.
=> All Music21Objects must be hashable and default instantiate

music21/roman.py
Also a de facto doc test for the upper/lower case issue discussed there.
=> adds doc for RN from int, following #1481

music21/chord/__init__.py
`sortAscendingDiatonic()` sorts by DNN, not by "scale degree". Adjust docstring.
=> Remove reference to "scale degree" in `sortDiatonicAscending()`

music21/expressions.py
m21ToXml.py already checks if hasattr(blah, 'placement'), so all we need is this one line change.
=> Give GeneralMordent placement like Turn and Trill have.

music21/pitch.py, music21/test/test_interval.py
Make p.accidental = 2 a bit faster.
=> Tiny change to make .accidental

music21/graph/primitives.py, music21/harmony.py
=> Observe updatePitches=False when bass or root provided

music21/chord/__init__.py, music21/romanText/translate.py
Fixes #1531
(also includes an unrelated note about how chord root might be sped up in future -- hope to implement someday)
=> RomanText: allow Note fields with anacrusis

music21/stream/core.py
=> minor docs fixes to coreInsert

music21/common/numberTools.py, music21/musicxml/xmlToM21.py
Ensure that opFrac never returns Fraction(0, 1)
Fixes #1544 
Thanks @jacobtylerwalls and @vanderstel
=> fix opfrac for small numbers

music21/converter/subConverters.py
A breaking change in the music21j github.io repo is breaking MIDI output in Jupyter.  This will fix it.
=> Backport 1565 to m21 v8

requirements_minimum.txt
=> Add `requests` to minimum requirements

documentation/source/about/faq.rst, music21/configure.py, pyproject.toml
Not using my mit.edu email much any more.
=> More email things

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I don't know how to make PULL_REQUEST_TEMPLATES or I would put them there too.
=> add sabbatical issue templates

music21/musicxml/m21ToXml.py, music21/musicxml/partStaffExporter.py, music21/musicxml/xmlToM21.py
Resolves deprecation warnings in python 3.12
Refs https://github.com/python/cpython/pull/31149
(mypy failure fixed in #1665)
=> Avoid testing truth value of ElementTree.Element 

.gitignore, music21/base.py, music21/note.py, music21/tree/timespanTree.py, music21/tree/verticality.py, music21/voiceLeading.py
Add safety to getAllVoiceleading quartets
add some typing.
=> iterateAllVoiceLeadingQuartets()

README.md
Using correct pronouns, not choice of pronouns (previous wording wasn't good no matter what viewpoint a person has! :-) )
=> Code of Conduct Clarify

music21/_version.py, music21/base.py, music21/expressions.py, music21/musicxml/m21ToXml.py, music21/musicxml/testPrimitive.py, music21/musicxml/test_m21ToXml.py, music21/musicxml/test_xmlToM21.py, music21/musicxml/xmlToM21.py, music21/stream/base.py
Ready for a (second) review, although I'm not going to call it done until I have finished implementing Humdrum read/write and MEI read/write in converter21.
=> PedalMark support

CONTRIBUTING.md
Add note about when AI contributions are allowed, but how they will not get review comments.
=> CONTRIBUTING.md -> AI contributions

documentation/source/usersGuide/usersGuide_07_chords.ipynb
Dummy PR as suggested by @mscuthbert in https://github.com/cuthbertLab/music21/pull/1580#pullrequestreview-2834959101 to get actions rights
I only added backticks for two methods.  `testDocumentation.py` worked fined on the file I changed. I hope that's okay!
Cheers
=> Minor doc update: User's guide Chords

music21/alpha/analysis/aligner.py, music21/analysis/correlate.py, music21/analysis/discrete.py, music21/audioSearch/__init__.py, music21/audioSearch/recording.py, music21/audioSearch/scoreFollower.py, music21/audioSearch/transcriber.py, requirements.txt
=> Allow numpy 2.0+ with music21

music21/lily/translate.py, music21/musicxml/m21ToXml.py
Can a Windows User try this and report back?  Thanks!
=> Improve Lilypond opening in Windows

music21/configure.py
=> Support Dorico as MusicXML reader.

music21/environment.py
make keys more like dict, and add items() and values() to environment.UserSettings
=> Make UserSettings more dict-like
