cuthbertLab/music21

- music21/lily/translate.py
I just stumbled upon `music21`, tried to run some examples from the documentation and got a weird error with no obvious error message. After some debugging it turned out that this was due to Lilypond not being installed on my system, but the missing Lilypond executable was not detected correctly.
Currently the logic in `music21/lily/translate.py` (line 194) assumes that a `KeyboardInterrupt` is thrown if Lilypond is not installed, but I don't see how this would ever be triggered by trying to split the version string (which is what happens in the `try...` block in line 190ff).
This PR implements a cleaner way. By avoiding to use `shell=True` in the call to `subprocess.Popen` an `OSError` is triggered if Lilypond is not found, which can be caught directly.
> Fix Lilypond detection

- music21/stream/__init__.py
Mention in docstring that numberEnd=None is interpreted as 'last measure'.
> Minor docstring addition

- music21/__init__.py
This is in compliance with PEP 396 (see [specification](https://www.python.org/dev/peps/pep-0396/#specification))
> Add toplevel __version__ attribute

- installer.command
Previously the installer command file was malformed and did not work on OSX (it complained of file not found). This was because the shell interpreted DIRFILE as a command, not a variable.
This commit fixes this by removing spaces around the DIRFILE variable assignment.
> Fixed: installer.command updated to work on OS X

- MANIFEST.in
The tests were failing when run from the installed package,
because those files were missing:
```
ERROR: testImportMei3 (converter.subConverters.Test)
File "music21/converter/subConverters.py", line 1096, in testImportMei3
testConverter.parseFile(testPath)
File "music21/converter/subConverters.py", line 988, in parseFile
with open(filePath) as f:
IOError: [Errno 2] No such file or directory: music21/mei/test/notes_in_utf16.mei
ERROR: testImportMei4 (converter.subConverters.Test)
-------------------------------------------------------------------- …
```
> Distribute .mei and .nwc files

- music21/lily/translate.py
Hi, I noticed that the LilyPond output doesn't actually display colors in the `note.editorial.color` property. In fact, there were some errors on the current version, e.g.:
>>> import music21.note
>>> n = music21.note.Note('G')
>>> n.editorial.color = 'red'
>>> n.show('lily')
GNU LilyPond 2.18.2
Changing working directory to: `.../music21'
Processing `.../music21/tmpyxX2wAly'
Parsing...
.../music21/tmpyxX2wAly:5:45: error: GUILE signaled an error for the expression beginning here
\once \override NoteHead #'color = #
(x11-color $color)
... (similar errors)
It still displays the note, but it is black. I'm not familiar with Scheme myself, but I changed the lines such as:
\once \override NoteHead #'color = #(x11-color $color)
to use `color` instead of `$color` in the LilyPond output, and that …
> Fixed LilyPond colors

- music21/features/jSymbolic.py
In `features.jSymbolic.MelodicIntervalHistogramFeature` normalization was done the wrong way. Before it was done in such a way, that the maximum histogram-bin always was equal to one. Now it is done in such a way, that the sum of all histogram-bins is equal to one.
Relevant passage from the jMIR thesis:
> The histogram is then normalized, so that the magnitude of each bin indicates the fraction of all melodic intervals that correspond to the melodic interval of the given bin.
Cory McKay: *Automatic Music Classification with jMIR*, PhD 2010, p. 227, [PDF](http://www.music.mcgill.ca/~cmckay/papers/musictech/mckay10dissertation.pdf).
> Changed normalization in MelodicIntervalHistogramFeature histogram should sum to 1

- music21/documentation/library/writers.py
this is supposed to fix the following error when trying to build the documentation on windows.
```
[NbConvertApp] Writing 20437 bytes to c:\users\bagratte\source\repos\music21\music21\documentation\autogenerated\usersGuide\usersGuide_02_notes.rst
File "make.py", line 141, in <module>
main(runMode)
File "make.py", line 88, in main
documentation.IPythonNotebookReSTWriter().run()
File "c:\users\bagratte\source\repos\music21\music21\documentation\library\writers.py", line 235, in run
nbConvertReturnCode = self.convertOneNotebook(ipythonNotebookFilePath)
File "c:\users\bagratte\source\repos\music21\music21\documentation\library\writers.py", line 315, in convertOneNotebook
oldLines = f.read().splitlines()
File "C:\Program Files\Python …
```
> make documentation build on windows

- music21/chord/__init__.py
- music21/pitch.py
I fixed an issue that bothered me. I am not sure if it is solved in the best way, but maybe this could find its way into music21 somehow?
The issue is the following: If I give a chord only pitch classes or midi names, it could take it in a very a-musical way. Here is an example where a B/C- major triad is totally mistaken:
>>> from music21 import *
>>> c = chord.Chord([11,3,6])
>>> c.pitches
(<music21.pitch.Pitch B>, <music21.pitch.Pitch E->, <music21.pitch.Pitch F#>)
>>> c.pitchedCommonName
'E--major triad'
I fixed it, by giving the Pitch a 'context'-keyword. This keyword gets a list of pitches and it is used for finding the best name for a pitch by maximizing the consonant intervals of the pitch with its context:
>>> c = chord.Chord([11,3,6])
>>> c.pitches
(<music21.pitch.Pitch B>, …
> guess best enharmonic name for notes in chords

- music21/chord/__init__.py
- music21/interval.py
- music21/pitch.py
I spot an undesirable behaviour in `simplifyMultipleEnharmonics`. Since it relied on `interval.isConsonant()`, e.g. it considered a perfect fourth and an augmented third equal -- both are non-consonant. So I wrote a simple custom consonance function.
Before:
In [1]: pitch.simplifyMultipleEnharmonics([3, 8, 0])
Out[1]: [<music21.pitch.Pitch E->, <music21.pitch.Pitch G#>, <music21.pitch.Pitch C>]
Now:
In [1]: pitch.simplifyMultipleEnharmonics([3, 8, 0])
[<music21.pitch.Pitch E->, <music21.pitch.Pitch A->, <music21.pitch.Pitch C>]
> custom consonance function for simplifyMultipleEnharmonics

- music21/documentation/source/usersGuide/usersGuide_04_stream1.ipynb
- music21/dynamics.py
In the case of subito dynamics I came across this little bug:
d = dynamics.Dynamic('sfp')
n = note.Note('C4')
s = stream.Stream()
s.append(d)
s.append(n)
n.volume # TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
I fixed this by ignoring subito in any case. Not sure if this is the very best solution? It fixes the error anyway.
(The small fix in the documentation is unrelated.)
> Error with subito when getting scalar of dynamics

- music21/chord/__init__.py
- music21/interval.py
- music21/pitch.py
I tried to improve the scoring in simplifyMultipleEnharmonics. Before it just took the Pythagorean ratio into account. Now it also takes into account that double-accidentals should be avoided and there thirds should be rewarded.
I also refactored a bit.
Myke, you also suggested some Monte Carlo method for doing better than greedy-left-to-right. As far as I know Monte Carlo would be stochastic and so there could be a different result every time. So a deterministic global optimization method would be needed... I am not having an idea yet, but maybe something would be possible.
> simplifyMultipleEnharmonics with better scoring

- music21/dynamics.py
I made a simple fix to give the default volumeScalar to any dynamic string that is unknown. Related issue: #121. Example:
from music21 import *
d = dynamics.Dynamic('sfz')
n = note.Note('C4')
s = stream.Stream()
s.append(d)
s.append(n)
n.volume
Before this returned an error, now it returns `<music21.volume.Volume realized=0.99>`.
> Give default volumeScalar to unknown dynamics

- music21/stream/__init__.py
Consider the following:
s = stream.Score()
m1 = stream.Measure()
m2 = stream.Measure()
m1.append(tempo.MetronomeMark('Adagio'))
m1.append(note.Note('D4', quarterLength=4))
m2.append(tempo.MetronomeMark('Allegro'))
m2.append(note.Note('C4', quarterLength=4))
s.append(m1)
s.append(m2)
Calling `s.metronomeMarkBoundaries()` raised this error because the MetronomeMarks have been searched in a non-flatted stream:
an entry for this object <music21.tempo.MetronomeMark Adagio Quarter=56> is not stored in stream <music21.stream.Score 0x7f0fcde08cc0>
Now it correctly returns:
[(0.0, 4.0, <music21.tempo.MetronomeMark Adagio Quarter=56>),
(4.0, 8.0, <music21.tempo.MetronomeMark Allegro Quarter=132>)]
> bugfix: metronomeMarkBoundaries for multiple MetronomeMarks in nested stream

- music21/environment.py
File descriptors for temp files have not beeen properly closed. This is resolved now.
My use case: I have an restrictive limit of opened files:
$ ulimit -n
1024
If I write quite some files with music21, it returned an error:
>>> import os
>>> from music21 import *
>>> s = stream.Stream()
>>> s.append(note.Note('C4'))
>>> for i in range(1025):
...     fp = s.write('musicxml')
...     os.remove(fp)
... 
File "<stdin>", line 2, in <module>
File "/usr/local/lib/python3.5/dist-packages/music21/stream/__init__.py", line 249, in write
File "/usr/local/lib/python3.5/dist-packages/music21/base.py", line 2514, in write
File "/usr/local/lib/python3.5/dist-packages/music21/converter/subConverters.py", line 802, in write
File …
> closing file descriptors for temp files

- music21/converter/subConverters.py
Currently attempt to run following code on Unix platform without .music21rc config
```python
>>> from music21 import environment
>>> from music21.note import Note
>>> Note('D#3').show()
```
causes following error message to appear:
```
SubConverterException: Cannot find a valid application path for format musicxml. Specify this in your Environment by calling environment.set(None, '/path/to/application')
```
which is misleading because running suggested call causes
```
AttributeError: 'NoneType' object has no attribute 'lower'
```
Provided fix makes initial error message correct, namely
```
SubConverterException: Cannot find a valid application path for format musicxml. Specify this in your Environment by calling environment.set('musicxmlPath', '/path/to/application')
```
> Show proper launchKey in SubConverter message

- music21/audioSearch/__init__.py
The interpolation returns the index of the peak, but for the edge cases when peak == 0 or peak == len(correlation) - 1, the function was returning the value instead of the index.
> Fix interpolation function in audioSearch

- music21/chord/__init__.py
added in method and doctest so that deprecation message for
normalFormString matches references something that exists
> created normalOrderString method

- music21/mei/base.py
Previously, the MEI importer could crash if @key.mode was not specified since it would pass in 'None' for the mode argument on KeySignature.asKey.
This commit fixes this by providing a default value so that if key.mode is None it assumes a 'major' mode.
> Fixed: key.mode was required in MEI import

- music21/converter/subConverters.py
I found a solution, to my problem in issue #230 it was a little difficult because all errors where being suppressed and by the time the execution got to the part where it checks for png output music21 had no idea something had gone wrong. I based this branch of master but the patch should also go into 3.*
> fixed issue for systems running headless, and better execution of musescore, better test for testXMLtoPNGtooLong

- music21/abcFormat/__init__.py
I can create some test cases if necessary. I am a bit concerned about the "O" (coda) decoration. But the existing tests all succeed.
> Fixes #269: Expand list of decorations to be ignored in abc parse.

- music21/voiceLeading.py
Fixes some issues in voiceLeading module:
- VoiceLeadingQuartet.parallelMotion() only accepted parallel motion by specific interval, rather than the normal convention of parallel motion being true when two consecutive intervals are the same generic interval. It now defaults to looking at the generic intervals, and takes an optional requiredInterval argument of either a generic or specific interval. This method also allowed octave displacement of one of the intervals, which is contrary to the normal definition of parallel motion (i.e., 3 -> 10 by similar motion is not typically considered parallel motion). This is now optional (for use mainly in the parallelFifth and similar methods).
- VoiceLeadingQuartet.isProperResolution() wasn't handling minor keys at all. Removed the requirement that …
> voiceLeading update

- music21/converter/subConverters.py
Fix the show method of the Braille subconverter so it works from the standard python interpreter as well as with the .ascii subformat.  Fixes issue #285.
> Fix the show method of the Braille converter

- music21/abcFormat/translate.py
- music21/chord/__init__.py
- music21/common/misc.py
- music21/common/pathTools.py
- music21/corpus/corpora.py
- music21/corpus/nottingham-dataset/reelsa-c.abc
- music21/harmony.py
We fixed a bug where pitch 'b' was converted to a '-' (ultimately raising an exception), when the intention was to convert a flat specified with a 'b'. This bug affected the creation of a chord that contained pitch 'b' either in its root or its bass.
Incidentally, the calls to replace() in music21/harmony.py lines 249 and 255 had not effect, so the bug wasn't always manifesting itself, depending on how the chords were instantiated.
Co-authored-by: Vincent Degroote <1230888+vinzentt@users.noreply.github.com>
Co-authored-by: Alexandre Papadopoulos <32906275+a-papadopoulos@users.noreply.github.com>
> Fixed wrong b to - conversion (shouldn't convert lowercase pitch b)

- music21/converter/subConverters.py
In the runThroughMusescore() function, the filename arguments are not quoted, although the musescore command is.  This was causing problems because my temporary directory has spaces in it, so the command generated looked like this:
"/Applications/MuseScore 2.app/Contents/MacOS/mscore" /Users/pkirlin/Box Sync/projects/ragtime/scratch/tmpu886ehll.xml -o /Users/pkirlin/Box Sync/projects/ragtime/scratch/tmpu886ehll.png -T 0  -r 200
When it should look like this:
"/Applications/MuseScore 2.app/Contents/MacOS/mscore" "/Users/pkirlin/Box Sync/projects/ragtime/scratch/tmpu886ehll.xml" -o "/Users/pkirlin/Box Sync/projects/ragtime/scratch/tmpu886ehll.png" -T 0  -r 200
> quoted filename arguments in musescore

- music21/articulations.py
- music21/musicxml/m21ToXml.py
Unlike other articulations, fingers should not only be applied to the first note of a chord. Fingerings must be applied in orderd, one each to one note respectively. This commit fixes this behavior.
> Fix xml serialization of fingering articulations

- music21/musicxml/testChordOffset.xml
- music21/musicxml/xmlToM21.py
This solves #350. I didn't have a lot of data to test this, but there's a few scores in wikifonia with `<harmony>` objects that have an `<offset>` component. Obviously I can't include them here, but things look fine.
(edit: escaped xml tags)
> Chord offset

- music21/environment.py
The latest version of MuseScore is v3. Running the configuration script will set "musicxmlPath
correctly, but leave "musescoreDirectPNGPath" set to a path for MuseScore 2. Maybe it's better to dynamically update the "musescoreDirectPNGPath" to the path of the version of MuseScore that the user installs.
> Update MuseScore from v2 to v3

- music21/stream/makeNotation.py
- music21/test/testStream.py
When a score has multiple voices (i.e. two notes played at the same time and not combined into a Chord) then the KeySignature is lost when the score is run through 
```
GEX = m21ToXml.GeneralObjectExporter(s)
wellFormedObject = GEX.fromGeneralObject(s)
```
The bug presented as a missing key signature when I was using `score.show()` and looking at the output in MuseScore, or when I was exporting to `.musicxml` file.
My fix works, but it feels a tad hacky. I don't quite understand how or why the keySignature gets destroyed in a multi-voice situation. Code review is be appreciated!
I included tests-- one that started passing, and one that started broken.
> Key signature for multi voice score being exported

- music21/mei/base.py
Hello,
I've added a small change to support accid.ges on `<accid>` This is based on the support for accid.get on `<note>`.
Please let me know if there is anything more needed to properly contribute to the project.
We're hoping to use this fix in a workshop at the Digital Humanities Summer School at the University of Victoria this June 2018, so it would be awesome to have this integrated by then!
> Added support for accid.ges on accid element

- music21/converter/subConverters.py
Hi,
showing a PNG didn't work for me on Windows.
Minimal example:
```python
import music21 as m21
n = m21.note.Note('c')
n.show('ipython.musicxml.png')
```
Before, that caused the error at the end of this message. In the subconverter, I just put the command in quotes before passing it to `os.system`. For me, it is now working fine. The same solution was used in this old commit 9ea4e43c5e5c6ed7aefdeb25b738d22e490158fc (see the `launch` method).
Possibly related issue: #348.
Best,
Frank
---
Error before:
```
---------------------------------------------------------------------------
SubConverterFileIOException               Traceback (most recent call last)
<ipython-input-28-b03574fb841c> in <module>()
5 # %load_ext music21.ipython21
6 n = m21.note.Note('c')
----> 7 …
```
> Quote Command for Windows for Showing PNGs

- music21/meter.py
Fix a reference so that the test case executes. (Or, to put it another way,
make this reference to TimeSignature() consistent with the rest of the test
cases here.)
Noted while running the test suite:
ERROR: testBasic (music21.meter.TestExternal)
File "/home/disciple/pkgsrc/wip_dhg/py-music21/work/music21-5.7.0/music21/meter.py", line 4444, in testBasic
ts = music21.meter.TimeSignature('%s/%s' % (meterStrNumerator,
NameError: name 'music21' is not defined
> meter.py: fix testBasic() test case

- music21/analysis/reduceChords.py
This code uses the Verticality class from tree/verticality.py, not the
Verticality class from voiceLeading.py; the object supplied here has to
have the toChord() method called first to prepare it for this usage.
Also, isConsonant() is a method, not an attribute.
Noted while running the test suite:
ERROR: testTrecentoMadrigal (music21.analysis.reduceChords.TestExternal)
File "/home/disciple/pkgsrc/wip_dhg/py-music21/work/music21-5.7.0/music21/analysis/reduceChords.py", line 729, in testTrecentoMadrigal
maximumNumberOfChords=3,
File "/home/disciple/pkgsrc/wip_dhg/py-music21/work/music21-5.7.0/music21/analysis/reduceCh …
> reduceChords.py: fix removeVerticalDissonances()

- music21/humdrum/spineParser.py
In testShowSousa(), parse() must be called first to generate a stream. Noted while running the test suite:
ERROR: testShowSousa (music21.humdrum.spineParser.TestExternal)
File "/home/disciple/pkgsrc/wip_dhg/py-music21/work/music21-5.7.0/music21/humdrum/spineParser.py", line 2897, in testShowSousa
hf1.stream.show()
AttributeError: 'NoneType' object has no attribute 'show'
> spineParser.py: fix testShowSousa()

- music21/analysis/windowed.py
The issue is(I assume due to changes of how python3 handels division), that windowCount in the 'noOverlap' case will be a float (even in the case where maxWindowCount / windowSize is divisible). This will then create an issue in line 149,       
`  data = [0] * windowCount`
`  File "/usr/local/lib/python3.7/site-packages/music21/analysis/windowed.py", line 146, in analyze
data = [0] * windowCount
TypeError: can't multiply sequence by non-int of type 'float'`
This Pr solves this by casting(I assume this way is most consistent with prior versions of python), also adds a warning, since i belive user should eb made aware
> solved issue with float/int conversion

- music21/beam.py
- music21/meter.py
- music21/test/testStream.py
Using music21 we've noticed various beaming bugs in the past. We've originally just kept the fixes internally but now as we move to python3 we take this opportunity to contribute the fixes back to the master repo.
As you can see, I've added "TestMakeBeams" class to demonstrate some proper beaming, as well as demonstrate some of the errors we encountered.
The unit tests that originally failed were: "test_1_e_a_after_16th_note" and "test_repeated_1_e_a". Not the best unit test names...I know...but we are working on drummers project here :)
The fix was simple and you can see our changes in the "getBeams" function.
For each failing unit test I've provided the wrong representation today and a proper representation as well that I was aiming for.
I'd be very happy to see these changes come into …
> Fix beaming issues

- requirements-minimum.txt
- setup.py
As part of the steps to make this package more developer friendly, I wanted to list the minimal requirements this package needs. By listing these in the `setup.py` we make sure that following a `pip install music21` the package can be used immediately by users.
**How did I determine the minimal dependencies?**
1. Checkout the `music21` project as-is from this repo to a local folder
2. Start a fresh `pipenv` (basically a type of a `virtualenv`) that has nothing installed in it.
3. Run `from music21 import *` and make sure we get no errors: For each `ModuleNotFoundError: No module named '<module-name>'` exception I got, I installed the package. Repeating this step until `from music21 import *` is working with no exceptions.
So the list of minimal dependencies we got via this process is: …
> Add minimal package requirements to setup.py

- music21/braille/basic.py
- music21/duration.py
- music21/test/testStream.py
Before this change music21 did not support dotted notes within tuplets when constructing notes based on their quarterLength. This change allow up to 1 dot when looking for the best represation candidate.
One unittest was added to demonstrate that the original issue was indeed fixed. I'd be happy to make any changes to get these changes into music21.
Thanks!
> Allow dotted tuplet notes when looking for duration candidates

- music21/alpha/analysis/__init__.py
- music21/alpha/analysis/aligner.py
- music21/alpha/analysis/fixer.py
- music21/alpha/analysis/hasher.py
- music21/alpha/analysis/ornamentRecognizer.py
Trill Fixer detects where a trill should be in music generated using OMR when compared against music generated from MIDI using the new Trill Recognizer. And inserts trill on appropriate omr note. 
Changes hasher to no longer split ties and only use note references in source and target stream, not root reference. This enables not in place fixing with Ornament Fixer.
> Trill Fixer for OMR 

- MANIFEST.in
Source distributions and subsequent downstream packaging results were including .mypy_cache contents.
> MANIFEST.in: specify the correct path to prune .mypy_cache

- music21/analysis/neoRiemannian.py
A few blank lines were missing in between documentation prose and the following code samples, which was causing the code samples to be incorrectly rendered as part of the prose.
An example of this can currently be seen here:
https://web.mit.edu/music21/doc/moduleReference/moduleAnalysisNeoRiemannian.html#music21.analysis.neoRiemannian.isNeoR
> Fix formatting in music21.analysis.neoRiemannian docs

- music21/_version.py
- music21/base.py
- music21/graph/plot.py
- music21/search/base.py
- music21/stream/__init__.py
- music21/stream/iterator.py
Filter adding properties and methods such as `.notes` or `.getElementsByClass()` now return a new StreamIterator
Fixes #536
Backwards incompatible change (won't be noticed by most users but might catch power users
> CHANGING:  .notes returns new StreamIterator

- music21/converter/subConverters.py
On Windows 10, inside Jupyter Notebook environment, `show` method with PNG output does not work because of the double quotes placed around the arguments of the called command.
```
import music21
s = music21.corpus.parse('bach/bwv65.2.xml')
s.show('ipython.musicxml.png')
```
throws `SubConverterFileIOException: png file of xml not found. Or file >999 pages?` error. Because PNG file was not generated in the scratch folder. This problem and its solution were mentioned in issue #348
The reason I found is that the command for PNG generation puts double quotes around arguments, and `os.system` does not like them. Below is the system call made by above `show` method, stored in `musescoreRun` variable..
```
os.system('"C:\\Program Files\\MuseScore 3\\bin\\MuseScore3.exe" …
```
> Use subprocess.run instead of os.system for PNG generation

- music21/harmony.py
Hey all, I noticed that error messages aren't helpful in cases where an invalid string is passed to ChordSymbol so I added a couple in this PR. It took me some debugging to figure out why ChordSymbol('Bb') was not working because the error I was getting was not informative -- so it took a while for me to realize that music21 expects - for flats in this case.
Do let me know your thoughts
> Add error messages for invalid chord roots and abbreviations

- music21/musicxml/testPrimitive.py
- music21/musicxml/xmlToM21.py
Fixes #490
Previously, XmlToM21 would reject any value other than an int for the `number` attribute of an `<ending>` element. 
Since the MusicXML spec supports comma-separated values, and since the setter for numbers in `RepeatBracket` already parses comma-separated values and raises a `SpannerException` if there is non-conforming input, the idea is here to make use of each of those features of `RepeatBracket`.
> Parse multiply numbered endings

- music21/musicxml/testPrimitive.py
- music21/musicxml/xmlToM21.py
Resolves #444
Summary: leading hidden rests were being found because makeRests() creates them in all cases, but mid-measure and end of measure hidden rests from `<forward>` elements were not created.
fillGaps handles the midmeasure case, and using refStreamOrTimeRange to compare with the entire measure stream handles the end case.
> Find mid-measure and end of measure hidden rests from <forward> elements

- documentation/source/about/faq.rst
The Humdrum links in the FAQ were outdated. The Ohio State link no longer leads to Humdrum info, and the .net yielded a spam site.
> Update Humdrum links in FAQ

- music21/stream/__init__.py
- music21/test/testStream.py
Fixes #575 
Before: time sig and key sig were only propagated to lower parts by `voicesToParts()` if the source measure for those elements had voices. Barlines also weren't propagated even in measures with voices due to a typo.
Now: time sig and key sig and barlines all propagate whether the source measure had voices or not.
Current behavior for clef is maintained: don't propagate, and let `bestClef()` run at the end.
> Propagate time sig, key sig, barline in voicesToParts()

- music21/stream/__init__.py
- music21/stream/makeNotation.py
- music21/test/testStream.py
Fixes #577. Easy patch, so I just forged on.
Before: calling `makeAccidentals()` on a Measure with substreams would have no effect. Such calls are made by `makeNotation()` and xml export.
Now: just let `makeAccidentals()` recurse over the input Stream.
Question: is there a valid use case for not recursing over substreams when making accidentals?  If so, this needs a couple quick lines of documentation in `makeAccidentals()`, possibly a keyword `recurse=`, and a decision about whether the default should be True or False in v.6 and whether it should move to True in v.7, etc.
I'm having trouble imagining the use case for NOT wanting accidentals made on substreams, so I didn't create a keyword arg. If a user doesn't want the new behavior, well, `makeAccidentals()` wasn't doing anything to …
> Let makeAccidentals() recurse

- music21/musicxml/m21ToXml.py
Fixes #580 
Before: `ScoreExporter` will eventually create a `Part` for a `Score` without one, but `setPartsAndRefStream()` is called first, causing problems when it clears offsets on substreams (which, until Parts are created, are Measures).
Now: don't clear/transfer offsets on Measures; do calculate `self.highestTime`, though.
NB: this is a case where `parseFlatScore()` indeed runs (code comment wonders if it ever does).
> Fixes #580: ScoreExporter no longer resets offsets on measures not contained in parts

- music21/analysis/discrete.py
- music21/features/base.py
- music21/features/jSymbolic.py
- music21/features/native.py
- music21/graph/primitives.py
- music21/midi/translate.py
- music21/stream/__init__.py
- music21/test/testStream.py
Fixes #266 fixes #514 
Summary: when `stripTies(retainContainers=True)` deletes notes, it only searches `Measure` containers. Notes in other containers or no containers will stick around and end up as duplicates.
Fix: use `Stream.remove(recurse=True)` rather than popping notes from `Measure` containers.
Update: fixes #568 
Summary: `stripTies()` depends on tied notes being consecutive in the flattened parent container, which when voices are involved, may not obtain, and will yield unexpected results.
Fix: make recursive calls to `stripTies()` for each voice, modeling on how this is currently done for part-like substreams.
Update: Fixes #491 by filtering non-`GeneralNote` objects from `findConsecutiveNotes()` output.
> Let stripTies() recurse when deleting and searching

- music21/midi/translate.py
- music21/musicxml/m21ToXml.py
Fixed #588 
**Before**: `MetaEvent.INSTRUMENT_NAME` and `MetaEvent.SEQUENCE_TRACK_NAME` were ignored when parsing midi files into streams.
**Now**:  Instrument instances are constructed.
> Constructed m21 instrument from MIDI instrument name or sequence track name

- music21/stream/__init__.py
- music21/stream/makeNotation.py
- music21/test/testStream.py
Fixes #534 Fixes #515 (duplicates)
**Before**:  `makeMeasures()` would choke on a duration-less element coinciding with the end offset of the final measure.
**Now**: `makeMeasures()` places a duration-less element coinciding with the end offset of the final measure <s>in that final measure</s> at the end of the stream.
> Allow element to lack duration when coinciding with last measure's end offset

- music21/stream/__init__.py
- music21/test/testStream.py
Fixes #502 fixes #430 (duplicates)
**Before**: `stripTies()` would accept at face value a tie type of stop from a `Chord` object, even though not all of its members might participate in a tie. This would leave downstream effects in `chordify()` where verticalities would go missing.
**Now**: `stripTies()` only treats a `Chord` as the end of a tie if every member has a tie type of stop. That is, unless `matchByPitch` is used.
--
(PS -- LMK if you think linking back to the issue tracker is overkill -- seems useful in the event there is either a discussion there or evidence of something happening in the wild, but would certainly defer on this style point!)
> Fixes #502: Strip ties from chords only when all members have a stop tie

- music21/musicxml/m21ToXml.py
Fixed #594
**Before:** On .xml export, schema validation issues occurred when `Instrument` instances with merely a `.midiProgram` and no `.instrumentName` never had a corresponding `<score-instrument>` created alongside the `<midi-instrument>`.
**Now:** we create a `<score-instrument>` element in this case so that the `<midi-instrument>` id matches something.
> Create score-instrument when all we have is .midiProgram

- music21/environment.py
- music21/musicxml/m21ToXml.py
- Now with support for multi-digit endings from m21 -> xml (before I only did xml -> m21)
- Tried .write('musicxml.png') for the first time and needed to download MuseScore, which now downloads as MuseScore 3.5.app, so updated the default paths.
> Support multi-digit endings in xml export; bump MuseScore version paths

- music21/audioSearch/__init__.py
- music21/graph/axis.py
- music21/humdrum/spineParser.py
- music21/midi/translate.py
- music21/musicxml/xmlToM21.py
- music21/omr/correctors.py
- music21/pitch.py
- music21/search/base.py
Fixed #608 
• `search.base.translateDurationToBytes()` checks for zero before taking `math.log2()`
• `search.base.translateNoteWithDurationToBytes()` calls the above function rather than performing the same calculation with duplicative code
•  similar changes in `omr.correctors.hashQuarterLength()` and `musicxml.xmlToM21.xmlToDuration()`
• `math.log(2, x)` changed to `math.log2(x)` where possible, since as of Python 3.3 `log2` is considered more reliable
> Check if zero before taking log; prefer math.log2()

- music21/environment.py
Thanks to David Garfinkle for the report and patch!
fixes #342
> Fixed string formatting issue in EnvironmentException when scratch directory doesn't exist

- music21/features/outputFormats.py
- music21/roman.py
- music21/test/testPerformance.py
Fixes #585
**Before:** `RomanNumeral` objects without keys would pass a `Scale` object to `_parseRNAloneAmidstAug6()`, which only contemplated `Key` objects for `useScale`, even though elsewhere `useScale` is a scale or key.
**Now:** check the appropriate attribute on scales vs. keys to get to `'major'`.
Fixes #609 
**Before:** augmented sixths must be built from minor scales, but this mode correction was never set in the context of secondary Roman numeral keys.
**Now:** set `RomanNumeral.secondaryRomanNumeralKey` to the parallel minor key when building augmented sixths.
Also! Was poking around in the test directory and ran findNonUTF8.py and testPerformance.py and found some small fixes.
> Augmented sixths

- music21/scale/intervalNetwork.py
Fixed #319 
**Before:** next pitches derived from a node in `IntervalNetwork.nextPitch()` would have their octave copied from the node in question, which comes out wrong if stepping to the next pitch crosses an octave boundary.
**Now:** increment or decrement octaves as necessary until upper neighbors are above `pitchOrigin` or lower neighbors are below it. Only one octave adjustment should be necessary in most cases, but I didn't see a reason to rule out compound intervals -- lmk if those aren't supported/necessary to worry about here -- that's what the `while` is there for.
> Corrected octaves on pitches derived in IntervalNetwork.nextPitch()

- music21/musicxml/m21ToXml.py
Fixed #624
`Coda` and `MetronomeMark` affected in the same way, although those are far less likely to matter than `Fine`. Still, I applied the same patch.
> Transferred element offset to derived TextExpression upon export to XML

- music21/harmony.py
- music21/musicxml/xmlToM21.py
Fixes #604 and fixes #384 
**Before:** `ChordSymbol('C6')` had a root of C stored as an override at an intermediate point, then erased, yielding eventually A as the root. Update: similarly, inversions parsed from XML were wiped. (See #384)
**Now:** We don't wipe overrides for root and bass. Turned out to be the same solve for 'sus4' chords where there was a patch telling us it was probably in the wrong place. So I removed the no longer needed, wrong-place patch after being sure to add 'sus4' as a test.
Update: fixes #615
> ChordSymbols: Don't wipe overrides for root and bass

- music21/midi/translate.py
- music21/stream/__init__.py
- music21/test/testStream.py
Fixes #629 
**Before:** `Stream.quantize(processDurations=True)` would allow durations of 0 on non-grace notes. By contrast, sequencers and notation programs such as Logic Pro and Finale enforce a minimum nonzero duration when quantizing MIDI:
> For example, a note with a short note value, such as a 32nd note, can only be displayed at its original length if Quantize is set to 32 or shorter. If Quantize is set to 8, the 32nd note is displayed as an eighth note (the shortest note value displayed at that Quantize setting). 
https://support.apple.com/guide/logicpro/quantize-lgcp8535c422/mac
**After:** Unless a note's duration `isGrace`, `Stream.quantize(processDurations=True)` uses the largest value of `quarterLengthDivisors` to derive and set a nonzero duration.
> Enforce nonzero duration on non-grace notes when quantized

- documentation/source/installing/installMac.rst
- documentation/source/installing/installWindows.rst
Fixed #526 Fixed #354 (duplicates)
Mac users were having trouble finding `installer.command` because `pip` doesn't install it, and the Mac install instructions don't mention any other way to find and run the configuration assistant.
Also fixed the lack of line break in the Windows installation instructions by treating it as a quoted code block.
> Help Mac users find and run the Configuration Assistant

- music21/midi/translate.py
Came up in the discussion in #629. Workaround for behavior of MuseScore in writing MIDI files:
https://musescore.org/en/node/310158
> Workaround for null-terminated instrument name

- music21/base.py
`fp` and `subformats` are keyword arguments on every writer, so it seems safer to me to pass them by keyword than by position.
> Pass fp and subformats to formatWriter.write() by keyword

- music21/common/misc.py
As described in #656, retrieving the version of macOS Big Sur does currently not work. This effectively prevents using _music21_ on macOS Big Sur as `import music21` fails.
This pull request introduces a future-proof fix that handles unexpected macOS versions that only contain a major version (e.g., `11`) or a major and minor version (e.g., `10.16`).
> Correctly Retrieve Version of macOS Big Sur

- documentation/source/developerReference/documenting.rst
Sphinx links linked to broken sites. Pointed to sphinx-doc.org and to a cheat sheet created by the matplotlib project that sphinx-doc.org links to itself. With luck that means these links will enjoy a healthy shelf life. Also fixed some things that read didn't quite.
> Update Sphinx documentation

- music21/abcFormat/__init__.py
- music21/corpus/virtual.py
- music21/editorial.py
- music21/metadata/__init__.py
- music21/metadata/bundles.py
- music21/metadata/caching.py
- music21/metadata/primitives.py
I wanted to add one tiny feature to ABC, but the tokenize method is way too complex as it is.  A start to cleanup methods by making current parsing positions be attributes on the ABCHandler class.
Next step will be to move ABCHandler to two classes:  ABCStringParser and ABCTokenParser.  But will merge in small PRs that make incremental improvements.
> Start of a cleanup for ABC parsing

- music21/environment.py
Patches the failures on Windows reported by @tanchihpin0517 in #660 . This is a pretty trivial approach. If `forcePlatform` doesn't/can't work any more, fix or deprecate?
> Skip Mac platform tests failing on Windows

- requirements.txt
Minimum version for `webcolors` was set to the latest release 1.11 in f178932728ed54462755bc837b2cef8e59b75c6c, but this was because a function was finally deprecated and its replacement `name_to_hex()` has been working since at least 1.5.
Loosening the minimum version to 1.5 would help folks install on conda-forge, where the latest version of `webcolors` available is 1.9.
Test suite passes when rolling `webcolors` back to 1.5.
> Loosen minimum webcolors version to 1.5

- music21/roman.py
Fixes #437
The subroutine `sharpen()` was not unsharpening roots from figures representing inversions when sharpening the root. This led to the need to pass in and return `workingFigure`, which led me to question whether this method serves any purpose being public, save for its useful documentation about `Minor67Default`, since this is extremely low-level work. So I moved the documentation to `Minor67Default` and made the method private for consistency with its neighbors, and provided a backwards compatible public stub.
> Make adjustMinorVIandVIIByQuality() private; unsharpen root in figure when sharpening root

- music21/midi/translate.py
- music21/stream/__init__.py
Regression in #641. Was causing leading rests at the beginning of a part to be broken up into smaller chunks.
Noticed while poking at #684.
> Don't assign durations to instruments during MIDI parsing

- music21/musicxml/testPrimitive.py
- music21/musicxml/xmlToM21.py
Before, on xml import, when brackets were undefined but show-number = None, this would result (beat 2):
Noticed this in the Grosse Fuge.
> Set bracket=False when bracket is undefined and show-number=None

- music21/midi/translate.py
Refs #684 
**Before**: `instrument.partName` was not set on instruments created from parsing MIDI. If the instruments could successfully be normalized to m21 instruments, `.partName` on the `Part` would come out okay because of the way the property drills down to the instrument types. If a default instrument was created from a string like "Marcato" that doesn't normalize, the information was lost (there was no specific instrument for the property to drill down to).
**Now**: We store the text from SEQUENCE_TRACK_NAME or INSTRUMENT_NAME meta messages on `instrument.partName` so it will flow upstream to `Part.partName` and thus to an xml export, whether the text successfully normalizes to a specific instrument or not.
> Set literal name parsed from SEQUENCE_TRACK_NAME or INSTRUMENT_NAME on instrument.partName or .instrumentName

- music21/stream/__init__.py
- music21/test/testStream.py
Refs #684  (Turned out to be easier than I thought!)
**Before:** elements outside of voices, such as Instruments, would vanish when running `.makeMeasures`.
> Retain instruments outside of voices when making measures

- music21/midi/__init__.py
Noticed while debugging that the `else` case was capturing more than NOTE_ON and NOTE_OFF. So I looked up what was being captured and wrote cases for them. Needs a test file; none of the .midi files in the repo have PITCH_BEND messages, for instance.
> Improve readability of parsing PITCH_BEND and POLYPHONIC_KEY_PRESSURE messages

- music21/base.py
- music21/chord/__init__.py
- music21/expressions.py
- music21/stream/__init__.py
- music21/stream/core.py
- music21/stream/makeNotation.py
Long long ago, music21Objects could have `.duration == None` -- for a long time, all music21 objects have always had a duration.Duration object as .duration, but we still had a lot of checks for it.  Removing them all.
> Remove tests for None duration

- .idea/dictionaries/music21.xml
- documentation/source/usersGuide/usersGuide_13_music21object2.ipynb
- music21/instrument.py
- music21/midi/__init__.py
- music21/midi/translate.py
- music21/scale/__init__.py
- music21/test/testStream.py
- music21/volume.py
Fixed #152 Fixed #569
**Before:** music21 produced multitrack MIDI files in format 1 (multi-track) without a conductor track. This isn't standard practice and could lead to the failure to propagate tempo, meter, and key to subsequent tracks when loaded into sequencers or notation programs.
**Now:** every produced MIDI file begins with a conductor track (Track 0) before the first music track (Track 1).
**Update:** On MIDI _import_, A `MetronomeMark` in the conductor track will now propagate to every m21 part, to fix a bug but more importantly so that `.seconds` will be correct on notes in subsequent parts.
I would appreciate some testers beating this up before merge. I'm not a MIDI expert.
> Conductor track

- music21/_version.py
- music21/base.py
- music21/midi/__init__.py
- music21/midi/translate.py
- music21/tempo.py
* Document a number of under-documented midi.translate routines
* Add typing in MIDI
* Upgrade version since conductor track is breaking old pickles (for testing only)
* tempo.MetronomeMark -- FINALLY allow a number alone.
* Fix pyCharm linter errors
> MIDI translate -- ensure conductor track is first

- music21/scale/__init__.py
Here is the new implementation of `DiatonicScale.getLeadingTone()` as discussed in #699.
Based on the last comment by @mscuthbert (each step appears exactly once in DiatonicScales), it should be safe to omit the `mod 12` in the condition.
Credit for faster check on 11 semitones (rather than `M7` Intervals) goes to @jacobtylerwalls.
> Alternative (faster) implementation of DiatonicScale.getLeadingTone()

- music21/stream/__init__.py
- music21/test/testStream.py
Noticed while reviewing #651 . Every other `.write()` returns something, but not `opus.write()`. What do you think?
> Write individual files from opus.write() and return path to last

- music21/chord/__init__.py
- music21/clef.py
- music21/common/pathTools.py
- music21/harmony.py
- music21/interval.py
- music21/roman.py
Fixes potential problems where retrieving a property causes an exception.
Cache a few more things.
Define what things like .forteClass are for empty Chords
remove test the common.getSourceFilePath() must end in music21 -- it does not for me! and probably others.
Document changes.
Technically backwards incompatible, but needed for a lot of Py3.8/3.9 compatibility.
> Allow inspection of properties for Chord/Interval/Clef/etc.

- music21/stream/__init__.py
- music21/test/testStream.py
When writing a test for the line I hadn't covered yet, sure enough there was a bug. Multiple periods were being created in a couple places.
Also short-circuited on lack of `.scores` so that we don't raise an ugly `MathDomainError`.
> Prevent multiple periods in the filepath from opus.write()

- music21/converter/subConverters.py
- music21/midi/translate.py
Refs #684
`.numberImplicit` was all it took.
> Hide metronome marks on subsequent staffs from MIDI

- documentation/source/developerReference/documenting.rst
- music21/harmony.py
- music21/roman.py
- music21/romanText/translate.py
Makes a small tiny changes mostly for empty roman numerals.
`.followsKeyChange` and `.scaleOffset` are deprecated and will be removed in v7
> Add proper documentation to RomanNumeral for the first time

- music21/analysis/reduction.py
- music21/base.py
- music21/beam.py
- music21/duration.py
- music21/editorial.py
- music21/pitch.py
- music21/prebase.py
- music21/roman.py
- music21/scale/intervalNetwork.py
- music21/stream/filters.py
- music21/style.py
- music21/tie.py
Do not require that the chord matches the impliedQuality IF the adjustment to a chordStep has been explicitly set.
Also fix up some confusion on when to call init() on a ProtoM21Object subclass (almost never)
> Fix RNs like V7b5

- music21/environment.py
Apparently this summer when I bumped the default MuseScore path to MuseScore 3.5.app, I caught the brief period when they weren't using just "MuseScore 3.app":
August 2020 (3.5.0)
(only 3.5.1 is accessible today?)
October 2020 (3.5.2)
> MuseScore package is once again just MuseScore 3

- music21/scale/__init__.py
```
>>> from music21 import *
>>> sc = scale.DiatonicScale('C')
>>> sc.show('scala')
File "/Users/jwalls/music21/music21/scale/__init__.py", line 2436, in show
self.abstract.show(fmt=fmt, app=app, direction=direction)
File "/Users/jwalls/music21/music21/scale/__init__.py", line 621, in show
returnedFilePath = self.write(format, direction=direction)
File "/Users/jwalls/music21/music21/scale/__init__.py", line 599, in write
fileFormat, ext = common.findFormat(fmt)
File "/Users/jwalls/music21/music21/common/formats.py", line 155, in findFormat
fileFormat = c.regularizeFormat(fmt)
File "/Users/jwalls/music21/music21/converter/__init__.py", line 946, in regularizeFormat
fmt = fmt.lower().strip()
AttributeError: …
```
> Fix crash in AbstractScale.show('scala')

- documentation/source/usersGuide/usersGuide_24_environment.ipynb
- documentation/source/usersGuide/usersGuide_54_extendingConverter.ipynb
- music21/environment.py
Came up while discussing #660:
First commit refactors `getTempFile()`. Second commit attempts to address #660 by writing to a user-specific dir only when needed (when catching `PermissionError`). Second commit has lower utility if #660 or #680 is merged, but `PermissionError`s could still theoretically arise, even if those PRs make it less likely to arise accidentally.
> Refactor getTempFile() and catch PermissionError when unable to write to scratch directory

- music21/harmony.py
- music21/musicxml/xmlToM21.py
The demo file in the corpus for chord symbols was exporting malformed xml, because on import, musicxml's `<kind>major-minor</kind>` was never mapped back to music21's `minor-major-seventh`, so it never matched the entry in `harmony.CHORD_ALIASES` and `minor-major` was written back out, which is not a valid musicxml chord kind.
> Check CHORD_ALIASES when importing xml chord symbols

- music21/abcFormat/translate.py
- music21/harmony.py
Fixes #720
Other figures were broken such as "dadd6" or "atristan" where the root being replaced matched case with a letter in the figure.
> Replace root only once while parsing figure

- music21/chord/__init__.py
Extends the check for chords containing more than one triad.
Previously hasRepeatedChordStep() was used to check steps 3 and 5, so that:
```
>>> chord.Chord('C E- E G').quality
'other'
>>> chord.Chord('C E G- G').quality
'other'
```
But that still returned 'major' for the following case:
```
>>> chord.Chord('C C# E G').quality
'major'
```
While it's true that there's a major triad in there (CEG), there's also a diminished one (C#EG); it would be more consistent if this cases returns 'other' too.
With this PR, that case now returns 'other'
```
>>> chord.Chord('C C# E G').quality
'other'
```
Note that this does not apply to b2:
```
>>> chord.Chord('C Db E G').quality
'major'
```
> Quality: adds hasRepeatedChordStep(1) check in addition to 3 and 5

- music21/musicxml/m21ToXml.py
Spec says `<degree-alter>` takes a decimal, so exporting `<degree-alter />` for "omit5" was causing validation errors.
> degree-alter 0 instead of empty

- music21/musicxml/m21ToXml.py
Missed case from #598 -- musicxml doesn't allow '0' for an ending number; music21 does.
Noticed in corpus example (mozart/k458, 1)
> Fix musicxml validation error on lack of ending number

- music21/instrument.py
- music21/midi/translate.py
- music21/stream/__init__.py
Fixes #684
(In the sense that we identified no further TODOs, but for my comment about improving quantization someday, which would be a massive project.)
**Before:** MIDI parsing, after #589, constructs Instrument instances from either `SEQUENCE_TRACK_NAME` messages or `PROGRAM_CHANGE` messages.
This can lead to duplicates if both messages are present at the same offset, which can lead to downstream problems with `partitionByInstrument()`:
https://stackoverflow.com/questions/64413988/reading-midi-file-using-music21-with-partitionbyinstrument-to-get-notes-and-ch
**Now:** instrument instances at the same offset in a substream are consolidated IF the `partName` and `instrumentName` attributes agree, i.e. are identical or `None`.
Consolidation means:
- setting the attributes to agree
- …
> Deduplicate instruments

- music21/roman.py
Fixes #725
It was stupidly simple:  the variable `pitches` has outlived its usefulness by the time `self._matchAccidentalsToQuality` has run. Should be checking `self.pitches`.
> Improve handling of omitted pitches in _updatePitches()

- music21/instrument.py
- music21/musicxml/xmlToM21.py
- music21/stream/__init__.py
- music21/stream/makeNotation.py
- music21/test/testStream.py
This is the patch file attached to #722 
Fixes a bug in partitionByInstrument, where instrument objects were left with non-zero durations.
Fixes findGaps not putting the stream back in order
Removed some places where coreElementsChanged() was being called inside subroutines where it should have been called before the routine.
Removed a few coreInserts at the cleanup stage of PartStaff creation -- too few to be worth the bugs.
> cleanup core methods that were leaking

- music21/chord/__init__.py
Also speed up containsTriad and containsSeventh
Make helpers for isMajorTriad, isMinorTriad, isDim..., isAug...
Takes away a tiny bit of the speedup, for greater code clarity.
Might slightly reduce code coverage because of reduced length of covered code.
> Remove bottlenecks on Chord.isTriad and Chord.isSeventh

- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlToM21.py
- music21/romanText/writeRoman.py
After #634 , we use a `StaffGroup` to track grand staff instruments we can merge back to `<part>` elements on xml export.
This was creating duplicate part names and group names on export:
dragged apart so you can see them:
Sketched a fix. Will add a test if this is acceptable.
> Avoid duplicative part name from StaffGroup object

- music21/__init__.py
- music21/base.py
- music21/lily/translate.py
Likely fixes #750, although I wasn't able to reproduce it on a Mac, which probably fully imports `importlib.util` at some other point. @nblumoe can you let us know if this resolves the issue? Thanks for the report.
> from importlib.util import find_spec

- music21/converter/__init__.py
Fixes #567 by adding a tip to `makeNotation()`. Reproduced using another MIDI file and confirmed this avoids the exception.
> Added tip for calling makeNotation after parsing MIDI

- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlObjects.py
Fixes #759 
`Harmonic` wasn't being exported unless it was `StringHarmonic`, but musicxml has a way to represent this.
Also found a docstring modeling creating `Harmonic` and hacking the attributes in--fixed.
Used `<other-technical>` to represent whatever we can't translate, just like `<other-articulation>` elsewhere. EDIT: on first push I was exporting `<other-articulation`, but I found that musicxml has `<other-technical>`, so updated.
Spot checked the other exceptions that are raised and don't see much value at this time to try to pass m21 objects in and print sites.
> Create <other-technical> instead of raising an exception from untranslatable technical marks

- music21/instrument.py
- music21/musicxml/xmlToM21.py
Fixes #397 , which described reverting to generic `Instrument` on encountering midi programs that didn't match the default midi programs on the existing classes, and provide a faster lookup in `instrumentFromMidiProgram()`.
The remaining TODOs would be to also set self.instrumentSound from a similar lookup.
`class Sampler` could be replaced with references to `KeyboardInstrument`, but that seems to decenter electronics and contemporary musical practices to me. An orchestra hit or a siren can't be played on a generic KeyboardInstrument--only a sampler. I'm having flashbacks to the few minutes before my 12pm section of Keyboard Skills where my students would unplug their headphones and jam on sirens and whistles and screams before class. It was pretty tight.
> Capture more instruments from MIDI programs

- music21/note.py
Previously, `GeneralNote(lyric=None)` would set a lyric with the literal `None` as a string. Fixes #768.
> Fix the instantiation of GeneralNote with lyrics

- music21/humdrum/spineParser.py
Humdrum notation can (apparently!) contain manual-positioning information for rests, which unfortunately the current code detects as a note.
Details:
In humdrum, a normal eighth note rest might look like `8r`, but the position of this rest can be changed by adding the symbol for a pitch after the `r`; e.g., `8rGG` would mean an eighth note rest but positioned at the vertical space on the staff where the note `GG` is.  I cannot find any definite information on this in the humdrum documentation, unfortunately, but it appears in at least one file on the KernScores website: https://kern.humdrum.org/cgi-bin/ksdata?l=users/craig/ragtime/joplin&file=entertainer.krn&f=kern  (see measure 4).  
For the moment, this can be fixed by detecting rests first, then notes, in the `hdStringToNote` function, …
> WIP: Humdrum parser bug when encountering manually-positioned rests

- music21/midi/__init__.py
- music21/midi/translate.py
Python3 specific bug:
track.getChannels throws an exception if one of the channels is None.
This is because the channels are being sorted, and python3 no longer allows comparison between int and None.
I don't have enough context, so feel free to close this PR and put up the correct fix instead.
Steps to REPRO:
1. Download midi file: 
`wget https://github.com/bearpelican/musicautobot/raw/master/data/midi/examples/A%20Thousand%20Miles%20-%20Vanessa%20Carlton%20-%20Verse-And-Pre-Chorus.mid`
2. Run Following
```python
import music21
file = 'A Thousand Miles - Vanessa Carlton - Verse-And-Pre-Chorus.mid'
mf = music21.midi.MidiFile()
mf.open(file)
mf.read()
mf.close()
[t.getChannels() for t in mf.tracks]
```
> Filtering out null channel values

- music21/base.py
- music21/chord/__init__.py
- music21/clef.py
- music21/meter.py
- music21/stream/__init__.py
- music21/stream/makeNotation.py
Adds method to clef and several functions in makeNotation to set stems consistently for beam groups.
(not 100% needed for most Python applications, but very helpful for fixing problems with beam stem directions after manipulating meter or transposition.  Crucial for music21j which will be getting this soon.)
> Set Stem directions consistent with Beaming

- documentation/source/developerReference/documenting.rst
> Update Sphinx example for block-quoting code

- music21/_version.py
- music21/base.py
- music21/musicxml/lilypondTestSuite/61l-Lyrics-Elisions-Syllables.xml
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/note.py
- music21/search/lyrics.py
Changes #673 and #666 to deal with multiple syllables in a single verse in a different way:
Lyric objects gain a .components[] list which is a list of subservient note.Lyric() objects representing multiple lyrics in a single verse (like "co_e" in "Il bianco e dolce cigno" or "th'an" in Hark the Herald Angels sing, "With th'angelic host proclaim")  -- in these cases a `.isComposite` boolean is true, and the syllabic is set to "composite" -- roundtrips to musicxml.
I appreciate @DIDONEproject work on putting a list in the .text and .syllabic attributes, but this ended up other code in real-world scenarios, so a new direction needed to be taken.  DIDONE and others who rely on the direction used since November 2020 will need to refactor.  Though if you only want the .text attribute after …
> Composite Lyric objects

- .coveragerc
- music21/chord/__init__.py
- music21/harmony.py
- music21/musicxml/xmlToM21.py
- Tests authored by @a-papadopoulos in #383
- Passing tests enabled, failing tests disabled
- Fix: set bass pitch when there is no chord; set default octave on bass pitches
- Fix: add bass note to chord's pitches when not in harmony
- Standardize `augmented-major seventh` to `augmented-major-seventh` like every other type
- Fix: treat "add" alterations on the seventh degree against a minor-seventh baseline, per musicXML spec
- Fix: parse inversions from musicXML when only `<inversion>` is present and `<bass>` is absent
- Fix: add chord step modifications before performing bass octave corrections
TODO: ~~one fix per commit to get the other tests to pass~~ What's left is just the "add", "omit", "subtract" business which is sticky and probably needs its own PR. I left those tests commented …
> Chord symbol fixes

- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlObjects.py
- music21/musicxml/xmlToM21.py
There were two existing efforts to do this--`measureParsingError()` which wasn't tested/functioning, and a try block on `xmlToSimpleNote()`--but it was simple enough to just abstract this to the exception classes.
> Add part and measure context to MusicXML exceptions

- .gitignore
- music21/abcFormat/__init__.py
- music21/abcFormat/testFiles.py
- music21/abcFormat/translate.py
Extension for the recognition of chords in ABCFormat according to http://abcnotation.com/wiki/abc:standard:v2.1#chords_and_unisons.
* For chords an outer length modifier is supported
Example:
[ceg]2 == [c2e2g2]
[c3e3g3]2 == [ceg]6 == [c6e6g6]
* The length of the chord is determined by its first note
Example:
[c2e4g8] == [c2e2g2]
* Empty chords are discarded
* Additional unittests for variations of abc Chords
* Fix: Missing chord symbols  for chords
* Additional unittests for chord symbols on note & chords
> Extended duration symbols in ABC chords (marian-schultz)

- documentation/source/usersGuide/usersGuide_20_examples2.ipynb
"figure out what approximately what note" > "figure out approximately what note"
> minor typo in usersGuide_20_examples2.ipynb

- music21/environment.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlToM21.py
- music21/stream/iterator.py
Fixes #808 
LMK if you prefer that I not use `.keySignature` as a lookup, but it seemed more convenient than recursing and checking if not None, etc.
> Import and export multi-key piano staves

- music21/midi/__init__.py
- music21/midi/translate.py
Fixes #809
The test that had to be adjusted demonstrates the improvement.
```
s = converter.parse('/Users/jwalls/music21/music21/midi/testPrimitive/test09.mid', forceSource=True)
made = s.parts[0].makeMeasures()
made.measure(54).show()
```
**Before**
**After**
**Update:** fixed an existing bug that would have increased in frequency -- when setting duration on MIDI chords, only the first chord member's note off is used. Now we use the last, which I would expect to be more likely to be correct.
> Make chord/voice boundary agree with quantization units

- documentation/source/usersGuide/usersGuide_31_clefs.ipynb
- documentation/source/usersGuide/usersGuide_43_searching1.ipynb
- music21/features/base.py
- music21/stream/__init__.py
- music21/test/testStream.py
- remove retainContainers
- default matchByPitch = True
I cribbed the doctest example for `matchByPitch=True` from your https://github.com/cuthbertLab/music21/pull/586#issuecomment-679428578
> V7 stripTies signature

- music21/musicxml/xmlToM21.py
- music21/stream/__init__.py
* Discard the original PartStaff, and create all new ones from template.  Then assign elements to staff if it is not excluded, but the second time an element is encountered, make a copy of it -- so except for measures, etc., we make n-1 copies of duplicate elements still.
* Add tests that duplicate elements are not appearing in staff.
* template uses coreInsert methods
* fix original template code to ensure that endElements remain endElements.
* add recurse() to addGroupForElements, but do not yet turn on in parsing.
> Refactor separateOutPartStaves

- music21/musicxml/partStaffExporter.py
- music21/musicxml/testPrimitive.py
- music21/musicxml/xmlToM21.py
Spotted this while we were working on templates and multi-keys.
Polymetric grand staffs were imported before templates, but then templates sort of broke it (just like keys) by letting the template copy the top meter into the bottom staff, leaving the bottom staff with two meters.
Then, export wasn't ever supported, but now it is.
> Import and export polymetric grand staffs

- music21/analysis/windowed.py
- music21/braille/test.py
- music21/graph/plot.py
- music21/graph/primitives.py
- music21/stream/__init__.py
- music21/stream/makeNotation.py
- music21/test/testStream.py
`makeMeasures` no longer automatically flattens streams with part-like substreams. Forces the user to `.flat` first if they're OK with that.
It will continue to <s>flatten</s> account for substreams inside measures, such as voices.
> makeMeasures no longer flattens part-like substreams

- music21/braille/segment.py
- music21/braille/test.py
- music21/braille/translate.py
Two fixes:
- parse maxLineLength keyword
- fix a constraint on trailing whitespace that was demanding impossible solutions in short line length scenarios, better to leave some whitespace than to give up (just so happens that your original test, with the dotted quarter, hit precisely at the right location on the line!)
> Fix braille line length rendering

- documentation/docbuild/writers.py
- music21/braille/segment.py
- music21/common/enums.py
- music21/musicxml/m21ToXml.py
- music21/romanText/tsvConverter.py
- music21/spanner.py
- music21/stream/__init__.py
- music21/stream/core.py
- music21/stream/iterator.py
* measures() is more open to what spanners can appear in it (even if just one note of a slur is present, for instance)
* add enum GatherSpanners to determine what types of spanners can appear.
* constrain gatherSpanners in measures() to only those present in the parent stream.
* speedup coreGatherMissingSpanners to only call elementsChanged if any spanners have been inserted.
* filter out obnoxious and wrong making directory warns in building docs
* explain why some try: in braille.segment are there.
* findGaps -- correct cache and check storeAtEnd
> Refine missing spanners in measures()

- music21/common/objects.py
- music21/stream/__init__.py
- music21/test/testStream.py
Spanners would disappear if a terminus was stripped by `stripTies`:
```
sch = corpus.parse('schoenberg/opus19', 6)
sch.stripTies().measure(8).show()
```
Before:
After:
> Replace spanned elements when stripping ties

- music21/musicxml/m21ToXml.py
I have fixed an incompatibility between the fontStyle property of music21 and the corresponding font-style property in mxml.
Unlike music21, mxml does not know  font-styles 'bold' and 'bolditalic'. 
When exporting, the font-style values are changed to compatible values and properties in the mxml output as follows
a.) 
For fontStyle='bold' in music21, font-weight="bold" is set in mxml.  (The font-style property is removed in mxml)
b.)
For fontStyle='bolditalic' in music21 font-weight='bold' and font-style='italic' is set in mxml.
I added 2 Testcases for this issue, and the bug in my personal usecase is solved too ;)
> fix the mxml export for unspecified font-style values 'bold' and 'bolditalic'

- music21/midi/translate.py
- music21/stream/__init__.py
- music21/test/testStream.py
Now that we don't have to dance with `retainContainers` to get a return value, we can make this banana peel go away (in this example, the call was already commented out but you get the idea):
https://github.com/cuthbertLab/music21/blob/c79932c43beb528dba428641d0e133a836770f5c/music21/features/base.py#L369-L375
> V7 stripTies(inPlace=True) returns None

- music21/base.py
- music21/beam.py
- music21/chord/__init__.py
- music21/common/__init__.py
- music21/common/enums.py
- music21/common/objects.py
- music21/common/types.py
- music21/corpus/chorales.py
- music21/duration.py
- music21/meter/base.py
- music21/meter/core.py
- music21/musicxml/m21ToXml.py
- music21/spanner.py
- music21/stream/__init__.py
- music21/stream/base.py
- music21/tempo.py
Add types in Duration
Deprecate common.Iterator (since Py2.6 was required)
Create common.types
Fix docs in corpus.chorales
Speed up Duration._updateQuarterLength
TimeSignature's default of 4/4 is explicit.
Lots of cleanups in meter/core
> Cleanup in v7

- music21/stream/base.py
All of the calls to `makeAccidentals` whether they call the overridden method or not send `inPlace` explicitly, so I think we're safe to change this without unforeseen consequences in core.
> v7 Part.makeAccidentals defaults inPlace=False

- music21/stream/makeNotation.py
- music21/stream/tests.py
Fixes #854 (on the assumption it would be too expensive to add guardrails to check all sites when inserting)
Before, a durationless element coinciding with the end of the stream would be added (on purpose) to the end elements, then (accidentally) also to the last measure.
> Prevent durationless element being inserted in last measure AND in end elements

- music21/graph/axis.py
- music21/prebase.py
- music21/romanText/clercqTemperley.py
- music21/stream/tests.py
Fixes code failing on the new Pylint check for unnecessary comprehensions when generators will do.
> Pylint -- remove unnecessary comprehensions

- music21/chord/__init__.py
As discussed in #869, this provides the ability to simplify enharmonics based on a supllied key, without having to call `pitch.simplifyMultipleEnharmonics` for the pitch objects.
I also believe that a simpler criterion could be added as an option to the `pitch.simplifyMultipleEnharmonics`, for the key context case. Namely, for every pitch choosing between its enharmonics if they belongs to the key pitches (in a greedy manner). 
If you find this useful, I could add it to this PR or create a new one.
> Added keyContext option in chord.simplifyEnharmonics

- music21/stream/base.py
Previously, Opus objects would always fail `isWellFormedNotation()`.
Update: now, we fail streams that have "loose" notes and rests and aren't a Measure or Voice.
My hunch is that if we sew up the gaps in `isWellFormedNotation` then we can more quickly answer user questions by just directing them to this method.
> Add cases to isWellFormedNotation

- music21/musicxml/partStaffExporter.py
Fixes a failure to show flattened piano scores. Could be worth a backport to v.6?
> Fix crash in export of flattened piano music

- music21/key.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
Fixes #867 
Any interest in also changing the default arg from `sharps=None` to `sharps: int = 0`?
> v7 KeySignature sharps defaults 0 instead of None

- music21/chord/__init__.py
for most chords, will be a major speedup, from about 25microseconds to 7!  Only runs the slower routines if there are not stacked thirds.
> Speed up _findRoot

- documentation/source/usersGuide/usersGuide_58_sitesContext.ipynb
- music21/musicxml/xmlToM21.py
- music21/stream/base.py
- music21/stream/makeNotation.py
<s>Figured it would be a small win to at least print .id rather than the memory location, but was this considered and rejected before?</s> <s>The MusicXML parser sets random numbers for voice IDs--is there a desire to hide this from users?</s>
EDIT: I see this is done after all -- just a matter of sprucing up some examples to model that this works!
> Provide more examples of setting .id on Voice objects

- music21/common/stringTools.py
cProfile shows me this will speed up musicxml parsing by about 8%, since compiling a regex every time a note is parsed is expensive.
master
```
>>> from timeit import timeit
>>> timeit('music21.common.hyphenToCamelCase("relative-x")', setup='import music21')
4.062028805999999
```
PR
```
>>> from timeit import timeit
>>> timeit('music21.common.hyphenToCamelCase("relative-x")', setup='import music21')
1.016820898000006
```
The only difference in behavior is this, but I see this as acceptable (we don't have XML attributes named with numbers), and I documented it:
master
```
>>> music21.common.hyphenToCamelCase('music-21')
'music-21'
```
PR
```
>>> music21.common.hyphenToCamelCase('music-21')
'music21'
```
I could add a check for this to get the old behavior, but I don't think we need the old …
> Faster implementation of hyphenToCamelCase

- music21/spanner.py
Dramatic speed improvement for musicxml export.
<s>95%</s> 76% of the time in musicxml export after `makeNotation()` for this corpus example --i.e. inside `parseWellFormedObject()`--is spent in `getSpannedElementIds()`:
EDIT: updated to use `ScoreExporter` to ensure I wasn't counting calls during makeNotation:
master
```
>>> s = corpus.parse('cpebach')
>>> sx = musicxml.m21ToXml.ScoreExporter(s)
>>> cProfile.run('sx.parse()', sort='cumtime')
3441542 function calls (3429186 primitive calls) in 2.838 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000    2.839    2.839 {built-in method builtins.exec}
1    0.000    0.000    2.839    2.839 <string>:1(<module>)
1    0.000    0.000    2.839    2.839 m21ToXml.py:1361(parse) …
```
> getSpannedElementIds() checks _elements

- music21/stream/base.py
Slightly slower for 'highestTime' but faster for everything else. musicXML parses 20% faster.
master
```
>>> timeit('s.elementOffset(n)',
setup='from music21 import note, stream;n = note.Note();s = stream.Stream([n])')
3.110492326
```
PR
```
>>> timeit('s.elementOffset(n)',
setup='from music21 import note, stream;n = note.Note();s = stream.Stream([n])')
0.410327549999991
```
> Speed up elementOffset()

- music21/musicxml/xmlToM21.py
Creating a GeneralNote without a `duration` argument creates a Duration of 1.0 that is later overwritten:
https://github.com/cuthbertLab/music21/blob/7498a6ee3ec2592a097ac243d6042da3b85e8b3d/music21/musicxml/xmlToM21.py#L3260-L3262
Timing script:
```
from timeit import timeit
timeit('mp.xmlToSimpleNote(mxNote)',
setup = '''
from music21.musicxml.xmlToM21 import MeasureParser
from xml.etree.ElementTree import fromstring as El
mp = MeasureParser()
mp.divisions = 10080
mxNote = El('<note pizzicato="yes"><pitch><step>D</step><alter>-1</alter>'
+ '<octave>6</octave></pitch><duration>7560</duration><type>eighth</type><dot/></note>')''',
number=100000)
```
PR: 8.50 vs master: 10.23
> Avoid creating and overwriting default Duration in musicxml parser

- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
Import and export versions of `setPrintStyle()` call `setColor()`, so additional calls to `setColor()` are redundant.
https://github.com/cuthbertLab/music21/blob/1d917269a9cc64db4783cb67ee972a55b4a7fb40/music21/musicxml/xmlToM21.py#L460-L469
https://github.com/cuthbertLab/music21/blob/ef4bdd6ae787ffb189486a126e6f1a2ee0b556c7/music21/musicxml/m21ToXml.py#L824-L833
> Remove redundant calls to setColor() and setPosition()

- music21/stream/base.py
Restore two calls removed in #803
- flattenUnnecessaryVoices calls remove(), which calls coreElementsChanged, but remove() might need correct offsets when doing its work
- And activateVariants() just looks like a review comment was missed.
> Restore two coreElementsChanged() calls

- music21/base.py
- music21/braille/segment.py
- music21/converter/subConverters.py
- music21/figuredBass/checker.py
- music21/instrument.py
- music21/midi/translate.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlToM21.py
- music21/note.py
- music21/spanner.py
- music21/stream/base.py
- music21/stream/iterator.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
- music21/style.py
- music21/tree/fromStream.py
- music21/variant.py
- Fix doc for humdrum `parseData()`
- Remove check for not hasattr(st, 'lineWidths')
- Model calling list() instead of  .elements in doctest
- Fixes #831 -- use `getFirst()` to index into slurs
- Documentation cleanup in partStaffExporter (Sphinx problem with python reserved word)
- Bugfix in `previous()` -- put className in a tuple before passing as classList
- Speed up `Note.__eq__()`
- Prefer tuples to lists in `setStyleAttributes` (hottest function in parser)
- Slight speed up to `Iterator.__next__()`
Avoid doing self.index - 1
- Optimize `addSpannedElements()`
- Speed up `_setAbsoluteY()` for values 'above' and 'below'
`numToIntOrFloat()` was being called.
- More uses of `.first()`
> Miscellany

- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/note.py
- Avoid splitting complex full measure rests on export (e.g. 4.5QL rest in 9/8 was split into 4.0 QL and 0.5QL)
- Set correct attribute `.fullMeasure` on import
> Full measure rest fixes

- music21/spanner.py
Sorry for the specific form of torture of getting multiple PRs a day, but it occurred to me (and didn't take long) to check the git blame for the spanner change we just merged in #901.
It was in b9929ef where there were changes system-wide to identity/contains, and I spotted a few other changes from that commit that should be reverted relating to spanner storage.
Update: added another speed improvement -- instead of getting the entire list of spannedElementIds and then checking if `in`, we can just check if the element is in the spanner, which uses the now-optimized `__contains__`, so that we can short-circuit when we find the element.
> Further spanner storage optimizations

- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
The patch in #863 to fix showing flat scores was too restrictive. Noticed today when trying to run `s.measure(1).show()`. 
@mscuthbert contributed logic for this in dcb32fc946, so my proposal is to just run it up front when filtering the joinable groups.
> Search derivations and id when finding joinableGroups

- music21/search/segment.py
python-Levenshtein (the name it goes by, rather than "pyLevenshtein") is now
available on pypi.org (https://pypi.org/project/python-Levenshtein/) and can
be installed via pip. Update the reference to this newer version (which has
fixed bugs with potential security issues that were present in the older
version). While here, also mention the forceDifflib parameter.
> Update a comment that references python-Levenshtein

- music21/_version.py
- music21/base.py
- music21/midi/translate.py
Missed case from #856 . Need to insert conductor events (time signatures in particular) before making measures, else the whole thing is for naught.
> MIDI -- insert conductor events into parts before making measures

- documentation/docbuild/documenters.py
- music21/serial.py
h/t @MarkGotham for noticing a stray item in `_DOC_ORDER` -- harmless by itself, but led me to discover that the entire order was being ignored.
Now, in the correct order!
PS -- `historicalDict` had to be removed from the order, b/c dicts aren't hashable (deep in the ModuleDocumenter), but it wasn't displaying anyway. There's another doctest that prints the keys, so it's visible in one way/shape/form.
> Fix documentation order in serial module

- music21/repeat.py
- music21/spanner.py
- music21/stream/base.py
- music21/stream/iterator.py
One last PR for spanners.
After the last few PRs there remains only one use of `getSpannedElementIds()`, which inefficiently builds the entire list before providing it to the caller to search, in `SpannerBundle.replaceSpannedElement()`, which alternatively takes an element, and which could be tested for spanner membership with the faster `Spanner.__contains__()` pattern we just optimized in 839c7e5.
- commit 1: sends elements, not ids, to `SpannerBundle.replaceSpannedElement()`, since we just optimized that, and raises an exception if you try to do it the slow way by passing an id.
- <s>commit 2: instead of raising an exception, provide backwards compatibility by checking if the input is `int`, so as to treat as an id and pass to new function `replaceSpannedElementSlow` with a deprecation …
> v7 SpannerBundle.replaceSpannedElement() only takes elements, not ids

- music21/analysis/neoRiemannian.py
> Instantiating chords with PC numbers could lead to an exception being raised, and triads safety checks could be misleaded

- music21/chord/__init__.py
- music21/pitch.py
Fixes #929
Also replace some bare asserts in the Chord module tests.
> Preserve value of spellingIsInferred in simplifyMultipleEnharmonics()

- documentation/source/about/faq.rst
- music21/musicxml/testPrimitive.py
- music21/musicxml/xmlToM21.py
Set position on `<direction>` elements on import, which wasn't handled.
- Set position on dynamics, spanners, and metronome marks
-- Fixes an issue with vocal dynamics not appearing above the staff, e.g. in the Beach corpus example. (placement='above' was not sufficient; also needed the y-values)
- Also set relative positions on coda/segno elements (only default positions were handled)
- Add tests for position import for all 5 direction types (TextExpressions were already working, but the other 4 had changes; just test all 5)
The file parsing shouldn't add much time to the test suite; the Beach file is parsed elsewhere, so the cached version loads here (in fact, this was how I found the bug with barlines in cached streams -- by trying to use `if el.hasStyleInformation` in the list …
> Set position on dynamics, wedges, and tempos on import

- music21/stream/base.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
All but a handful of calls in the test suite set the `inPlace` keyword already, so this was an easy change.
(side note -- the "obvious" problems... have to do with placing rests inside measures, in the last example?)
Update: handled in #922, so removed the TODO line here to avoid a forseeable merge conflict.
> v7 makeRests defaults inPlace=False

- music21/musicxml/m21ToXml.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
Noticed `makeTies` had a comment about leaving unnecessary voices behind, and figured that was easy to clean up with a call to `flattenUnnecessaryVoices()`.
Then promoted the doctest where that was demo'd (along with some version changed annotations) above the OMIT_FROM_DOCS line.
> Flatten unnecessary voices in makeTies

- music21/converter/subConverters.py
- music21/environment.py
- music21/features/base.py
- music21/metadata/bundles.py
- music21/romanText/tsvConverter.py
- music21/stream/base.py
- music21/stream/tests.py
Noticed yesterday that a number of temp files are not cleaned up by the test suite. (I authored about half of these tests.) Not a showstopper, but going to the minimal effort to clean them up revealed a couple of bugs/functional changes to fix/make:
Functional changes:
- `Opus.write(fp=None)` now deletes the temp file that it creates and doesn't use
- `DataSet.write()` now returns `fp` (`OutputFormat.write()` returns `fp` to `DataSet.write()`, which returns nothing)
Documentation:
- replace use of `mkstemp()` in a metadata doctest
> Delete unnecessary temp files in `Opus.write()` and test suite; return `fp` from `DataSet.write()`

- documentation/source/usersGuide/usersGuide_12_music21object.ipynb
- music21/stream/base.py
Fixes #902 
Depends on the Instrument being at the level containing the Measure (such as Part), which is the standard.
Continues to use `mergeElements` like the rest of the routine -- which will create shallow references, so the same `Instrument` will be in both parts in the resulting score. But it appears that is how the rest of the routine works today.
> voicesToParts() now preserves Instruments

- music21/common/enums.py
- music21/roman.py
Front alterations should be "bII" not "-II" for romanNumeral.  Do not use "#Ger" for German, etc.
> Fix RomanNumeral.romanNumeral

- music21/duration.py
- music21/stream/base.py
- music21/stream/tests.py
Fixes #957 
(few days, few minutes, what is a Duration anyway?)
Thanks again to @gregchapman-dev for tracking down the interaction with `coreElementsChanged()` so that we could get a reproducer.
> Add safety to `Stream._getDuration()`

- music21/harmony.py
- music21/musicxml/xmlToM21.py
A sequence of two such measures previously raised `ZeroDivisionError`.
**Example source:**
```
<measure number="4" width="289.46">
<harmony print-frame="no">
<root>
<root-step>G</root-step>
</root>
<kind text="m">minor</kind>
</harmony>
<harmony print-frame="no">
<root>
<root-step>E</root-step>
<root-alter>-1</root-alter>
</root>
<kind>major</kind>
<offset>24</offset>
</harmony>
<forward>
<duration>48</duration>
</forward>
</measure>
<measure number="5" width="357.54">
<harmony print-frame="no">
<root>
<root-step>D</root-step>
</root>
<kind>major</kind>
</harmony>
<forward>
<duration>48</duration>
</forward>
</measure>
```
Because m.4 was treated as "short", in the next measure we executed the last-measure-was-short branch and then crashed on a `ZeroDivisionError`:
```
Traceback (most …
```
> Import musicxml measures containing only ChordSymbols

- music21/_version.py
- music21/base.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlToM21.py
- music21/stream/base.py
- music21/stream/tests.py
**Before**
Streams with piano (joinable groups) could only be exported from `ScoreExporter` once. Fine for the typical usage of `Stream.write('musicxml')` since we make a deepcopy before reaching `ScoreExporter`. So the failure to export a second time only affected advanced users using `ScoreExporter` directly.
This limitation in the original feature was really a shortcut to get `<part-group type="stop" />` written. What I didn't realize until the TestExternal failure I saw in #938 is that this workflow was leaving side effects on the input stream -- which is not great -- and prevents exporting even after creating a new `ScoreExporter` object.
**Now**
Implement the feature in the right place! We would have had to revisit this eventually when adding a `makeNotation=False` for MusicXML …
> Avoid leaving malformed StaffGroups in cases where ScoreExporter is used directly and add safety to `Stream.replace()`

- music21/harmony.py
There was a small bug with duplicate bass pitches on dominant seventh chords that was just an alias/name bug.
(At first, I thought #882 would take care of it, but it's unrelated.)
> Fix duplicate bass note in dominant seventh ChordSymbol

- music21/_version.py
- music21/base.py
- music21/converter/__init__.py
- music21/midi/translate.py
- music21/stream/base.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
Noticed that we can solve 2 TODOs at once: 
- `makeRests()` makes rests inside Measures now
- in order to do that, we need to split rests at measure boundaries, which is what `makeTies()` does, but we don't want to touch the notes, therefore it was convenient to just handle the TODO declared there to create a class filter list.
- Update: now this also fixes some issues with MIDI notation making:
-- measures are now repositioned in the stream if they were enlarged due to gap-filling
-- ties are now made on notes and chords across barlines (vs. just rests, by virtue of this PR's new feature in makeRests())
> Add classFilterList to makeTies and allow makeRests to put rests in Measures

- music21/instrument.py
- music21/midi/__init__.py
- music21/midi/percussion.py
- music21/midi/translate.py
**Feature**:
Read from an `Instrument` instance's `.midiChannel` attribute when assigning MIDI channels on export. Update: also set program and channel on import.
- Give unpitched percussion a default midiChannel of 10 (9 in music21, which uses 0-indexing on Instrument instances).
- Fix 0-index vs. 1-index confusion in `instrument.autoAssignMidiChannel()`
- Improve docs
- Set .midiChannel and .midiProgram on Instrument instances on import.
Refs #398 
Also refs #465 but doesn't address note-by-note channel changes, which, if we continue on the current model, would need Instrument instances created each time.
<s>**Future work for another PR**:
- Ensure instrument identification from MIDI files captures most drum programs. As discussed in #398 it's possible we will need a DrumSet class. </s> …
> Import/Export MIDI channel and import MIDI program

- music21/braille/basic.py
- music21/braille/segment.py
- music21/braille/translate.py
- music21/corpus/__init__.py
- music21/corpus/manager.py
- music21/expressions.py
- music21/features/base.py
- music21/graph/plot.py
- music21/harmony.py
- music21/humdrum/__init__.py
- music21/mei/base.py
- music21/roman.py
- music21/search/serial.py
- music21/serial.py
A lot of early documentation did not make a strong distinction between functions and methods.  Went through some places and clarified.
Noticed during review of #962
> Improve Trills and Make sure "methods" are methods

- music21/_version.py
- music21/base.py
- music21/musicxml/testTab.xml
- music21/musicxml/xmlToM21.py
... and create unlinked durations if discrepancies.
Fixes #779 
<s>I say I'm not going to jump on these and then it turns out to be just one more line to add. Needs tests before it's ready. </s> (Added one test.) And verify this is the direction we want to go.
> Check literal duration from MusicXML against notated type and create unlinked durations

- music21/duration.py
- music21/musicxml/m21ToXml.py
I had this lying around (not pulling an all-nighter!)
**Motivation**:
Some tiny durations raise exceptions when accessing their types. My real-world case for this was reducing an orchestral score using `chordify()` and ending up with a 1/72 QL from the difference between one violin part with a 9/8/32nd tuplet run and another part with 8 32nd notes. This is how we handle large types, so here I extend it to small types.
MusicXML export should still fail if the type is inexpressible (and in one case they were getting all the way through and exporting invalid musicxml), but better to fail there (seems to me) than when just merely creating the duration and accessing the type.
```
>>> from music21 import *
>>> d = duration.Duration(1/72)
>>> d.type
File …
```
> Create inexpressible durations from tiny durations instead of raising

- music21/converter/__init__.py
- music21/stream/base.py
- music21/stream/core.py
- music21/stream/tests.py
- music21/variant.py
Inspired by mailing list 4/2/21
This would be the error if someone tried to follow my advice to `.show('text')` on a stream where iterators were inserted (user error!). Easy improvement.
**Update: ** also add `coreGuard...` check to Stream constructor.
```
>>> src = stream.Stream()
>>> otherStream.append(src.iter)
>>> otherStream.show('t')
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music21/stream/base.py", line 1844, in elementOffset
o = self._offsetDict[id(element)][0]
KeyError: 4469622288
During handling of the above exception, another exception occurred:
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music21/base.py", line 894, in …
```
> v7 Stream constructor improvements

- .github/ISSUE_TEMPLATE/feature_request.md
FYI @mscuthbert I don't like how the intent boxes on the feature request template show up as task lists when viewing the rows of the issue board. We don't have to use actual Markdown for this. What do you think?
> Prevent intent boxes from turning into task list

- .github/ISSUE_TEMPLATE/bug_report.md
Don't want to be THAT strict for other OSes in the contributing guide.
> Give caveat about other OSes

- music21/analysis/reduction.py
- music21/audioSearch/__init__.py
- music21/audioSearch/scoreFollower.py
- music21/figuredBass/realizer.py
- music21/stream/base.py
- music21/stream/iterator.py
- music21/stream/tests.py
Fixes #947 
Changed in v7:
- [earlier PR:] out of range indexes now raise an IndexError, not StreamException
- class searches now recursive
- negative slice indices now work
-  Unsupported types now raise TypeError
- Class and string searches now return a `StreamIterator` rather than a `Stream`
- slice searches return a list, not a `Stream`
> Improve `Stream.__getitem__()`

- music21/analysis/reduction.py
- music21/audioSearch/__init__.py
- music21/braille/segment.py
- music21/capella/fromCapellaXML.py
- music21/converter/subConverters.py
- music21/instrument.py
- music21/midi/translate.py
- music21/musicxml/xmlToM21.py
- music21/note.py
- music21/noteworthy/translate.py
- music21/search/base.py
- music21/stream/base.py
- music21/stream/filters.py
- music21/stream/iterator.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
- music21/tinyNotation.py
- music21/tree/verticality.py
Give the type/duration-fullName of the rest or something useful if type is too long.
Wanted since v3 or so but finally got around to implementing.
> Give more info in Rest __repr__

- music21/stream/makeNotation.py
Missed in #922.
`returnObj` is already a deepcopy if need be, so just like the branch below for voices, we should just edit inPlace instead of doing more copies.
> Prevent unnecessary deepcopies in `makeRests()`

- music21/_version.py
- music21/base.py
- music21/duration.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/note.py
Fixes #968 
Reproduced the bug on 3.1.0, actually!
The issue was that you can't derive type from components once the duration is unlinked. And the constructor for a GraceDuration sets .linked = False shortly after calling the superclass constructor. So the GraceDuration constructor is your only chance to get a type set automatically. Figured this fix, deliberately setting type, was cleaner than some sort of (`if not self.components: self.linked = True`) logic in the GraceDuration constructor that might just cause bugs later.
> getGraceDuration() now sets type on GraceDuration

- music21/features/jSymbolic.py
Generic `Instrument` objects (the fall back for several file parsers) have a `.midiProgram` of None, so we can't use that value as an index in the feature extractors.
```
>>> i = instrument.Instrument()
>>> s = stream.Stream()
>>> s.append(i)
>>> s.append(note.Note())
>>> fe2 = features.jSymbolic.PitchedInstrumentsPresentFeature(s)
>>> fe2.extract()
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music21/features/base.py", line 249, in extract
self.process()  # will set Feature object to _feature
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/music21/features/jSymbolic.py", line 3354, in process
self.feature.vector[i.midiProgram] = 1
TypeError: …
```
> Check if `Instrument.midiProgram` is None in feature extractors

- music21/freezeThaw.py
- music21/lily/translate.py
- music21/stream/base.py
- music21/variant.py
**Before**
`Score(Part(Measure(Note())))` gave Score > Measure > Note, because `common.isIterable(myPart)` evaluated True and we just took the `.elements` of `myPart`, effectively flattening the provided container away.
#946 didn't make this any worse, as far as I can tell, but by providing additional support for single elements, we would have nudged people toward this banana peel by encouraging them to send single elements to the constructor. So this is another case we should handle.
**Now**
We don't flatten the provided container when sending that single Stream container to `Stream()`, i.e. we wrap it in a list.
Spruced up some doctests that were previously demonstrating the antipattern.
There are some **very** deep problems with this previous antipattern in LilyPond and Variant that …
> Don't flatten Stream containers when passing to Stream()

- music21/musicxml/m21ToXml.py
- music21/note.py
- music21/stream/base.py
#982 was a little too strict when defining the new error condition for 'zero' duration.
If a user creates a vanilla GraceDuration() (i.e. without calling `getGrace()` to get a grace duration with a type), and it makes it to the MusicXML exporter, it seems harmless to give them a default of an eighth.
> Provide default type when exporting grace durations to musicxml

- music21/analysis/discrete.py
- music21/metadata/__init__.py
`s.analyze('range')` is now a synonym for `s.analyze('span')`, which is a much faster algorithm. That means in the rare cases where there were no instances of a repeated note in a stream, the previous nonzero minPitch is now zero.
***
Prevents segfaults I was seeing when trying to cache metadata.
**More information**
This algorithm is O(n^2), so any extra values should be filtered out of `psFound` before running an expensive computation. We don't need more than two instances of any `ps`, because they'll just produce the same interval.
https://github.com/cuthbertLab/music21/blob/ebc47a1fbc9d65981bc52928593b4b564ae96cd5/music21/analysis/discrete.py#L1079-L1091
While debuggging I printed `psRange` being computed for one stream to a file, and it consumed > 500 MB before I interrupted the …
> Remove Ambitus.getPitchRanges()

- music21/stream/makeNotation.py
Fixes #345 
Applied equally with or without tuplets -- just an issue with makeBeams() in general.
**Before**
**Patch**
The variables `noteStream` and `noteGroups` are temp streams, so it's safe to edit.
> Ignore grace notes when beaming

- music21/_version.py
- music21/base.py
- music21/musicxml/m21ToXml.py
- music21/stream/base.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
Handling some cases not handled by #922.
**Before**
This describes the first bullet point under "Now", below.
#922 was the first effort toward recursing in `makeRests()`. It wasn't quite enough -- final rests in Voices weren't created from the last element to the end of the bar, because the Voice objects don't have a `.barDuration`. Then, a loose rest was eventually created outside of the voices on the Measure object (see the regression test I included--the first test would have failed). Update: I'm actually only describing the MIDI parsing workflow. Reading voices as defined in a musicXML file is unaffected.
**Now**
- refactored `makeRests` to handle voices early enough that measure bar duration is accessible for voices
- recursed over parts, since that was the remaining nested stream …
> makeRests() gets bar duration context for voices from measures and recurses into Parts and checks for measure padding

- music21/stream/base.py
- music21/stream/tests.py
I was using `melodicIntervals()` with the intent to find desired intervals and then extract the measure context by accessing .noteStart and then .derivation.origin, but I was encountering broken derivation chains because of the way `.noteStart` is set *after* the interval is created from `Pitch` objects:
```
>>> n = note.Note()
>>> n2 = note.Note()
>>> i = interval.notesToInterval(n.pitch, n2.pitch) # from pitches
>>> i.noteStart = n  # set the note afterward
>>> i.noteEnd = n2
>>> i.noteStart is n
False
>>> i.noteEnd is n2
True
```
The above example only happens in `melodicIntervals()` if chords are involved, so this PR just has melodicIntervals handle chords as it does notes and create intervals from Note objects, not Pitch objects. Took the opportunity to simplify a little bit, also.
> Set `Interval.noteStart` when `melodicIntervals()` encounters Chords

- music21/stream/base.py
This will now match `Score.makeNotation()` and `Measure.makeNotation()`.
> v7 `Stream.makeNotation(inPlace=True)` returns None

- documentation/source/usersGuide/usersGuide_11_corpusSearching.ipynb
- music21/common/formats.py
- music21/converter/subConverters.py
- music21/defaults.py
- music21/stream/tests.py
There was a [comment](https://github.com/cuthbertLab/music21/issues/456#issuecomment-544558681) a while ago about doing this for v6, so when I saw `.endswith('-2.xml')` in the temp files cleanup patch, I thought "let's cross this off now".
(Let me know if I've severely misunderstood the point of the comment!)
> v7 Write `.musicxml` files instead of `.xml` if `fp` not given

- music21/lily/translate.py
Spotted when testing #1001 but doesn't address the reporter's issue.
> Fix LilyPond crash where Lyric.text is None

- .github/scripts/install_ubuntu_deps.sh
- music21/lily/translate.py
Turns out LilyPond started supporting hex colors this year. Simpler than using `webcolors` to convert to RGB.
Fixes #1001 and fixes #541 (duplicates)
"#FF0000"
"darkgreen"
> Fix LilyPond color statements

- music21/converter/subConverters.py
Only caught one of these when making late adjustments to #1007
> Add second explicit check for None in headless MuseScore Linux defaults

- music21/roman.py
**Previously**
```
File "/Users/jwalls/music21/music21/roman.py", line 851, in __main__.romanNumeralFromChord
Failed example:
roman.romanNumeralFromChord(harmony.NoChord())
Exception raised:
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
exec(compile(example.source, filename, "single",
File "<doctest __main__.romanNumeralFromChord[27]>", line 1, in <module>
roman.romanNumeralFromChord(harmony.NoChord())
File "/Users/jwalls/music21/music21/roman.py", line 1012, in romanNumeralFromChord
thirdType = chordObj.semitonesFromChordStep(3)
File "/Users/jwalls/music21/music21/chord/__init__.py", line 3469, in semitonesFromChordStep
tempInt = self.intervalFromChordStep(chordStep, testRoot=testRoot)
File …
```
> Fix crash when romanNumeralFromChord gets empty chords

- music21/features/base.py
- music21/features/native.py
Fixes #907 
Open for suggestions on how best to do this. We shouldn't reuse the id, it seems to me. But we don't want it returned in `allFeaturesAsList()`.
> Remove ComposerPopularity

- README.md
- music21/musicxml/m21ToXml.py
- music21/stream/base.py
- music21/stream/tests.py
- Fixes #994: `stripTies()` sets StreamStatus.beams = False
- for that to have effect, refactored `fixupNotationMeasured()` in musicxml export so that it doesn't use a dummy stream as an iterator and then query that dummy stream for its beam status
- called `splitAtDurations()` earlier in musicxml export so that it happens before fixupNotationMeasured remakes beams
- moved full-measure rest splitting logic out of musicxml exporter and into `splitAtDurations()`
> `stripTies()` now sets StreamStatus.beams = False

- music21/stream/base.py
- music21/stream/tests.py
Fixes #1026: permit providing chords to Stream constructor
Fixes #976: append rather than insert when providing a list of Scores to stream constructor (i.e. `Opus()`)
> Permit providing Chords to Stream constructor

- music21/analysis/floatingKey.py
- music21/analysis/reduction.py
- music21/base.py
- music21/braille/segment.py
- music21/clef.py
- music21/figuredBass/checker.py
- music21/graph/axis.py
- music21/graph/plot.py
- music21/layout.py
- music21/lily/translate.py
- music21/midi/translate.py
- music21/musicxml/xmlToM21.py
- music21/repeat.py
- music21/search/base.py
- music21/stream/base.py
- music21/stream/core.py
- music21/stream/filters.py
- music21/stream/iterator.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
- music21/tempo.py
- music21/variant.py
- music21/volume.py
Fixes #1025 
I had this lying around from when I wrote up the issue. Just tweaked the doc string on the `__call__()` method a bit and it was ready to go.
On second glance, some of these existing calls to `.iter` look unnecessary, <s>but I didn't stop to audit them all.</s> so I spruced them up to get Pylint to pass (two extra characters knocked a couple of these over the line limit!)
> Support and recommend `.iter()` instead of `.iter`

- music21/musicxml/m21ToXml.py
> Prevent writing `<part-group>` tags on multi-staff parts

- music21/musicxml/xmlToM21.py
After #1008 I've got MuseScore files emitting dozens of warnings:
```
WARNING: Cannot put in an element with a missing voice tag when no previous voice tag was given.  Assuming voice 1... 
```
Turns out they don't write `<voice>` tags on `<forward>` elements and just expect readers to infer the voice context. So extended a workaround already present for an issue with Sibelius.
The spec says `<voice>` tags are optional on forward tags but also that "The forward element is generally used within voices and staves."
> Handle `<forward>` elements without `<voice>`

- music21/key.py
- music21/midi/translate.py
- music21/stream/tests.py
I built this for someone, and I'm offering it back upstream. It's what I had suggested in reviewing #781.
> Let `asKey()` solve for mode from tonic and sharps

- music21/chord/__init__.py
- music21/stream/base.py
- music21/stream/tests.py
Fixes #1000
Also changed `findConsecutiveNotes()` to scan each Voice of Measure or Part of Score separately rather than flattening. Used existing `noNone=False` functionality to insert None when backing up to scan another Voice or Part.
Previously, notes in Voices could be accessed with getOverlaps=True (not default), but the results were likely unwanted:
```
>>> from music21 import stream
>>> m = stream.Measure()
>>> m.repeatAppend(note.Note(), 4)
>>> m.repeatInsert(note.Note(), [0, 1, 2, 3])
>>> m.makeVoices(inPlace=True)
>>> for i, elem in enumerate(list(m.recurse().notes)):
...     elem.transpose(i, inPlace=True)
... 
>>> p = stream.Part(m)
>>> p.show('t')
{0.0} <music21.stream.Measure 0 offset=0.0>
{0.0} <music21.stream.Voice 0x105077880>
{0.0} <music21.note.Note C>
{1.0} …
```
> `findConsecutiveNotes()` no longer evaluates a flat version

- music21/scale/__init__.py
Fixes this issue (and there are tonic-less uses like this in the test suite, for instance, calling `getPitches()` will assume a tonic of C4):
```
>>> sc = scale.MinorScale()
>>> sc
File "/Users/jwalls/music21/music21/prebase.py", line 236, in __repr__
strRepr = self._reprInternal()
File "/Users/jwalls/music21/music21/scale/__init__.py", line 1381, in _reprInternal
return f'{self.tonic.name} {self.type}'
AttributeError: 'NoneType' object has no attribute 'name'
```
The repr() was simplified in f58395e45b to just be the same as the .name when a tonic exists, so let's just DRY it out and grab the .name.
> Fix repr() of scales without tonics

- music21/environment.py
Hi,
I add two checks for read & write permission of the root temp directory.
I also modify the naming rule of alternative temp directory for ~Linux~ Linux and Mac platform with "music21-$UID" (which is "music21-$(8-digit hashed code)" originally). It can avoid music21 creating too many directories while using the alternative temp directory.
> Refactor catching of OSErrors when finding default temp directories, and improve the naming of fallback temp directories for Linux and Mac platforms

- .github/workflows/pythonpylint.yml
see most recent PR run and https://github.com/PyCQA/astroid/issues/1080
edit: it's probably much simpler to simply disable pylint checks on the one method having trouble in text.py, come to think of it.
edit edit: with limited time before v7, how about we just also pin pylint until after v7
> Pin pylint==2.8.3

- documentation/source/usersGuide/usersGuide_55_advancedMeter.ipynb
- music21/metadata/__init__.py
- music21/stream/base.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
As mentioned in v6.7 release notes.
> Support and recommend `.sorted()` instead of `.sorted`

- .github/workflows/pythonpylint.yml
- .pylintrc
- music21/_version.py
- music21/abcFormat/__init__.py
- music21/base.py
- music21/chord/tables.py
- music21/common/classTools.py
- music21/ipython21/objects.py
- music21/lily/lilyObjects.py
- music21/mei/test_base.py
- music21/note.py
- music21/stream/base.py
- music21/test/commonTest.py
- music21/test/testLint.py
- music21/tree/verticality.py
- requirements-minimum.txt
- suppress `consider-using-dict-items` and `arguments-renamed`
- resolve the other pylint issues detected
- accelerate the deprecation timeline for `.sorted` -- emit a DeprecationWarning on stream deletion (for `iter` in v.8, I was planning to do something similar in `__next__`, but there's not a great place to do it on a Stream for `.sorted` --what do you think?)
> Add deprecation warning for .sorted and some Pylint fixes

- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/tempo.py
As suggested, this PR adds a positionPlacement to MetronomeMark. It also enables the corresponding import from xml, converts xml placement to positionPlacement.
> add positionPlacement to MetronomeMark

- music21/dynamics.py
- music21/expressions.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/tempo.py
Fixes #377 
Also, document the attribute for the first time.
cc @gesellkammer
cc @gregchapman-dev
> Rename `positionPlacement` to `placement` on Dynamic, TextExpression, and MetronomeMark

- music21/_version.py
- music21/base.py
- music21/meter/base.py
- music21/musicxml/xmlToM21.py
- music21/stream/makeNotation.py
- music21/stream/tests.py
- Set paddingRight on musicXML import
- `makeBeams()` now observes a difference between paddingLeft and paddingRight instead of treating all incomplete measures as having paddingLeft
- `getBeams()` for 6/8 fixed to handle quarter + eighth + eighth:
- should be None, None, None
- was None, 'start', 'stop' if incompleteness programmatically interpreted as paddingLeft (see above)
- was None, None, 'stop' once above issue was fixed
> Set paddingRight on MusicXML import and fix beaming of quarter + eighth in final incomplete 6/8 measure

- setup.py
Reads minimal requirements from the adjacent requirements.txt and uses them to define the install_requires
options for setuptools.
This addresses https://github.com/cuthbertLab/music21/issues/338 and fixes https://github.com/cuthbertLab/music21/issues/1050.
I tested using the following procedure:
```
git_home=~/Downloads
repo_name=music21
repo_path=${git_home}/${repo_name}
repo_url=https://github.com/JamesOwers/music21.git
git clone ${repo_url} ${repo_path}
conda create -n ${repo_name}-dev python=3.8 --yes
conda activate ${repo_name}-dev
pip install ${repo_path}
python -c 'import jsonpickle' && echo 'This succeeded as expected!'
```
> Parse requirements from file

- music21/duration.py
#908 didn't handle toggling `.expressionIsInferred` back to False when setting type/dots after construction.
No change when setting tuplets, since part of the point is that for numeric durations such as 4/3, they still bear .expressionIsInferred = True even when expressed with tuplets.
While here, I noticed that the attribute should likely be set True when setting numeric qL on unlinked durations, not just on linked durations.
> Handle more expressionIsInferred toggling on Durations

- music21/audioSearch/recording.py
- music21/midi/realtime.py
A recent change to run TestExternal had the drawback that it imported pygame and pyaudio every time music21 was started (if it was installed), adding half a second to music21 start. 
All parts of a Class definition that are not in a `def` are run on music21 startup.  Therefore setup commands, etc. for test modules / rarely run modules need to be fast, or music21 startup will slow to a crawl.  (hence lazy importing of matplotlib, etc.)
> Do not import pygame/pyaudio until needed

- music21/chord/__init__.py
Still TODO: subclass commonName on roman.RomanText to give a common name for Neapolitan (maybe)
> Add commonName for other Aug chord inversions

- music21/_version.py
- music21/base.py
- music21/converter/__init__.py
- music21/stream/base.py
- music21/stream/tests.py
Fixes #811
Avoid gaps that don't fit quantization scheme (1/6 QL rests, etc.) by looking ahead to see the divisor that will be used to quantize the subsequent offset.
***
Example file: https://github.com/cuthbertLab/music21/blob/master/music21/midi/testPrimitive/test01.mid
**Finale (reference)**
**m21 roundtrip Before**
**m21 roundtrip After**
> Avoid gaps that don't fit quantization scheme

- music21/base.py
- music21/common/enums.py
- music21/instrument.py
- music21/prebase.py
- music21/sites.py
- music21/stream/base.py
- music21/stream/filters.py
- music21/stream/tests.py
- music21/tempo.py
- music21/tree/fromStream.py
- music21/tree/timespanTree.py
- music21/tree/toStream.py
- music21/voiceLeading.py
- music21/volume.py
Fixes #1028 with documentation changes.
Adds `ElementSearch` enum and cleanup for `getContextByClass()`.
Various v. 7 deprecations per release notes in v.6.7.0:
- `getClefs()`
- `getKeySignatures()`
- `makeChords()`
- `extendDurationsAndGetBoundaries()`
- `tree.toStream.chordified()`
- `tree.toStream.partwise()`
- `VoiceLeading.color`
- `isClassOrSubclass()`
> `ElementSearch` enum for `getContextByClass` and related deprecations

- music21/base.py
The first constant was a tuple; the other four were sets. Purely an oversight. Collections of indeterminate length should just be lists.
> Cleanup: make all getContextByClass() constants lists

- music21/_version.py
- music21/base.py
- music21/midi/translate.py
Fixes #1085 
Thanks to @Meekohi for the report. Oversight in #589.
Bumped the minor version so that parsed files won't accidentally be loaded when testing the fix.
Regression test fails on current version.
> Set correct MIDI program when constructing instrument from name given in MIDI file

- music21/midi/translate.py
The basic idea is that we should create a better fallback instrument when we have bad MIDI data on channel 10, because this information is starting to be used to create and manage `note.Unpitched` instances.
And a side benefit: reduce indentation
> Return UnpitchedPercussion instance when MIDI instrument lookup fails on channel 10

- music21/converter/subConverters.py
Regardless of whether we make all the keywords explicit in #872, there's no reason not to permit them to work when calling `show()` or `write()`!
Makes debugging easier.
> Enable braille keywords in show() and write()

- music21/chord/__init__.py
- music21/note.py
- music21/roman.py
Fixes Python DeprecationWarnings:
`DeprecationWarning: NotImplemented should not be used in a boolean context`.
This is because `NotImplemented` is truthy. Haven't checked to see if this has been causing logic issues.
> NotImplemented fixes for subclass `__eq__()` methods

- music21/braille/basic.py
- music21/pitch.py
- music21/stream/base.py
- music21/stream/tests.py
Fixes issue demonstrated in regression test. Need to reiterate accidentals in subsequent measures when making accidentals on a score.
Surely escaped notice in the past by musicxml export pipeline running makeNotation() and ultimately `Part.makeAccidentals()` rather than `Stream.makeAccidentals()`.
> Reiterate accidentals each measure in Stream.makeAccidentals()

- music21/converter/subConverters.py
Fixes #1089 -- although silencing everything might seem heavy-handed, printing 7 messages for every success seems much.
> Silence MuseScore command-line output in case of success

- music21/stream/makeNotation.py
Some of the changes to makeRests in v7 introduced expensive context searching by calling `barDuration` on Measure objects, which have to look left to get a time signature, which can be a long distance.
UPDATE: fixed test failure.
> Avoid so much context searching in makeRests()

- music21/duration.py
Follow up to #1072 to show snapshot of current support for nested tuplets and their outer brackets.
> Add test showing state of nested tuplet support (brackets)

- music21/musicxml/m21ToXml.py
- music21/stream/base.py
- music21/stream/tests.py
By not restoring original instrument lengths we were creating instruments with quarter lengths like 40.0, which is a complex duration that was being split by  `splitAtDurations`.  Then we'd end up with two Instrument objects in measure 1, one of which was FAR FAR later, so even though it was being removed in output, it caused a massive `<forward>` tag in the musicxml output which caused spacing to be terrible.
Also saves making a second deepcopy of a score for 98% of show() cases which don't have complex durations.
> Restore original instrument lengths after _transposeByInstrument

- music21/expressions.py
- music21/stream/makeNotation.py
```
File "/Users/jwalls/music21/music21/stream/makeNotation.py", line 1689, in makeAccidentalsInMeasureStream
tiePitchSet = getTiePitchSet(previousNoteOrChord)
File "/Users/jwalls/music21/music21/stream/makeNotation.py", line 1625, in getTiePitchSet
tiePitchSet.add(n.pitch.nameWithOctave)
AttributeError: 'Unpitched' object has no attribute 'pitch'
```
***
The other way to do it is to check `hasattr(n, 'pitch')`, which we do elsewhere, but this is slightly more explicit to say why the check is needed.
> Prevent AttributeError when making accidentals

- music21/mei/base.py
- music21/musicxml/helpers.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
ElementTree in its C form is very delicate (see: https://stackoverflow.com/questions/60470643/python-xml-typeerror-subelement-argument-1-must-be-xml-etree-elementtree-el)  -- I have been running into problems with
```
import xml.etree.ElementTree as ET
from xml.etree.ElementTree import Element, SubElement
root = Element('root')
comment = ET.Comment('hi')
root.append(comment)
```
that they are binary incompatible, when running music21 under other frameworks (Django, etc.) -- it is safer if everything is imported from the same file at the same time.  Thus, all imports on one line, no namespace prefixes.
Prevents: `must be xml.etree.ElementTree.Element, not Element` errors.
> Safer ElementTree by always importing from same file

- music21/stream/base.py
- music21/stream/makeNotation.py
Allow making beams on individual measures that may lack a `TimeSignature` by getting the time signature from the context.
Useful for operating on, say, just the final measure of a part.
> Allow making beams in individual measures without time signatures

- music21/analysis/reduceChords.py
- music21/analysis/reduction.py
- music21/musicxml/m21ToXml.py
Prevents warnings emitted since df7308c8960280413289575f31169a8011fea149 (v7 dev)
```
.../music21/music21/musicxml/m21ToXml.py:1635: StreamIteratorInefficientWarning: makeRests is not defined on StreamIterators. Call .stream() first for efficiency
```
> Resolve warnings emitted by musicxml exporter

- music21/converter/subConverters.py
Follow up to #1104 -- this test was supposed to target the uncovered line in #1104 where there is _not_ a provided filepath. Not a typical usage scenario, best to just call `my_stream.write()` with any of:
- path ending in .mxl
- fmt = 'mxl'
- compress=True
> Improve test for advanced usage of ConverterMusicXML

- music21/converter/__init__.py
If a user has mislabeled their uncompressed musicxml file with the `.mxl` filepath, and then actually compressed it, in all likelihood, the zipfile archive will show the original path ending in '.mxl' as the uncompressed contained filepath.
This was never contemplated. It would have failed silently.
After a59c91e4fa it fails loudly with a crash, which was helpful for diagnosing the issue. Handled the crash and the use case.
> Handle .mxl files zipped up from mislabeled .mxl files

- .github/workflows/pythonpylint.yml
- music21/converter/__init__.py
- music21/converter/qmConverter.py
- music21/converter/subConverters.py
- music21/features/outputFormats.py
- music21/freezeThaw.py
- music21/midi/__init__.py
- music21/musicxml/m21ToXml.py
- music21/romanText/tsvConverter.py
- music21/test/multiprocessTest.py
- music21/vexflow/toMusic21j.py
Pylint 2.10.x introduced `unspecified-encoding` to force projects to decide if they support cross-platform file I/O. We can suppress this check, or, better I suppose, make explicit whether we are relying on `utf-8` or can tolerate the system default. We may as well help people stay platform-agnostic, no?
How does this look? (I pulled over one other commit from the `september-miscellany` branch (u-prefixes) so I can unpin Pylint on this one.)
> Make text file encoding explicit

- music21/test/multiprocessTest.py
- `getdefaultencoding()` is on `sys`, not `locale`. whoops! mistake in #1117.
- Just remove needless complexity and write in 'utf-8', since this is just a library developer tool.
> Fix improper call to locale library in multiprocess test text output

- music21/stream/base.py
- music21/stream/tests.py
`stripTies()` crashed in a scenario where:
- `matchByPitch=False` (only currently used in MIDI writing; default is otherwise True)
- a Chord with "stop" or "continue" ties follows a Rest
(that would seem malformed, but for the fact that stripTies() flattens the part, so you can have a perfectly valid measure that when flattened gives a stop tie following a rest in virtue of there being voices)
Regression in b7bcad9914 (v7.1)
Luckily, `matchByPitch` defaults True in v7, so this only affects MIDI writing by default.
Reported in StackOverflow [post](https://stackoverflow.com/questions/69140830/music21-write-function-giving-attributeerror-rest-object-has-no-attribute).
***
I'm not certain why `matchByPitch` is still False in the MIDI writer. I suppose I just was unwilling to change something …
> Fix `stripTies()` crash in certain scenario with matchByPitch=False

- .pylintrc
- music21/abcFormat/testFiles.py
- music21/alpha/analysis/ornamentRecognizer.py
- music21/braille/basic.py
- music21/chord/__init__.py
- music21/converter/__init__.py
- music21/expressions.py
- music21/lily/translate.py
- music21/mei/test_base.py
- music21/metadata/primitives.py
- music21/romanText/rtObjects.py
- music21/variant.py
- music21/voiceLeading.py
Postpone `consider-using-f-string` until existing codebase is updated (53 warnings). Leave `consider-iterating-dictionary` and `consider-using-in` enabled.
Cherry-picked from #1131 so that it can be merged faster and unblock other PRs.
> Postpone consider-using-f-string

- music21/figuredBass/realizer.py
**Previously**
Only line-separated lyrics such as `'6\n4'` were supported in `figuredBassFromStream()`.
**Now**
Lyrics such as `'64'` and `'#6#4'` are supported.
This allows for fast entry of figured bass using tinyNotation, which doesn't support line breaks.
> Support multiple figures in single lyric (e.g "64") in `figuredBassFromStream()` 

- music21/figuredBass/realizer.py
Fixes regression in e51729f.
See added regression test cases; they failed with:
```
ERROR: testMultipleFiguresInLyric (__main__.Test)
File "/Users/jwalls/music21/music21/figuredBass/realizer.py", line 851, in testMultipleFiguresInLyric
unused_fb = figuredBassFromStream(s)
File "/Users/jwalls/music21/music21/figuredBass/realizer.py", line 151, in figuredBassFromStream
annotationString = updateAnnotationString(annotationString, lyric_line.text)
File "/Users/jwalls/music21/music21/figuredBass/realizer.py", line 136, in updateAnnotationString
annotationString = updateAnnotationString(annotationString, …
```
> Add safety and more characters to `figuredBassFromStream()`

- music21/midi/translate.py
Another way of preventing the issue in #1126 is to just use the safer method of stripping ties during MIDI export.
matchByPitch was False since the inception of the MIDI exporter, and since then the speed vs. accuracy tradeoff has swung way, way in favor of accuracy. Essentially a follow-up to #818.
> Use matchByPitch=True in MIDI export

- music21/musicxml/m21ToXml.py
Previously, only color information was exported from individual chord members (Note instances), not other style attributes.
> Export style attributes from chord members

- music21/analysis/reduceChordsOld.py
Fixes #1024 
After fixing the site crash in the `coreInsert()` call, another problem revealed itself relating to zero-duration chords:
```
File "/Users/jwalls/music21/music21/musicxml/m21ToXml.py", line 91, in typeToMusicXMLType
raise MusicXMLExportException('Cannot convert durations without types to MusicXML.')
music21.musicxml.xmlObjects.MusicXMLExportException: In part (None), measure (20): Cannot convert durations without types to MusicXML.
```
> Fix zero-duration chords and coreInsert crash in reduceChordsOld

- music21/articulations.py
- music21/braille/basic.py
- music21/braille/lookup.py
- music21/braille/segment.py
In February I was doing some work with MusicXML treatment of fingerings/TechnicalIndications, and I was learning how to debug the braille module to get CI jobs to pass. At the time I looked into the combination of the two, and then I rebased at some point in September but never opened a PR.
This PR:
- adds bowing symbols to braille export
- tightens up an edge case involving TechnicalIndications beyond Fingerings that should not be exported
- adds some coverage
- small docs fixes
> Braille: export bowing symbols

- music21/mei/base.py
- music21/test/testLint.py
Gave `bad-option-value` once this check was removed to extensions.
Refs https://github.com/PyCQA/pylint/pull/5298
> Pylint removed misplaced-comparison-constant

- music21/instrument.py
- music21/midi/percussion.py
- music21/midi/translate.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
Read and write `<midi-unpitched>` tag so as to import and export unpitched percussion instruments in MusicXML.
Also resolve confusion over whether m21's percussion mapper is 1-indexed (it's not). (Fixed up the confusion over this I introduced to docs and MIDI import.)
> Import/export unpitched percussion instruments <--> MusicXML

- .github/workflows/maincheck.yml
- music21/__init__.py
- music21/chord/__init__.py
- music21/note.py
Adds all music21 modules by name to `__init__.py` imports, hopefully making life easier for certain IDEs.  For a long time, the music21 core modules were changing almost weekly, so `import *` within `__init__.py` was the best approach.  Now we add or rename a core module maybe once a year, so this should be a good approach.
Also add Python 3.10 to the github matrix.  All tests currently passing without warnings.
> Explict imports in init.py; support 3.10

- music21/instrument.py
Just a small modernization task since this code predated `importlib` in Python 3.
> Avoid calling globals in `instrument.fromString()`

- music21/note.py
- music21/stream/base.py
Only causes problems, and getElementsByClass is now very fast.  No need for caches.
> Disable caches for .parts, .notes, .notesAndRests

- music21/languageExcerpts/naturalLanguageObjects.py
- music21/pitch.py
The Spanish translation of "flat" is "bemol". The accent mark that is currently used in music21 doesn't exist in Spanish. 
For reference:
https://es.wikipedia.org/wiki/Alteraci%C3%B3n_(m%C3%BAsica)
https://catalog.ldc.upenn.edu/docs/LDC2019S07/Rules_for_Spanish_Accent_Marks.pdf
> Replace bèmol with bemol in Spanish translation of flat

- music21/braille/basic.py
- music21/braille/segment.py
- music21/braille/test.py
Fixes side-effects on streams left by braille translator, and removes related workarounds in test suite.
Simple fix for now without committing to any refactoring.
> Clean up temporary attributes set by braille translator

- music21/midi/__init__.py
Fixes #1174
Alternative to #1175
@kwikwag, would you be interested to take a look? I added you as a co-author.
Using your benchmark (thank you) I see the same improvement (a hair better, even) as storing a `frozenset`. Avoids managing an extra class attribute (that will then require a mypy disable when we type-check the midi module soon.)
> Speed up MIDI enum membership tests

- music21/midi/translate.py
Fixes regression in v.7 (a56955ae50b87ee9f5145f8b6d63d629dc33e121). when making measures in MIDI import, if there is a non-empty conductor track, it was assumed to have a time signature. If it only had tempos, instrument names, etc., music21 raised:
```music21.exceptions21.StreamException: failed to find TimeSignature in meterStream; cannot process Measures```
> Don't choke on conductor tracks lacking meters

- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
Take 2 -- fixes #1129. Alternative to #1131.
@gregchapman-dev Another one here -- would you mind checking?
> Avoid exporting superfluous meters and keys in staff groups

- music21/stream/makeNotation.py
Fixes:
```python
AttributeError: 'PercussionChord' object has no attribute 'pitch'. Did you mean: 'pitches'?
```
> Fix exception in makeNotation for PercussionChord

- music21/corpus/corpora.py
Removing paths using `LocalCorpus.removePath()` didn't work for corpora persisted to disk because the infrastructure expects strings, not `Path` objects. `Path` objects were being used since v5 when the `common.cleanpath()` default changed.
Added a test for the _in-memory_ corpus to at least add some coverage, but I didn't see a way to add coverage for the case that was failing without rewriting a lot of the system. (E.g. add more `verbose=` arguments to silence warnings, add a step to CI that creates a path that is not Desktop, etc.).
Adding that test was useful, though, since I discovered _that_ codepath _does_ expect `Path` objects.
> Fix LocalCorpus.removePath() string/path confusion

- music21/environment.py
> Make GarageBand default MIDI player on MacOS

- music21/roman.py
Fixes  #1205. Patch by @napulen (Néstor Nápoles López)
See #1209 for original PR
> Clearing bracketedAlterations in RomanNumeral.figure.setter.

- music21/braille/examples.py
- music21/braille/translate.py
Previously, full scores containing piano music could not be exported.
```python
>>> beach = corpus.parse('beach')
>>> beach.show('braille')
File "/Users/.../music21/music21/stream/base.py", line 334, in show
return super().show(fmt=fmt, app=app, **keywords)
File "/Users/.../music21/music21/base.py", line 2758, in show
return formatWriter.show(self,
File "/Users/.../music21/music21/converter/subConverters.py", line 502, in show
super().show(obj, fmt, app=None, subformats=subformats, **keywords)
File "/Users/.../music21/music21/converter/subConverters.py", line 212, in show
returnedFilePath = self.write(obj, fmt, subformats=subformats, **keywords)
File "/Users/.../music21/music21/converter/subConverters.py", line 510, in …
```
> Make full scores containing piano parts exportable to braille

- music21/musicxml/m21ToXml.py
Improvements to `.measure(n).show()`:
- show the measure number (if no measure number style was set) so you can see what you exported
- show the part name and part abbreviation from the containing part
- fix a bug in musicxml export with a nonexistent member: `AttributeError: 'StreamStyle' object has no attribute 'measureNumberingStyle'`
- get the measure's clef from earlier in the context (previous measure)
- gather spanners
> Improvements to single measure extraction to musicxml

- music21/braille/examples.py
- music21/braille/segment.py
- music21/braille/text.py
- music21/braille/translate.py
- Add support for exporting music in voices to braille.
- Don't return braille unicode for metadata if `debug=True`
(- lines are actual, + lines are expected, this is with a `debug=True` export)
```python
AssertionError: Lists differ: ['⠠⠍⠕⠧⠑⠍⠑⠝⠞⠀⠠⠝⠁⠍⠑⠒⠀⠞⠺⠕⠴⠧⠕⠊⠉⠑⠎⠲⠭⠍⠇', '⠠⠞⠊⠞⠇⠑[1228 chars]---'] != ['Movement Name: two-voices.xml', 'Title: M[1179 chars]---']
First differing element 0:
'⠠⠍⠕⠧⠑⠍⠑⠝⠞⠀⠠⠝⠁⠍⠑⠒⠀⠞⠺⠕⠴⠧⠕⠊⠉⠑⠎⠲⠭⠍⠇'
'Movement Name: two-voices.xml'
Second list contains 19 additional elements.
First extra element 51:
'Octave 3 ⠸'
- ['⠠⠍⠕⠧⠑⠍⠑⠝⠞⠀⠠⠝⠁⠍⠑⠒⠀⠞⠺⠕⠴⠧⠕⠊⠉⠑⠎⠲⠭⠍⠇',
-  '⠠⠞⠊⠞⠇⠑⠒⠀⠠⠍⠥⠎⠊⠉⠼⠃⠁⠀⠠⠋⠗⠁⠛⠍⠑⠝⠞',
+ ['Movement Name: two-voices.xml',
+  'Title: Music21 Fragment',
'---begin segment---',
'<music21.braille.segment BrailleSegment>',
'Measure 1, Signature Grouping 1:',
'Key Signature 2 …
```
> Export music in voices to braille

- documentation/docbuild/documenters.py
- documentation/source/developerReference/documenting.rst
- music21/chord/__init__.py
We weren't publishing any of the documentation for special ("dunder") methods like `__eq__()` and `__getitem__()`, some of which are very useful to read about, like the new v7 bracket syntax.
Presumably this was to avoid polluting every class with the docs for Python's base implementations on `list`, etc, but this PR works around that by loosening the check for `object` to any builtin (`list`, etc.)
***
> Surface `__eq__()` and `__getitem__()` in doc builds

- music21/roman.py
Fixes #1217 
Fixes #1229 
FYI @napulen what do you think?
Clarification: this does not change any default behavior of figure or pitch parsing, but simply sets the attributes on the created RomanNumeral object to reflect how the figure should be interpreted, given the figure it was created with. (i.e., the method creates a cautionary "b" in "bVI", so set `sixthMinor` to `CAUTIONARY`.)
> Set sixthMinor and seventhMinor to CAUTIONARY in romanNumeralFromChord()

- music21/tempo.py
… And never set a default TempoText style when getting a property.
> Only set a default TempoText style if there is no style already set.

- music21/chord/__init__.py
Fixes #614 for common sevenths and ninths (sus chord workaround not really needed: "quartal trichord" doesn't imply triadic spelling).
New method `isNinth()`.
> Clarify enharmonic equivalents for common sevenths and ninths (commonName)

- music21/converter/subConverters.py
- music21/musicxml/helpers.py
- music21/musicxml/m21ToXml.py
Raise an exception instead of writing invalid values for duration types. Necessary for safety before removing the call to `splitAtDurations()` that makes in-place edits on streams where makeNotation=False (see https://github.com/cuthbertLab/music21/commit/a23a64a44e48ffbbeff4a4ae2dd55d08f366ce71#commitcomment-68049838).
/cc @gregchapman-dev
> Raise instead of writing invalid musicxml duration types

- music21/repeat.py
- music21/stream/base.py
- music21/stream/tests.py
Changes are as follows:
1. Implementation of @jacobtylerwalls 's [code snippet](https://github.com/cuthbertLab/music21/issues/1165#issuecomment-967293691) as a test case
2. Adjusting `mergeAttributes()` in `stream/base.py` to also port over `_partName` and `_partAbbreviation`
3. Manually calling `mergeAttributes()` at the end of `expandRepeats()`
If there are any grievous styling/syntax problems let me know!
> expandRepeats() partname (Fixes #1165)

- .idea/inspectionProfiles/Project_Default.xml
- music21/base.py
- music21/musicxml/archiveTools.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlObjects.py
- music21/musicxml/xmlSoundParser.py
- music21/musicxml/xmlToM21.py
- music21/style.py
Also fix some typos and errors noticed by PyCharm
Fixes #1271  -- does not implement musicxml 4, but puts notes where changes should go.
Change order of authors in a few places where substantial work has been done by others since original version was released
> Cleanups for musicxml 4 TODO status

- music21/_version.py
- music21/base.py
- music21/chord/__init__.py
- music21/chord/tables.py
- music21/corpus/chorales.py
- music21/figuredBass/checker.py
- music21/figuredBass/examples.py
- music21/figuredBass/notation.py
- music21/figuredBass/possibility.py
- music21/figuredBass/realizer.py
- music21/figuredBass/realizerScale.py
- music21/figuredBass/rules.py
- music21/figuredBass/segment.py
- music21/graph/primitives.py
- music21/harmony.py
- music21/musicxml/m21ToXml.py
- music21/note.py
- music21/pitch.py
- music21/roman.py
- music21/scale/__init__.py
- music21/sieve.py
- music21/stream/base.py
- music21/stream/core.py
master/main is now on v8.  A m21_7 branch has been created for any backward changes to put in v7.
* Update version number
* Chord.bass('new_bass') throws exception if new_bass is not in the chord, unless allow_add=True
* FiguredBass realizer stores notation objects in the note's Editorial not on the note object itself (typing cleanup)
* Change some obscure chord table names to things that make more sense to me
* Grammar fixes
> V8 -- cleanup 1

- music21/stream/iterator.py
The upgrade path is to call `.stream()` before attribute access.
Resolves #1137
> Deprecate `StreamIterator.__getattr__()`

- music21/base.py
Fix test failing on master by reverting a small bit from 2f345d1407c96fa54851fb47e4361d5162eae255.
> Fix repr() failure for Metadata

- documentation/docbuild/writers.py
- music21/common/misc.py
- music21/converter/subConverters.py
- music21/ipython21/__init__.py
- music21/ipython21/ipExtension.py
- music21/ipython21/objects.py
Jupyter Notebook comes with the require.js script for loading other modules already included.  Google Colab does not.  Showing MIDI in the notebook needs to have require.js around.  Google Colab runs each cell in its own WebWorker; thus the loading of require.js and music21j must happen in each cell -- no global variables.
Since Google Colab is still running Python 3.7 (and selecting another core is a PAIN!) and music21 v8 will be 3.8+ only, this functionality is being backported to v7 and a 7.3.2 version will be released.
> Fix MIDI in Google Colab Notebooks

- music21/abcFormat/__init__.py
- music21/bar.py
- music21/figuredBass/checker.py
- music21/figuredBass/examples.py
- music21/figuredBass/possibility.py
- music21/graph/__init__.py
- music21/graph/axis.py
- music21/graph/findPlot.py
- music21/graph/plot.py
- music21/graph/primitives.py
- music21/graph/utilities.py
- music21/mei/base.py
- music21/meter/tests.py
- music21/musicxml/xmlSoundParser.py
- music21/note.py
- music21/stream/iterator.py
- music21/test/testLint.py
Add option to plot pianoroll with each instrument in a different color.
> Improve graphing docs, typing, and options

- music21/stream/makeNotation.py
Let `makeRests(inPlace=True)` return None for consistency with other methods (and with itself).
> v8: makeRests(inPlace=True) returns None for scores

- music21/defaults.py
- music21/musicxml/m21ToXml.py
~Remove title and author defaults, and~ avoid writing empty tags for `<movement-title />` and `<creator />`.
> Avoid writing empty `<movement-title />` and `<creator />` tags when title and author have no defaults

- music21/pitch.py
- music21/stream/base.py
- music21/stream/tests.py
> Make cautionaryPitchClass=True work with chords

- .github/workflows/pythonpylint.yml
- music21/midi/__init__.py
- music21/midi/realtime.py
- music21/midi/translate.py
Only those input methods already used by music21 are allowed for midiEventsToNote and midiEventsToChord -- demonstration methods are removed.
> Type MIDI -- Simplify Choices

- .github/workflows/pythonpylint.yml
- music21/_version.py
- music21/abcFormat/__init__.py
- music21/alpha/analysis/search.py
- music21/base.py
- music21/chord/__init__.py
- music21/common/classTools.py
- music21/common/decorators.py
- music21/common/misc.py
- music21/common/numberTools.py
- music21/interval.py
- music21/meter/core.py
- music21/pitch.py
- music21/roman.py
- music21/romanText/translate.py
- music21/scale/__init__.py
- music21/scale/intervalNetwork.py
- music21/scale/test_intervalNetwork.py
- music21/scale/test_scale_main.py
- music21/search/lyrics.py
- music21/sites.py
- music21/stream/base.py
- music21/tree/fromStream.py
- music21/tree/trees.py
- music21/tree/verticality.py
- music21/voiceLeading.py
All of music21 code passes mypy now.  All future contributions must be properly typed.
This PR makes a few non-backwards compatible changes, mostly in the deep reaches of intervalNetwork.  Terminus and Direction are now Enums.
Tree classLists must be properly given as tuples of tuples.
> Finish Typing music21 (scale last)

- music21/midi/translate.py
- music21/note.py
> Export Unpitched to MIDI

- music21/common/numberTools.py
see post to music21list about details.
Switches the cache from 1024 to None -- not because we want to cache more than 1024 values, but to avoid the overhead of an LRU cache, which is significant.
Speeds up opFrac(0.5) by about 37% by giving a set of 20 values to return very quickly at a cost of adding 25% to opFrac(9/16) or 5% to opFrac(1/3) -- worth it -- though the lru_cache speedup makes the latter actually faster.
opFrac is the performance bottleneck of music21, so anything to speed it up is a big win.
> optimize opFrac

- music21/pitch.py
- music21/stream/base.py
- music21/stream/tests.py
- music21/test/test_pitch.py
Better solution than #1299. That PR caused a regression with this case:
```python
from music21 import chord
c = chord.Chord("D# F# A#")
c.show(app='Finale')
```
***
A better solution is to actually distinguish "past" from "simultaneous" rather than mixing the two notions.
> Fix a regression with chord accidentals

- music21/tinyNotation.py
Deprecated in 3.11, can just catch `re.error`
> Remove deprecated `sre_parse` module

- music21/musicxml/m21ToXml.py
- music21/musicxml/testPrimitive.py
Fix a regression in #1261 with midmeasure clef changes outside voices.
From Amy Beach corpus example:
**Before**
**After**
> Fix midmeasure clef export regression involving voices

- music21/common/numberTools.py
- music21/humdrum/spineParser.py
- music21/meter/base.py
- music21/meter/tools.py
- music21/sieve.py
math.gcd <s>and math.lcm</s> were added and use C-speed.
math.gcd is Py3.8; ok.  lcm is Py3.9, not ok.
> deprecate gcd in favor of C math

- documentation/docbuild/documenters.py
- music21/braille/basic.py
- music21/braille/segment.py
- music21/converter/__init__.py
- music21/corpus/corpora.py
- music21/duration.py
- music21/humdrum/spineParser.py
- music21/metadata/__init__.py
- music21/metadata/bundles.py
- music21/search/segment.py
- music21/search/serial.py
- music21/stream/base.py
- music21/stream/tests.py
Greg noticed his PRs failing on newer versions of `flake8`.
> Remedy flake8 warnings: missing whitespace after keyword

- music21/stream/base.py
`startOffset` and `endOffset` in this method work like excluding filters -- so this should read that elements outside the bounds are _not_ shifted.
> Fix shiftElements docs

- music21/roman.py
> SixthMinor carries to secondary. impr. docs

- music21/expressions.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/testPrimitive.py
- music21/musicxml/test_m21ToXml.py
- music21/musicxml/test_xmlToM21.py
- music21/musicxml/xmlToM21.py
> Fix for #547 : Initial proposal for ArpeggioMark and ArpeggioMarkSpanner classes.

- music21/stream/makeNotation.py
Adds test requested in https://github.com/cuthbertLab/music21/pull/1242#issuecomment-1207180391
> Demonstrate ties in `splitElementsToCompleteTuplets` doctest

- music21/musicxml/m21ToXml.py
- music21/musicxml/test_m21ToXml.py
- music21/stream/makeNotation.py
Follow up to #1242. Didn't quite fix #904 because we need to make rests _before_ making notation (if we are to have the opportunity to re-express the rests inside tuplets).
> MusicXML export: Make rests before making notation

- music21/chord/__init__.py
- music21/note.py
- music21/percussion.py
- music21/pitch.py
- music21/stream/base.py
This was failing:
```
>>> c = chord.Chord('C4 E4 G4')
>>> c.isConsonant()
True
>>> c.add('C#4', runSort=False)
>>> c.isConsonant()
True
```
The cache was only being cleared during `runSort=True`, which is the default.  But needs to happen either side.
Also caches the sort status, so repeated Chord.sort(inPlace=True) should be much faster.
> Clear cache when adding notes w/o sort

- music21/metadata/__init__.py
Adding setters back to metadata.py for properties, each with a note saying that they don't actually run.  My type checker in PyCharm was going crazy saying that title could not be set, etc. and will help with typing of the value of the setter.
Ping @gregchapman-dev @ahankinson -- good to get a set of eyes that I didn't break anything
> Add setters back for metadata-typing

- .pylintrc
- music21/test/testLint.py
@jacobtylerwalls removed it earlier, but Malcolm noticed it, so I've put it back commented out so we know to tell people to upgrade pylint if it appears.
> no-self-use is optional extension

- music21/romanText/tsvConverter.py
Fixes a small issue I noticed this morning in `handleAddedTones`.
See[(the DCML standard here](https://dcmlab.github.io/standards/build/html/tutorial/features.html#replacement-of-the-root-by-its-lower-neighbour).
> handle 0 in DCML added tones

- music21/musicxml/test_m21ToXml.py
I finally could ignore this no longer! Add a `makeNotation=True` default to test helper `getET` to encourage most unit tests to go through the usual codepath. Make explicit where existing tests actually depended on notation not being made.
> Add `makeNotation` argument to test utility

- music21/musicxml/partStaffExporter.py
The PartStaffExporter was producing `<duration>` values under `<backup>` tags that were too large by summing the durations of all chord members (instead of just taking one of the durations).
Adds a regression test failing on master:
```
FAIL: testBackupAmount (__main__.Test.testBackupAmount)
Regression test for chord members causing too-large backup amounts.
File "/Users/jacobwalls/music21/music21/musicxml/partStaffExporter.py", line 1079, in testBackupAmount
self.assertEqual(
AssertionError: '30240' != '10080'
- 30240
+ 10080
Ran 21 tests in …
```
> Prevent too large `<backup>` values in PartStaffExporter

- music21/stream/base.py
- music21/stream/tests.py
> Prevent zero-duration ChordSymbols from matching stripTies algorithm

- music21/romanText/rtObjects.py
- music21/romanText/translate.py
This PR addresses much of #858, though not (I think) the case of mid-measure repeats.
It turns out that romanText repeats were already largely implemented (by whoever wrote the romanText/translate.py, presumably), but there were a couple bugs that were preventing it from working as expected and there was no test.
I wrote some test cases and debugged the existing code. The bugs are explained in comments in the code. As far as I can tell, the repeats now work smoothly.
I also have a few (non-urgent, I think) questions in the comments. I'll repeat them here:
1. repeat.Expander does not work on stream.Stream, only on stream.Part. Is this expected behavior?
2. in the case of 1st and 2nd endings, spanner.RepeatBracket.getNumberList does not return the measure numbers I expect. What is the …
> fixed up romanText repeats

- music21/romanText/translate.py
Addresses https://github.com/cuthbertLab/music21/pull/1378#discussion_r945725373
> test repeat ending contents

- music21/metadata/primitives.py
- music21/test/test_metadata.py
Fixes a part of @gregchapman-dev comment on 38d103a
Does not create a machine readable representation for DateBetween, etc. -- happy to include that as something like 'humdrumStr()' -- since it is being parsed elsewhere, though I think the default string should be as human readable as possible.
Standardizes that Date.year / month / etc. hold int or None, not strings ever.
Sanity check month, day, hour, minute, second.
Wondering if we should be recording hour/minute/second at all -- thoroughly under tested before.
> Standardize DatePrimitive -> Date interaction

- music21/_version.py
- music21/analysis/discrete.py
- music21/analysis/transposition.py
- music21/base.py
- music21/braille/basic.py
- music21/braille/test.py
- music21/chord/__init__.py
- music21/figuredBass/examples.py
- music21/interval.py
- music21/musedata/base40.py
- music21/musicxml/partStaffExporter.py
- music21/pitch.py
- music21/roman.py
- music21/scale/__init__.py
- music21/scale/test_scale_main.py
- music21/serial.py
- music21/stream/base.py
- music21/test/multiprocessTest.py
- music21/voiceLeading.py
Store only Pitch elements in Interval(), not Notes, and depend on Pitch._client to get the notes back.
Simplifies the Interval object and speeds it up if we're not constantly looking at Pitch or Note at any moment.  Improves typing.
More importantly, the client for the Pitch will not change when transposed inPlace and therefore chordAttached on the note will also not change.  This was important with cached methods like isConsonant when one of the individual pitches in the Chord was being transposed.  Now client is informed.
> Emphasize Pitches in Interval classes

- setup.py
Requires find_namespace_packages not find_packages.
See warnings and changes at https://github.com/pypa/setuptools/issues/3340
> Setuptools Change

- music21/key.py
- music21/romanText/translate.py
Fixes #1390.
For the vast majority of cases (where there is just a single flat symbol) the regex on line 83 is overkill so we only run that if the preceding conditions don't match.
> Parse double flats in RomanText

- music21/musicxml/m21ToXml.py
- music21/musicxml/testPrimitive.py
- music21/musicxml/test_m21ToXml.py
Before this fix, the first and middle measures all had a 'stop' ending on the right barline.
> Fix (and test) writing of multi-measure RepeatBrackets to MusicXML.

- music21/converter/subConverters.py
Realizes #1415.
One difference between my new code and subConverter.writeDataStream() is that the latter calls fp.close() when fp is a file-like object. However, I don't think this is really ideal---if the caller is passing an open file, they probably expect it to remain open. (They may, for example, wish to continue writing to it later.) And in the case of writing to StringIO objects, (which is my use case) StringIO buffer contents are discarded when calling StringIO.close().
> romanText write to file-like objects

- music21/tinyNotation.py
Previously this raised an IndexError whether or not raiseExceptions was True.  Now does the best it can if raiseExceptions is False and raises a TinyNotationException if raiseExceptions is True
Also improved docs of Converter process and added more typing.
Remove weakref wrapping from a misunderstanding from before Py2.5 that circular references will not be cleaned up.  We're moving away from handling weakref garbage collection and letting Py's C-language more efficient garbage collector clean them up.  Tradeoff -- a little more temporary memory usage when parsing for faster parses.
> Closing too many states should be a TNException

- music21/base.py
- music21/sites.py
- music21/stream/base.py
- music21/stream/enums.py
- music21/test/commonTest.py
- music21/test/test_base.py
- music21/variant.py
Add proper typing for contextSites and yieldSites
Make RecurseType a Generator
differentiate between ContextTuple and ContextSortTuple
Rename newly introduced in v8 'appendOrInsert' in stream keyword to 'givenElementsBehavior' change to an enum
Find slower tests and move them up in multiprocessTest
> Add typing for contextSites, yieldSites

- music21/bar.py
- music21/instrument.py
- music21/test/commonTest.py
- music21/test/multiprocessTest.py
- music21/test/test_pitch.py
Thanks to https://github.com/conan-io/conan/issues/3441 for the inspiration
> Get rid of imp / load_source()

- music21/romanText/translate.py
While working on addressing #1412 I noticed that there was a syntax error in the romanText in `testRepeats` (my bad!). Each measure number was followed by a colon (i.e., "m1:" rather than "m1"). The first thing this PR fixes is removing those colons.
The colons caused the parser to insert a note in each measure. When I removed them, I discovered that the test was actually failing on measures that are empty except for forward/backward repeat bars. To fix this required two things:
1. explicitly set the offset of backward repeat bars according to the time-signature length
2. if a measure has 0 duration, explicitly set its duration according to the current time-signature
I also added a new test for the copying of empty measures.
> Fixes bug in repeat tests in romanText/translate.py; handles empty measures

- music21/romanText/writeRoman.py
While working on addressing #1412 I noticed that the RomanText writer is not writing out repeat bars or measure suffixes like "m1a".
I.e., previously if we read in
```
Time Signature: 2/4
m1 ||: C: I
m2 V :||
m3 ||: I :||
m4 ||: I
m5a V :||
m5b I
```
Then wrote it out, we would get
```
Time Signature: 2/4
m1 C: I
m2 V
m3 I
m4 I
m5 V
m5 I
```
This PR fixes this issue by implementing writing of repeat bars and measure suffixes.
> Romantext writer handle repeat bars and measure suffixes like m1a

- music21/_version.py
- music21/analysis/harmonicFunction.py
- music21/base.py
- music21/chord/__init__.py
- music21/chord/tools.py
- music21/roman.py
- music21/scale/__init__.py
According to published usage, transposed chords (bII, etc.) should take their 7th from the key and not be transposed.  So in c-minor, bII7 should be D-, F, A-, C, and not with C-flat.
Assuming that this would apply to 9ths, 11ths, and 13ths as well.
Does not affect interpretation of vi7, VI7, etc., I don't believe.
Slows the creation of bII, etc. RomanNumerals because a new Chord object needs to be created temporarily and `_findRoot()` run on it.
Add a new chord.tools file for routines that are too obscure to go on Chord.  Created `chord.tools.getAllChordSteps`
Fixes #1410
Credit MalcolmSailor for the notice and research on this.
> No transpose altered 7,9,11,13 in bII7; chord.tools

- music21/roman.py
- music21/romanText/translate.py
- music21/romanText/tsvEg_v2_measures.tsv
Fixes the issue in #1413. I closely modeled RomanNumeral.transpose() on Harmony.transpose().
> transpose key of RomanNumeral

- music21/_version.py
- music21/base.py
- music21/defaults.py
- music21/harmony.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/test_m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/roman.py
- music21/romanText/translate.py
RomanNumerals were creating false forwards.
RomanNumerals did not have "writeAsChord" on by default as had been documented, but they were being written as chords all the time no matter what.
Write out MusicXML 4.0 compatible harmony/numeral figures.
Also fix problem for RN transposition from RomanText that measure copied RNs share a Key.
> romanText/numerals substantial improvements; MXL4.0

- music21/abcFormat/translate.py
- music21/articulations.py
- music21/base.py
- music21/braille/basic.py
- music21/braille/test.py
- music21/clef.py
- music21/common/classTools.py
- music21/common/numberTools.py
- music21/corpus/testCorpus.py
- music21/duration.py
- music21/interval.py
- music21/layout.py
- music21/mei/base.py
- music21/metadata/__init__.py
- music21/midi/translate.py
- music21/musedata/translate.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/test_xmlToM21.py
- music21/musicxml/xmlToM21.py
- music21/note.py
- music21/repeat.py
- music21/spanner.py
- music21/stream/base.py
- music21/stream/iterator.py
- music21/stream/tests.py
- music21/test/commonTest.py
- music21/test/test_repeat.py
- music21/tinyNotation.py
Use v3.10 features
Add typeguards to isIterable isNum
common.classTools: isInt (int not True, False),  holdsType (does it hold a particular type?)
> use more v3.10 features. TypeGuards

- music21/base.py
- music21/braille/basic.py
- music21/braille/lookup.py
- music21/braille/translate.py
- music21/common/stringTools.py
- music21/converter/__init__.py
- music21/converter/subConverters.py
Adds converter.toData -- a drop in for getting the raw data from a format.
Improve documentation for Braille
> Add converter.toData, improve braille docs

- documentation/docbuild/documenters.py
- documentation/docbuild/make.py
- documentation/source/_themes/m21/static/m21.css
- music21/articulations.py
- music21/clef.py
- music21/common/decorators.py
- music21/dynamics.py
- music21/instrument.py
- music21/key.py
- music21/note.py
- music21/repeat.py
- music21/scale/__init__.py
- music21/scale/intervalNetwork.py
- music21/tempo.py
- music21/text.py
- music21/voiceLeading.py
Can't yet do deprecated properties.
Mark deprecated methods as `._isDeprecated` in their dicts.
Add many missing `**keywords`
Improve docs for enums
> Strike through deprecated in docs

- music21/analysis/discrete.py
- music21/base.py
- music21/key.py
- music21/note.py
- music21/pitch.py
- music21/stream/base.py
- music21/tie.py
This is a cleanup PR that prepares for implementing #1458.  I want to get this part right before putting in a commit that might break things.
Key and KeySignature were the only Music21Objects that implemented __hash__ -- they should not be hashable, since they are mutable, like all M21 objects.
> Pre-equality: rem hash

- music21/environment.py
I've been working in music21 and had to override `musicxmlPath` in order for it to find my fresh install of Musescore. I have not yet tested my edit to see if it functions correctly, as it seems that this could break existing music21 setups and wanted to open the discussion before going further on this effort. I have time set aside Sunday to test this edit, and will report back at that time unless we have conversation come up before then. 
This could break existing music21 setups where the default works on a user's computer that has a Musescore installation in the old location, but is important for people who are installing music21 for the first time. Music21 has built in assumptions about an old version of Musescore, meaning that a new installation of music21 today is not set up to use a …
> updated location of Musescore in Windows to match updated installer

- music21/languageExcerpts/instrumentLookup.py
This small change is needed for a lot of orchestral scores with part names like "Horns 1 and 2 in Eb"
> horns typically hunt in pairs

- music21/musicxml/testPrimitive.py
- music21/musicxml/test_xmlToM21.py
- music21/musicxml/xmlToM21.py
> Preserve multiple articulations on chords in musicxml import

- .github/workflows/pythonpylint.yml
- music21/roman.py
Closes #1450
Previously, RomanNumerals created with integer figures were always uppercase, even when `caseMatters` was True.
Now, certain figures are lowercased according to the mode.
***
cc/ @MarkGotham would you be willing to review?
I didn't use structural pattern matching per this comment:
https://github.com/cuthbertLab/music21/blob/d77f4059a6943aa43b0dea388faa2bf2b8257c6c/music21/midi/translate.py#L1281-L1283
> Lowercase some RomanNumeral figures created with integers

- music21/harmony.py
Add a convenience `__eq__` comparison for `ChordStepModification` to avoid having to compare each property manually.
> Add `__eq__` for ChordStepModification

- music21/musicxml/m21ToXml.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/test_xmlToM21.py
- music21/musicxml/xmlToM21.py
- music21/stream/base.py
- music21/stream/enums.py
Requested at https://groups.google.com/g/music21list/c/vMaz9wJVPyc.
Used `numberImplicit` to rhyme with attributes on MetronomeMark.
> Translate "implicit" attribute of MusicXML measures

- music21/midi/translate.py
The associated _coreInsert call was removed in #1225 without also removing coreElementsChanged() afterward.
> Remove unnecessary coreElementsChanged() call

- documentation/source/usersGuide/usersGuide_33_expressions.ipynb
- documentation/source/usersGuide/usersGuide_43_searching1.ipynb
This keyword is mentioned back in ch. 8, but it's described as ~_you don't need it_, so I was surprised to see it pop up here.
> Remove `forceSource=True` from user's guide examples

- music21/base.py
- music21/harmony.py
Fixes #1500 by not creating duplicative ChordStepModifications.
Also:
- Avoid unnecessary casting to tuple and back in `_adjustPitchesForChordStepModifications()`
- Default ChordStepModification.interval to perfect unison to avoid None != Interval('P1')
> Avoid creating duplicative ChordStepModifications

- music21/stream/base.py
This approach uses False to distinguish "no gaps" from "force a cache miss" (None), although this has to then be converted back to None for cache hits.
An alternative would be to rewrite the cache (there aren't that many keys) to just delete keys when intending to force cache misses.
Another alternative would be to break BC and have findGaps() return something else, like an empty stream that would still test False.
Closes #1514
> Cache result of findGaps() on gapless streams

- music21/converter/__init__.py
This is a change to help the converter21 project.
Newly registered converters that support the same extensions and formats as existing ones have priority.
After being deregistered, the normal format takes over.
for @gregchapman-dev and the converter21 Humdrum/MEI project.
> New subconverters register above default

- music21/musicxml/m21ToXml.py
- music21/musicxml/test_m21ToXml.py
Adding IDs to measures in MusicXML files. I added a call to _synchronizeIds(), just as it works already for other elements (eg, notes).
> Synchronize Measure IDs on Musicxml out

- music21/repeat.py
Unused since introduction in b7d430af25bbd1adb10d5b8429542e8c5b194b72.
> Remove Expander._srcNotMeasureStream

- music21/percussion.py
`PercussionChord.pitches` until now just fell back to the NotRest implementation that returns `()`. Now, it does something useful: setting, has parity with Chord; getting, has additional safety to filter out Unpitched instances in the `._notes` array.
TODO statement is just copied from Chord.pitches.
> Implement useful `PercussionChord.pitches` property

- music21/analysis/discrete.py
> Ignore Unpitched objects in key analysis

- music21/_version.py
- music21/base.py
- music21/midi/translate.py
- music21/stream/base.py
- music21/stream/tests.py
Fixes #1536 by improving the algorithm that "looks ahead" to minimize gaps when quantizing durations from its first draft in #1062, as long as the stream is sorted first.
Looking ahead was the right idea, but using the same divisor was not right, because in a passage of triplets, on beats, you have a tie between divisors (for calculating offsets). For the screenshotted example below, that means the last triplet-eighths of a beat were quantized as sixteenths (because there was a tie for the "best divisor" for the quantization of the offset at the X.0 beat).
This refactor solves the reported issue and also includes a simpler way of achieving #641's requirement of nonzero durations on non-grace notes.
- This also uncovered some infelicities with Stream.insert(ignoreSort=True), adding an …
> Minimize gaps produced by quantization algorithm

- music21/converter/__init__.py
- music21/converter/subConverters.py
- music21/romanText/clercqTemperley.py
de Clercq / Temperley files were being exported with all measure numbers set to 0.  Now they are properly numbered.
Deprecate `toScore` in CT parsing, add `toPart` since the format currently returns a Part object.  (this should be changed to a Score object instead to fit w/ RomanText parsing, but not done now).
Typing improvements for the converter.
> Improve measure numbers on ClercqTemperley

- music21/converter/subConverters.py
A recent update to music21j on github.io broke MIDI output in Jupyter notebooks in music21.  This will fix it.
Backport to v8
> fix jupyter/colab MIDI

- music21/musicxml/m21ToXml.py
We copy the score object early to avoid modifying it when calling `.write("musicxml", *)`
See #1557
@jacobtylerwalls
> Avoid altering score on write

- music21/corpus/virtual.py
Was playing with [this tool](https://github.com/carljm/compfinder) and wondered why it couldn't parse the AST for `corpus.virtual`. Answer: it has a [byte order mark](https://www.freecodecamp.org/news/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7/).
> Remove byte order mark from corpus.virtual

- music21/midi/__init__.py
Fixes #1574
When loading a MIDI file, messages can set a (running) status byte. However, meta messages don't set the status byte. 
This leads to problem on several MIDI files, for example 8584aaa73eb54bae39708da8be5e6282.mid from the lakh dataset.
It could be argued that the `!= 0xff` check is too conservative as running status is only applicable for messages in the range `0x8n - 0xEn`, the proposal is this way to be aligned with other python midi libraries:
https://github.com/mido/mido/blob/bff6bf2a8711e33782de5661ed5ccdffb0bb1688/mido/midifiles/midifiles.py#L204-L206
> Don't set status byte on Meta Message (Fix #1574)

- music21/features/jSymbolic.py
- music21/features/native.py
- music21/stream/base.py
- music21/stream/tests.py
When a stream contains two notes/chords that contain the same pitch, but one has a "neutral" accidental and the other one doesn't have an accidental at all (None), the tied notes weren't matched even though they should. 
This happens e.g., for quite a lot musicxml files from the ASAP dataset.
It's debatable whether this change should really take place in the pitch.Pitch class, where the `__eq__` method could be adapted to interpret a "neutral" accidental to be equal to a None accidental.  
This seemed like the less intrusive option, but I'm happy to change the PR as well. 
Let me know what you think!
> Fix stripTies when accidentals are neutral & none

- music21/abcFormat/__init__.py
- music21/abcFormat/testFiles.py
- music21/abcFormat/translate.py
- music21/defaults.py
- music21/meter/base.py
- music21/spanner.py
Previously only `%abc-2.1` on the first line was enough to set the version number.  Now `I:abc-version 2.1` can be set anywhere.
Note that unlike the 2.1 format, the version Information header affects everything from that point forward within one song.  The last version does take effect, but different versions may be given within the same file and the one in effect at that moment will carry forward.
Added lots of typing and fixed some bugs.
> Set ABC version from I:abc-version information

- music21/stream/base.py
During quantization, rests that end up with duration 0 are deleted.
Previously, the list of rests to be deleted was not reset after finishing with a substream, yielding extremely slow performance on big scores as the code attempted to delete all previously found (and already deleted) rests again in each following substream.
> Speed up quantize()

- music21/search/base.py
Doesn't do anything really useful but doesn't crash.
Add typing to module.
(Note: this module should return bytes not strings; Py2 legacy)
Fixes #1596
> Search.base with Unpitched etc

- documentation/docbuild/make.py
- documentation/docbuild_requirements.txt
- music21/converter/__init__.py
Overzealous on improving.
Also fix a bug in docbuild on readthedocs.io (unrelated, but the branch was read)
> Add unregisterSubconverter alias back

- .readthedocs.yaml
- music21/common/misc.py
- music21/converter/__init__.py
Converter.subconvertersList, Converter.defaultSubconverters , Converter.getSubconverterFormats, and setSubconverterFromFormat are all restored.
Note that most of these have been converted in their newer capital-C form to also be callable from the Class (staticmethods) -- this has not been added to the old forms which behave like before.
also keep taking every opportunity to see what readthedocs.io wants...
> substitute deprecation for removal: converter.py

- dist/dist.py
- music21/_version.py
- music21/base.py
- music21/pitch.py
- music21/scale/intervalNetwork.py
- music21/test/test_pitch.py
- requirements_dev.txt
Better errors are now given on invalid pitch creation like '60' (string) instead of 60 (int).
Tightens up a bug discovered by @vanderstel  (private communication) where Pitch('2D#5') was allowed and created a D# in octave 25.
(unrelated tiny dist.py improvements added here -- notes from release of 9.0 -- change version to 9.2 beta
> Better errors on pitch creation

- requirements_dev.txt
Flake8-quotes now has a compatible version which is what we were waiting for.
Now no versions are pinned to less-than-highest.
> Upgrade flake8 to v6

- music21/tree/fromStream.py
- music21/tree/node.py
Very slightly improves the performance of `updateEndTimes` which is called millions of times in some tree-related tasks.
Does not affect functionality. Same for `recurseGetTreeByClass`.
> Mini-optimization to updateEndTimes

- music21/duration.py
Instead of updating the components during deepcopy (which is expensive), we can defer this update until it is actually needed and just copy the object for now. This speeds up tasks that use derivations (e.g. `quantize`) by up to 30% on my machine.
> Speed up Duration deepcopy

- music21/stream/base.py
Replaces an unnecessary sort with max and simplifies the remaining logic of the function.
> Mini-optimization to getElementAtOrBefore

- music21/common/types.py
- music21/stream/base.py
- music21/stream/iterator.py
following on @TimFelixBeyer 's work in #1618
> more speed improvements to getElementAtOrBefore

- music21/base.py
This avoids the computation of the duration attribute when creating a stream's `sortTuple`, which is expensive as it requires iterating over all elements to compute `highestTime`.
Yields significant speedups on tasks that require sorting (12% overall for a simple load + quantize benchmark on my machine).
> speed up sortTuple for streams

- music21/common/stringTools.py
- music21/test/testRunner.py
adds stringTools.parenthesesMatch and a use of it in testRunner.
Does enough for this to be Fixes #1563 -- we can change other places as other PRs.
@jacobtylerwalls -- can you eyeball this or test it on 3.12?  I don't have my test computer where I install Python betas anymore.
> Fix OrderedDict tests on Python 3.12 (stringTools.parenthesesMatch)

- music21/stream/base.py
- music21/stream/core.py
Instead of comparing the result of the `id` function between objects, we can use the built-in `is` operator to achieve the same in half the time. `coreHasElementByMemoryLocation` was only used this one time and can therefore be removed as well.
> Speed up hasElement by 2x

- music21/musicxml/helpers.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlSoundParser.py
- music21/musicxml/xmlToM21.py
- music21/noteworthy/binaryTranslate.py
Going in the opposite direction as #1599 -- move MusicXML `<sound>` tag parsing to a separate file along with several helpers to helpers.py -- both m21ToXML and xmlToM21 are getting huge! so anything to try to make these files more manageable is the right direction.
While fixing mypy errors, noticed a bunch of warnings that things that were typed were not being checked in noteworthy/binaryTranslate.py -- checked these and fixed.  (TODO: make the contents of untyped functions are not checked become an error in CI)
> SoundParser to a separate file

- music21/analysis/reduction.py
- music21/base.py
- music21/freezeThaw.py
- music21/stream/base.py
- music21/test/test_base.py
Follow up to #1621.
I am aware of the dev sabbatical, just opening the PR now so I don't forget about it later...
Proposal:
`hasElement` has identical functionality to `__contains__`. Since the Zen of Python teaches us that "There should be one-- and preferably only one --obvious way to do it.", I propose deprecating `hasElement` in favor of the more concise and pythonic `__contains__`.
In addition, I have  optimized the speed of the function by adding the fast `offsetDict` check to `__contains__`, and after stumbling on [this discussion](https://stackoverflow.com/questions/44802682/python-any-unexpected-performance), and changing the calls to `any`, the changes resulted in about a 2x speed-up on my machine, which is significant since the contains check is used a lot throughout the …
> Speed up __contains__ by 2x and deprecate hasElement

- music21/roman.py
`add10` annotations (which occur when converting some DCML files) were causing a bug because the 0 was being converted to `o`, leading to parsing exceptions.
This PR updates the replace logic for `0` so as not to match this case, and adds a test case to the unit test.
> Roman Numerals: Don't substitute `d` for `0` in `add10`

- music21/romanText/tsvConverter.py
- music21/romanText/tsvEg_v2major.tsv
The regex to add `d` to Mm7 chords on degrees other than 5 was giving false positives for cases like `[add13]`, where it would match the `1`, resulting in `[addd13]`. This PR fixes that bug.
I added 2 test cases to `tsvEg_v2major.tsv` and discovered that there was another bug where the `d` syntax (e.g., for `IVd7`) was not being removed when converting from Music21 to DCML tsv, although it is not used in the latter standard. So I also added a fix for that.
> TSV converter bug fix: don't add 'd' prefix to 2-digit added tones like `[add13]`

- .github/workflows/maincheck.yml
- music21/__init__.py
- music21/abcFormat/__init__.py
- music21/audioSearch/recording.py
- music21/common/stringTools.py
- music21/humdrum/questions.py
- music21/metadata/__init__.py
- music21/metadata/primitives.py
- music21/musicxml/test_xmlToM21.py
- music21/note.py
- music21/scale/test_intervalNetwork.py
- music21/test/coverageM21.py
- music21/test/testLint.py
- pyproject.toml
Make music21 test suite fully compatible with Python 3.12 -- because the basic functionality of music21 works without change in music21, I'm not going to break sabbatical to do a new release for this, but all code tests going forward should also run on 3.12.
Minimum version remains 3.10.
Move coverage, flake8, and pylint to 3.11 -- keeping with general music21 policy to test these things on the middle version of Python supported, so that changes in run-time from oldest to newest versions can be observed.  (The middle version has more things its doing so it's always the slowest).
Thanks to @jacobtylerwalls for the fix in advance for the new OrderedDict syntax.
> Python 3.12 Compatibility

- music21/_version.py
- music21/base.py
- music21/musicxml/test_xmlToM21.py
- music21/musicxml/xmlToM21.py
We all know the ugly offsets (3875/480, 161/180, etc.) that happen after importing some musicXML files.
This usually occurs because the file contains tuplets with strange durations that cannot be represented exactly using integer `<duration>` tags in musicXML. For this reason, rounding errors can accumulate and lead to over/underfull measures.
Currently, if a measure is overfull, music21 just accepts that as a fact and increases the duration of the measure, shifting all following objects and resulting in them having very odd offsets. 
This proposal deals with this by automatically detecting such cases, warning the user, and fixing them. 
The change only affects behavior if the measure duration resulting from the contained notes differs from the duration dictated by the time signature by …
> Fix ugly MusicXML durations & offsets

- music21/chord/__init__.py
This PR extends the approach from https://github.com/cuthbertLab/music21/pull/1245 by accounting for minor 7th chords that are spelled enharmonically as C-E-G-Bbb.
Pinging @jacobtylerwalls since he wrote the original code, but would welcome a review from any contributor.
> Improve commonName for enharmonic equivalent to minor seventh chords

- music21/environment.py
I came across this problem when running a script on a compute cluster where the home dir exists, but is mounted read-only when running on the actual compute node.
In this case we should store the .music21rc file in /tmp.
> check if HOME directory is writeable in getSettingsPath

- music21/converter/__init__.py
Fixes error reported in https://github.com/cuthbertLab/music21/pull/1664#issuecomment-1817500436.
Adds missing coverage.
> Fix argument annotation in `converter.parse()` signature

- music21/tree/verticality.py
Make Verticality.makeElement aware of unpitched objects.
Supersedes #1652 -- which pointed out an important bug but didn't put the onus on type-safety on the calling attribute.
> Verticality.makeElement unpitched aware

- music21/musicxml/xmlToM21.py
Currently, it's not possible to access frets and string information in guitar tablatures for chords after conversion from musicXML, because StringIndication and FretIndication objects are stored in chord.articulation property only for a single (lowest) note of a chord.
E.g., when running the attached example with very simple musicXML, expected:
`<music21.chord.Chord D3 A3 D4 F4 A4>
[<music21.articulations.FretIndication 5>, <music21.articulations.StringIndication 5>, <music21.articulations.FretIndication 7>, <music21.articulations.StringIndication 4>, <music21.articulations.FretIndication 7>, <music21.articulations.StringIndication 3>, <music21.articulations.FretIndication 6>, <music21.articulations.StringIndication 2>, <music21.articulations.FretIndication 5>, …
> In conversion from musicXML, allow multiple {Fret/String}Indications for chord.

- music21/musicxml/xmlToM21.py
`hyphenToCamelCase` from common.stringTools.py currently gets called twice for every note in a piece when importing an xml file. This can be avoided by passing an `attributeName` argument when using the `_setAttributeFromTagText` method to set the step and octave properties of notes.
With this change, when importing a file like:
`score = corpus.parse('joplin/maple_leaf_rag.mxl', forceSource=True)`
`_setAttributeFromTagText` goes from being called over 30k times to about 120 times. Since all the string manipulation in hyphenToCamelCase has no impact on one-word strings, all these avoided calls were unnecessary.
> Avoid calling hyphenToCamelCase twice per note

- music21/harmony.py
Fixes #1685.
Corrects parsing error for harmony strings and adds regression test for #1685.
> Fix #1685: Harmony parsing errors with doubled characters

- music21/analysis/reduceChords.py
- music21/analysis/reduceChordsOld.py
- music21/analysis/windowed.py
- music21/braille/text.py
- music21/common/objects.py
- music21/features/jSymbolic.py
- music21/figuredBass/realizer.py
- music21/humdrum/spineParser.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/xmlToM21.py
- music21/scale/intervalNetwork.py
- music21/stream/base.py
- music21/stream/iterator.py
- music21/stream/makeNotation.py
- music21/test/treeYield.py
- music21/tree/core.py
- music21/tree/node.py
- music21/voiceLeading.py
Pylint now recommends using `yield from` and the use of `min/max` to simplify if statements.
> Fix pylint recommendations

- music21/chord/__init__.py
- music21/note.py
This PR adds the 'fa up' notehead type, which is included in the official [MusicXML spec](https://www.w3.org/2021/06/musicxml40/musicxml-reference/data-types/notehead-value/).
While it is rarely used, it should still be included as it currently leads to import errors for MusicXML files that use it.
> Add 'fa up' notehead type

- .idea/inspectionProfiles/Project_Default.xml
- music21/pitch.py
- music21/tinyNotation.py
Also ignoring more_itertools in JetBrains IDEs.  For some reason has been broken for a long time.
> Small spelling edits etc. (Misc-April-2024)

- music21/harmony.py
(was 'Bbpedal', should be 'B-pedal')
> A few ChordSymbol fixes

- music21/roman.py
Fixes #1653: We cannot use the name of a `ConcreteScale` to cache the scales as there are sometimes different scales with the same name but different pitches. Using the pitch list and names now to be more precise and avoid collisions.
Also adds a regression test. (and a small unrelated simplification).
> Fix #1653: Correct scale caching mechanism.

- music21/chord/__init__.py
Fixes #1382. Had a look at the mentioned thread and found that the duration code can indeed be simplified a bit.
Chords basically have two ways of setting their duration.
Either the duration is specified explicitly in the keywords of the constructor (via `duration`, `type`, or `quarterLength`), or it must be inferred from the notes contained in the chord (via `_add_core_or_init`).
> Fix #1382: Simplify ChordBase duration creation

- music21/abcFormat/__init__.py
- music21/braille/segment.py
- music21/chord/__init__.py
- music21/duration.py
- music21/humdrum/spineParser.py
- music21/interval.py
- music21/metadata/__init__.py
- music21/musicxml/m21ToXml.py
- music21/romanText/clercqTemperley.py
- music21/scale/__init__.py
- music21/tree/verticality.py
Just some small tweaks in the spirit of #1631 and #1683 that don't change the functionality.
> Small simplifications and speed-ups

- music21/pitch.py
Fixes #1689 where the spelling of a pitch was dependent on its octave.
This was a result of the _dissonanceScore computing Pythagorean ratios between the keyContext (which contributes a Pitch without Octave), and the given pitches. Now, the ratios are always computed between Pitches without Octaves to ensure correct scoring.
Adds a regression test and code simplifications as well.
> Make `_dissonanceScore` independent of octaves

- music21/musicxml/xmlToM21.py
- music21/stream/filters.py
MusicXML import: forward tags with voice should trigger the same behavior as note tags with voice.
I see this quite a bit in leadsheets where these are used to position chordsym changes within a single melody note.  The result should be a second voice containing only hidden rests, but instead, they land in the measure with the notes, and they overlap.
> A few leadsheet-related fixes

- .pylintrc
- music21/figuredBass/resolution.py
- music21/romanText/tsvConverter.py
- music21/stream/base.py
a little cleanup of typing and fix docs
> Cleanup on TSV-DCML Converter

- music21/base.py
- music21/braille/basic.py
- music21/chord/__init__.py
- music21/derivation.py
- music21/meter/core.py
- music21/note.py
- music21/stream/base.py
- music21/style.py
- requirements.txt
Many changes in Numpy 2.0 -- fixing other changes in other dev systems.
> Respond to Changing Dev systems; Pin Numpy to <2.0

- music21/musicxml/m21ToXml.py
- music21/musicxml/test_m21ToXml.py
**Before**
Stem styles were only exported if a stemDirection was explicit.
**Now**
If a stem has style information, the stem direction is calculated and the stem element is written with style info.
Fixes #1724
> Export stem styles on notes with implicit stem directions

- music21/common/numberTools.py
- music21/meter/base.py
- music21/meter/core.py
- music21/meter/tools.py
- requirements.txt
Working on better Meter in music21j, and needed to better understand how meter works in m21p, so added some typing.
> Improve typing on Meter.Core

- README.md
- documentation/source/usersGuide/usersGuide_14_timeSignatures.ipynb
- music21/meter/base.py
- music21/meter/tools.py
- music21/note.py
- music21/tinyNotation.py
- music21/tree/verticality.py
This is a bit of cleanup before fixing a bigger TN problem of Issue #1733.
> Some Note/TinyNotation typing

- .pylintrc
- music21/base.py
- music21/figuredBass/resolution.py
- music21/stream/base.py
- music21/stream/tests.py
- music21/test/testLint.py
Fixes #1735
Adds tests.
Thanks to Giulio Guilherme de Souza Simão for the perfect bug report!
> Fix Stream splitByQuarterLengths

- dist/dist.py
- music21/_version.py
- music21/base.py
> Create 9.4beta for 9.5 or 10.1

- documentation/source/about/about.rst
- pyproject.toml
Congrats on the release! Spotted these potential additions while approving a PR from a conda bot to package 9.3 for conda.
Thanks for shout out in the docs! Spotted an "o" in my middle name, but decided to just skip the whole word, since I don't really go by that anywhere but gmail and my url, although I may need to in the future to disambiguate me from the other Jacob Walls on spotify...
> Pyproject updates

- .idea/inspectionProfiles/profiles_settings.xml
- README.md
- music21/__init__.py
- music21/common/enums.py
- music21/license.txt
- music21/romanText/translate.py
> Happy New Year 2025

- music21/base.py
- music21/chord/__init__.py
- music21/common/enums.py
- music21/common/numberTools.py
- music21/common/pathTools.py
- music21/environment.py
- music21/graph/axis.py
- music21/graph/plot.py
- music21/graph/primitives.py
- music21/key.py
- music21/note.py
- music21/pitch.py
- music21/sites.py
- music21/stream/base.py
- music21/stream/iterator.py
- music21/tree/verticality.py
- requirements_dev.txt
upgrade astroid and get better information about overloads -- this was a long-awaited improvement.  Thanks to @jacobtylerwalls for the mypy contributions!
some attempts at fixes of graph for microtonal but no work there.
Information about deprecation of StrEnum in the distant future
> Astroid 1015 + misc improvements jan

- music21/interval.py
be stricter -- getWrittenHigherNote either needs two notes or two pitches, not one of each -- the return type should not depend on which is higher.
> update interval Typing overloads

- dist/dist.py
- music21/_version.py
- music21/base.py
- requirements_dev.txt
Update version for 9.6 beta development
Change the dev requirements to match what Jacob Walls had suggested but that I forgot to do (remove astroid and pin pylint to 3.2 or higher.
Update last couple parts of dist.py
> Start 9.6 beta - update requirements.dev

- music21/common/enums.py
- music21/midi/base.py
- music21/midi/realtime.py
- music21/midi/tests.py
- music21/midi/translate.py
Deprecate many pre-Python3 (unicode vs. bytes) functions.
Hide channel information for non-channel events.
> Finish typing Midi.base

- music21/_version.py
- music21/base.py
- music21/chord/__init__.py
- music21/harmony.py
- music21/musicxml/m21ToXml.py
- music21/musicxml/test_m21ToXml.py
- music21/musicxml/xmlToM21.py
Fixes #1756
Allow ChordSymbols to specify inversion and bass and round-trip them properly.
Adds several missing tests and corner case coverage
> Roundtrip inverted chord symbols properly

- music21/_version.py
- music21/alpha/analysis/aligner.py
- music21/analysis/discrete.py
- music21/base.py
- music21/braille/segment.py
- music21/converter/subConverters.py
- music21/layout.py
- music21/midi/base.py
- music21/midi/tests.py
- music21/midi/translate.py
- music21/text.py
Followup from #1769 gave me an opportunity to find places to improve midi translate.  Pinging @oxygen-dioxide since some changes took place since then
* Change `getNotesFromEvents()` from potentially O(n^2) to O(n) while retaining sort order.
* Pass encoding to parsing of instrument names in addition to lyrics (renamed "encoding_type" to "encoding" -- missed in prior review)
* create TimingNoteEvent which is a typed NamedTuple that keeps track of when a MidiEvent NoteOn started, stopped, and what the NoteOn event was.  Replaced the old tuple of tuples.
* Faster gathering of Chords (remove potential O(n^2) search).
* Remove unused special case for single-note streams.
* opFrac many offsets and durations in MIDI for absolutely correct tuplets, etc.
* Misc: Update braille.translate …
> midi.translate improvements

- music21/converter/subConverters.py
- music21/midi/tests.py
- music21/midi/translate.py
Midi files can contain lyrics. After this PR, the midi file exported from music21 will contain lyrics, which will show if you open it with musescore.
I've implemented reading lyrics from midi in #1769
Users can select the encoding which encoding to use when exporting by using `stream.write('midi', fp=filename, encoding=encoding)`. The default encoding is UTF-8.
> Support writing lyrics to midi

- music21/analysis/discrete.py
- music21/bar.py
- music21/chord/__init__.py
- music21/derivation.py
- music21/interval.py
- music21/musicxml/partStaffExporter.py
- music21/musicxml/xmlToM21.py
- music21/note.py
- music21/percussion.py
- music21/roman.py
- music21/stream/makeNotation.py
Improve typing for music21 based on issues uncovered in mypy 1.16.
Fix error in `Interval.noteEnd = None` -- setting noteStart, noteEnd, pitchStart, or pitchEnd to None raised exceptions
> Fix mypy 1.16 issues

- music21/stream/base.py
- music21/stream/tests.py
When calling `stream.Score.partsToVoices`, only `notesAndRests` are merged into the new part. We can also merge the spanners from those parts into the new one.
> Also merge spanners when calling stream.Score.partsToVoices

- .devcontainer/README-Codespace.txt
- .devcontainer/devcontainer.json
GitHub codespace is an online Linux environment with a vscode web UI. It is useful for developers who don't have a Linux device but want to test if their code works on Linux.
> Add github codespace support

- music21/musicxml/__init__.py
- music21/musicxml/testFiles.py
- music21/musicxml/test_xmlToM21.py
- music21/musicxml/xmlToM21.py
- music21/stream/base.py
- music21/stream/tests.py
Longstanding bug discovered by @seffka and @OttavioCresos - thank you for the careful explanation and the amazing test file that made fixing this "almost" simple. 
Added to template() `exemptFromRemove` -- and removeAll (separate from removeClasses=True which will be removed in v10
Deprecate some unused test helpers.
Fixes #1812
> Support RepeatBrackets for pianos

- .readthedocs.yaml
- README.md
- documentation/source/installing/installLinux.rst
- documentation/source/installing/installMac.rst
- documentation/source/installing/installWindows.rst
- music21/common/enums.py
- music21/converter/__init__.py
- music21/instrument.py
- music21/mei/base.py
- music21/metadata/__init__.py
- music21/meter/core.py
- music21/midi/base.py
- music21/midi/tests.py
- music21/midi/translate.py
- music21/musicxml/testFiles.py
- music21/prebase.py
- music21/roman.py
- music21/tablature.py
- music21/test/testRunner.py
- music21/test/test_base.py
Add MIDIEvent.isChannelEvent() to distinguish MIDIEvents where channels matter from ones which don't (since None is no longer an acceptable channel).  Update getChannels() to use it
Add midiEventToInstrument (singular event) and deprecate midiEventsToInstrument -- do it right or not at all.
Remove channel on midi.translate.getEndEvents
Use Python 3.11 error messages
Remove deprecated MeterSequence.flat -> for .flatten() Remove deprecated musicxml/testFiles.get(contentRequest) -- never used.
Add better docs to music21/prebase
make roman. _postFigureFromChordAndKey private as promised.  Leave figureTuples as public.
remove RomanException -- just use RomanNumeralException
clean up docs for v3.11
> MIDI/Instrument improvements + Misc
